COM-1426 can detach step from subprogram
sophiemoustard/alenvi-api pull request #1008
Opened 2020-08-27 14:37 UTC by cmolle

- [x] Mon code est testé unitairement
- [x] Mon code est testé avec des tests d'intégration

- Périmetre interface : vendeur

- Périmetre roles : admin/rof

- Cas d'usage : Je peux detacher une etape d'un sous programme

2020-08-27 16:04 UTC, KennyCallegari approved these changes

2020-08-28 07:14 UTC, sophiemoustard requested changes

2020-08-28 07:14 UTC, sophiemoustard commented on src/controllers/subProgramController.js
> +    };
sur une ligne

2020-08-28 07:14 UTC, sophiemoustard commented on src/routes/preHandlers/subPrograms.js
> +  const subProgram = await SubProgram.findOne({ _id: req.params._id, steps: req.params.stepId }).lean();
countDocument ? c'est mieux niveau perf

2020-08-28 07:14 UTC, sophiemoustard commented on tests/integration/subPrograms.test.js
> +      expect(subProgramUpdated.steps.length).toEqual(stepsLengthBefore - 1);
tu peux verifier aussi que l_id n'est plus inclu

2020-08-28 07:14 UTC, sophiemoustard commented on tests/integration/subPrograms.test.js
> +        url: `/subprograms/${invalidId}/steps`,
il manque l'id de l'etqpe

2020-08-28 12:49 UTC, sophiemoustard approved these changes

2020-08-28 12:50 UTC, merged