COM-1437 detach activities
sophiemoustard/alenvi-api pull request #1014
Opened 2020-08-31 13:48 UTC by CorentinMartinot

- [x] Mon code est testé unitairement
- [x] Mon code est testé avec des tests d'intégration

- Périmetre interface : vendeur

- Périmetre roles : admin rof

- Cas d'usage : retrait d'une activité

2020-08-31 15:01 UTC, sophiemoustard requested changes

2020-08-31 15:01 UTC, sophiemoustard commented on src/controllers/stepController.js
> +    };
sur une ligne

2020-08-31 15:24 UTC, CorentinMartinot commented on src/controllers/stepController.js
> +    };
done

2020-09-01 10:36 UTC, cmolle commented on src/controllers/activityController.js
> +    return { message: translate[language].activityFound, data: { activity } };
Je crois qu'on le laisse plutot sur deux lignes lorsqu'il y a le message et data

2020-09-01 10:36 UTC, cmolle commented on src/controllers/activityController.js
> +    return { message: translate[language].activityFound, data: { activity } };
Je crois qu'on le laisse plutot sur deux lignes lorsqu'il y a le message et data

2020-09-01 10:36 UTC, cmolle commented on tests/integration/steps.test.js
> +      expect(stepUpdated.activities.length).toEqual(0);
Pour eviter de casser les tests quand on change les seed, on pourrait plutot verifier que la taille a bien diminuer de 1

2020-09-01 11:02 UTC, sophiemoustard approved these changes

2020-09-01 11:06 UTC, KennyCallegari approved these changes

2020-09-01 15:00 UTC, cmolle approved these changes

2020-09-01 15:00 UTC, merged