Com 1464 - ActivityHistory
sophiemoustard/alenvi-api pull request #1028
Opened 2020-09-11 12:59 UTC by KennyCallegari

- [x] Mon code est testé unitairement
- [x] Mon code est testé avec des tests d'intégration

- Périmetre interface : VENDOR

- Périmetre roles : admin

- Cas d'usage : 
Ajout d'une activityHistory - contenant un userId, une activityId et une date - lorsque qu'une activité est terminée

2020-09-11 13:07 UTC, sophiemoustard requested changes

2020-09-11 13:07 UTC, sophiemoustard commented on src/routes/index.js
> +    routes: { prefix: '/activity-histories' },
on ne met pas de tiret

2020-09-11 13:07 UTC, sophiemoustard commented on src/routes/activityHistories.js
> +        auth: { scope: ['programs:edit'] },
tout le monde peut faire ca : justement il n'y a pas de droit sur cette route car tous les utilisateurs, meme ceux sans role peuvent le faire

il faut juste etre connecté

par contre tu peux verifier dans un prehandler que l'utilisateur est bien inscrit a une formation avec cette activité...

2020-09-11 13:07 UTC, sophiemoustard commented on tests/integration/activityHistories.test.js
> +      { name: 'trainer', expectedCode: 403 },
il manque admin vendor

2020-09-11 13:07 UTC, sophiemoustard commented on src/routes/activityHistories.js
> +        auth: { scope: ['programs:edit'] },
++ verifier dans le prehandler que l'utilisateur existe et que l'activité aussi

2020-09-11 13:07 UTC, sophiemoustard commented on tests/unit/helpers/activityHistories.test.js
> +    ActivityHistoryMock = sinon.mock(ActivityHistory);
tu peux faire un stub directement car tu ne chaines pas

2020-09-11 13:07 UTC, sophiemoustard commented on tests/unit/helpers/activityHistories.test.js
> +require('sinon-mongoose');
ce n'est pas utile

2020-09-11 13:08 UTC, KennyCallegari reviewed
Deux problèmes que j'ai constaté mais je ne sais pas quoi en faire :
Il est possible de créer deux activityHistories pour la même activité et le même user
Date.now donne l'heure pour l'utc 0 (donc une heure de moins que Paris)

2020-09-11 13:11 UTC, sophiemoustard commented
> Deux problèmes que j'ai constaté mais je ne sais pas quoi en faire :
> Il est possible de créer deux activityHistories pour la même activité et le même user
> Date.now donne l'heure pour l'utc 0 (donc une heure de moins que Paris)

pour le premier point que tu mentionness `Il est possible de créer deux activityHistories pour la même activité et le même user` ce n'est pas un problème car c'est ce qu'on veut. Ssi l'utilisateur fait deux foiss l'activité, on veut deux historiques

2020-09-11 13:54 UTC, cmolle commented on src/helpers/translate.js
> +    activityHistoryCreated: 'L\'historique d\'activité à été créé.',
A ajouter en anglais aussi

2020-09-11 13:54 UTC, cmolle commented on src/helpers/activityHistories.js
> +};
Tu peux tout mettre sur une ligne 
`exports.addActivityHistory = async payload => ActivityHistory.create(payload);`

2020-09-11 13:54 UTC, cmolle commented on tests/integration/activityHistories.test.js
> +      { name: 'trainer', expectedCode: 403 },
C'est avec admin vendor qu'il fait les premiers tests du coup pas besoin si ?

2020-09-11 14:02 UTC, KennyCallegari commented on tests/integration/activityHistories.test.js
> +      { name: 'trainer', expectedCode: 403 },
C'est les tests du dessus non ? Vu que j'auth selon vendor_admin:
` authToken = await getToken('vendor_admin');`

2020-09-11 14:21 UTC, KennyCallegari commented on tests/integration/activityHistories.test.js
> +      { name: 'trainer', expectedCode: 403 },
Du coup j'enlève l'authentification vendor admin au dessus et je la test ici ? Comme ça je test avec le cas où s'est simplement une personne connectée

2020-09-11 15:52 UTC, cmolle commented on src/routes/preHandlers/activityHistories.js
> +  if (!activity || !user || !userIsInActivityCourse) throw Boom.notFound();
tu pourrais renvoyer notFound des le debut si il n'y a pas d'activity ou de user

2020-09-11 15:52 UTC, cmolle commented on tests/integration/activityHistories.test.js
> +    it('should return a 400 if no user in payload', async () => {
il faut gerer aussi les cas ou l'utilisateur ne suit pas la formation ou si l'activite ou l'utiliisateur n'existe pas

2020-09-11 15:52 UTC, cmolle commented on tests/integration/seed/activityHistoriesSeed.js
> +const activityHistoriesList = [
Je ne suis pas sure qu'il soit utile de creer une activityHistory dans ces seed

2020-09-11 15:52 UTC, cmolle commented on tests/integration/activityHistories.test.js
> +        payload: { user: activityHistoriesList[0].user, activity: activityHistoriesList[0].activity },
Je trouve ca un peu etrange de tester d'ajouter une activityHistory en utilisant des champs d'une activityHistory deja existante.

2020-09-11 15:52 UTC, cmolle commented on tests/unit/helpers/activityHistories.test.js
> +    sinon.assert.calledWithExactly(addActivityHistoryStub, { user: userId, activity: activityId });
Tu peux faire directement calledOnceWithExactly je crois

2020-09-11 15:59 UTC, sophiemoustard commented on src/helpers/translate.js
> +    activityHistoryCreated: 'L\'historique d\'activité à été créé.',
juste 'Historique d\'activité créé.',

2020-09-11 16:21 UTC, sophiemoustard requested changes

2020-09-11 16:21 UTC, sophiemoustard commented on src/routes/activityHistories.js
> +            date: Joi.date(),
on ne va pas envoyer la date par la route donc autant ne pas la mettre

2020-09-11 16:21 UTC, sophiemoustard commented on src/routes/index.js
> +    routes: { prefix: '/activityHistories' },
pas de majuscule non plus - format comme courseslots au desssus ;)

2020-09-11 16:21 UTC, sophiemoustard commented on src/routes/preHandlers/activityHistories.js
> +  const activityCourses = await Course.find({ subProgram: { _id: subProgram._id } });
ici tu peux faire 
```
const activity = await Activity.findOne({ _id: req.payload.activity })
    .populate({
      path: 'steps',
      select: '_id -activities',
      populate: { path: 'subProgram', select: '_id -steps' },
    })
    .lean();
```

Comme ça tu récupères directement l'activité avec les étapes et a l'intérieur les sous programmes qui vont bien

1. si `activity` n'est pas définie, tu renvoie une erreur
2. sinon, tu map sur `activity.steps.map(s => s.subProgram._id)` pour recuperer un tableau d'objectId de sous programme
⚠️ il peut y avoir plusieurs etapes pour une activité si ton actvité est reutilisée dans plusieurs etapes - danss ton code ci dessus, le `findOne` n;est pas correct
3. Tu récupères les formations associées : `const activityCourses = await Course.find({ subProgram: { _id: subProgram._id } }).lean();` comme tu le fais - en ajoutant un `lean` a la fin ce qui permet de transformer l'objet mongoosse que tu récupères en objet JS - bien mieux pour les perf car tu n'as pas toute sles méthodes associées

si besoin on s'appelle :)

2020-09-11 16:21 UTC, sophiemoustard commented on src/routes/preHandlers/activityHistories.js
> +  }
tu peux directement utiliser la methode js `some` qui s'applique sur un tableau est retourne true si au moins un des elements a l'interieur verifie la callback que tu lui passes.

`const userIsInActivityCourse = activityCourses.some(c => c.trainees.includes(req.payload.user))`

2020-09-11 16:21 UTC, sophiemoustard commented on src/routes/preHandlers/activityHistories.js
> +  const user = await User.findOne({ _id: req.payload.user });
ajoutes un lean apres le findOne - comme preciser au dessus pour les perf :)

2020-09-11 16:21 UTC, sophiemoustard commented on tests/integration/activityHistories.test.js
> +    const roles = [
tu pourrais tester aussi que pour quelqu'un sans role ca fonctionne bien

2020-09-11 16:21 UTC, sophiemoustard commented on tests/integration/activityHistories.test.js
> +      { name: 'vendor_admin', expectedCode: 200 },
et sorry pour mon message d'avant mais en fait le vendor_admin est le cas qu'on teste plus haut donc pas besoin de le mettre la

2020-09-14 07:15 UTC, sophiemoustard commented on tests/integration/activityHistories.test.js
> +      { name: 'trainer', expectedCode: 403 },
POur rester coherent avec le reste, il vaut mieux laisser le vendor admin en premier test sinon on va confondre

2020-09-14 16:15 UTC, KennyCallegari commented on tests/integration/activityHistories.test.js
> +    const roles = [
Je vois pas comment on test pour quelqu'un qui n'a pas de rôle

2020-09-14 16:25 UTC, KennyCallegari commented on src/routes/index.js
> +    plugin: require('./activityHistories'),
creditNote au dessus est en camelCase, je boyscout ça ?

2020-09-15 11:29 UTC, sophiemoustard requested changes

2020-09-15 11:29 UTC, sophiemoustard commented on src/routes/preHandlers/activityHistories.js
> +  }).lean();
le formatage c'est plutot 
```
  const coursesWithActivityAndFollowedByUser = await Course
   .find({ subProgram: { $in: activitySubPrograms }, trainees: req.payload.user })
   .lean();
```

2020-09-15 11:29 UTC, sophiemoustard commented on src/routes/preHandlers/activityHistories.js
> +  }).lean();
et en fait tu pourrais faire un countDocuments plutot qu'un find non ?

2020-09-15 11:29 UTC, sophiemoustard commented on tests/integration/activityHistories.test.js
> +  ];
tu peux les definir directement aux endroits concernés non ? 
en le mettant au dessus je trouve que ca enlève de la lisibilité aux tests

2020-09-15 13:39 UTC, sophiemoustard commented on src/routes/preHandlers/activityHistories.js
> +  }).lean();
up sur le formatage 
et le countDocuments ne necessite pass de lean apres
le lean transforme un objet mongoose en objet JS et le countDocuments te retourne un nombre donc les 2 ne vont pas ensemble

2020-09-15 14:11 UTC, sophiemoustard approved these changes

2020-09-15 14:14 UTC, cmolle commented on src/models/ActivityHistory.js
> +});
Je suis desolee de le voir que maintenant, mais habituellement on ajoute les timestamps.  (createdAt et updatedAt). Est-ce que c'est utile ici, ou ca fait un peu doublon avec date ? (et du coup on prefere date a createdAt ?)

2020-09-15 14:16 UTC, sophiemoustard commented on src/models/ActivityHistory.js
> +});
oh oui bien vu ! c'est mieux de les mettre

2020-09-15 14:26 UTC, cmolle approved these changes

2020-09-15 14:44 UTC, merged