COM-1527 - Add areCardsValid virtual
sophiemoustard/alenvi-api pull request #1063
Opened 2020-10-07 11:33 UTC by KennyCallegari

- [x] Mon code est testé unitairement
- [x] Mon code est testé avec des tests d'intégration

- Périmetre interface : VENDOR

- Périmetre roles : admin / rof

- Cas d'usage : 
Ajout d'un virtual areCardsValid uniquement si les cartes sont populées et qui est true si toutes les cartes ont isValid === true.

2020-10-07 13:12 UTC, sophiemoustard commented on src/helpers/programs.js
> +    .lean({ autopopulate: true, virtuals: true });
tu as besoin de autopopulate ?

2020-10-07 13:29 UTC, KennyCallegari commented on src/helpers/programs.js
> +    .lean({ autopopulate: true, virtuals: true });
Non effectivement, c'était un test oublié

2020-10-07 13:51 UTC, KennyCallegari commented on src/helpers/programs.js
> +    .lean({ autopopulate: true, virtuals: true });
done

2020-10-07 16:05 UTC, sophiemoustard approved these changes

2020-10-08 09:12 UTC, cmolle reviewed
Est-ce qu'il ne faudrait pas ajouter un test pour verifier que si les cartes sont valides ca renvoie bien true ?

2020-10-08 09:39 UTC, felix-commits approved these changes

2020-10-08 12:08 UTC, cmolle commented on tests/unit/helpers/programs.test.js
> +            populate: 'cards' } } })
On met plutot comme ca : 
```
.withExactArgs({
    path: 'subPrograms',
    populate: { path: 'steps', populate: { path: 'activities', populate: 'cards' } },
})
```

2020-10-08 12:08 UTC, cmolle commented on tests/integration/courses.test.js
> +            areCardsValid: false,
C'est sur cette route ou sur celle de 'GET activities/id' ou on a besoin de areCardsValid ? Je pense qu'il vaut mieux faire le test true/false sur la route qui en a besoin

2020-10-08 16:15 UTC, cmolle commented on tests/integration/programs.test.js
> +            }],
sur une ligne

2020-10-08 16:15 UTC, cmolle commented on tests/integration/courses.test.js
> +            cards: expect.arrayContaining([{ _id: expect.any(ObjectID), template: 'title_text' }]),
Pourquoi l'avoir supprime ?

2020-10-08 16:18 UTC, KennyCallegari commented on tests/integration/courses.test.js
> +            cards: expect.arrayContaining([{ _id: expect.any(ObjectID), template: 'title_text' }]),
GET /courses/{_id}/user' est utilisé uniquement sur l'app mobile, ce n'est pas la route pour ProfileContent

2020-10-08 16:40 UTC, KennyCallegari commented on tests/integration/programs.test.js
> +            }],
done

2020-10-08 16:41 UTC, KennyCallegari commented on tests/integration/courses.test.js
> +            cards: expect.arrayContaining([{ _id: expect.any(ObjectID), template: 'title_text' }]),
Confusion de ma part. Ce n'est pas la route appelée par ProfileContent mais il faut quand même changer les tests. ça devrait être bon maintenant

2020-10-09 06:43 UTC, sophiemoustard requested changes

2020-10-09 06:43 UTC, sophiemoustard commented on tests/unit/helpers/programs.test.js
>        .returns(program);
dans ton objet program que tu definis plus haut, il faut que tu mettess `steps` puis `activities` puis `cards` dedanss pour que ca fonctionne

tu peux aussi verifier du coup que meme si ta requete en base te renvoie un tableau d'objet pour `cards`, la methode a la fin te retourne juste un tableau d'id

2020-10-09 08:10 UTC, sophiemoustard approved these changes

2020-10-09 08:10 UTC, merged