Com 1525
sophiemoustard/alenvi-api pull request #1064
Opened 2020-10-07 15:10 UTC by cmolle

- [x] Mon code est testé unitairement
- [x] Mon code est testé avec des tests d'intégration

- Périmetre interface : mobile

- Périmetre roles : utilisateur connecté

- Cas d'usage : 
Creation de la page Explorer + refacto ProgramCell (anciennement CourseCell)

Point d'attention: 
- pour que la redirection vers courseprofile fonctionne dans le ticket COM-1526 il faudra faire une refacto pour recuperer la course d'apres le sous programme.

2020-10-08 07:30 UTC, sophiemoustard commented on src/routes/programs.js
> +        auth: { mode: 'required' },
peux tu ajouter une validation sur `query` stp ?

et est ce qu'on a un cas ou on a en meme temps `format` et en meme temps une autre `query` ? si non tu peux encore simplifier le helper en enlevant le `omit`

2020-10-08 07:30 UTC, sophiemoustard commented on src/helpers/programs.js
> +exports.list = async (query) => {
je me dis que c'est peut être plus lisible comme ca qu'en penses tu ?

```
exports.list = async (query) => {
  if (query.format) {
    const courses = await Course.find({ format: query.format }).lean();
    const subPrograms = courses.map(course => course.subProgram);

    return Program.find({ ...omit(query, 'format'), subPrograms: { $in: subPrograms } })
      .populate({ path: 'subPrograms', select: 'name', match: { _id: { $in: subPrograms } } })
      .lean();
  }

  return Program.find(query).populate({ path: 'subPrograms', select: 'name' }).lean();
};
```

2020-10-09 08:04 UTC, KennyCallegari approved these changes

2020-10-09 08:04 UTC, KennyCallegari commented on tests/integration/programs.test.js
> +      expect(response.result.data.programs.length).toEqual(1);
On a un moyen de vérifier si le program est rattaché à une course e_learning ?

2020-10-09 08:28 UTC, KennyCallegari approved these changes

2020-10-09 08:55 UTC, sophiemoustard requested changes

2020-10-09 08:55 UTC, sophiemoustard commented on src/helpers/programs.js
> +exports.list = async () => Program.find({})
tu peux laisser `query`
ou alors l'enlever aussi coté controller

2020-10-09 09:10 UTC, sophiemoustard approved these changes

2020-10-09 09:31 UTC, merged