COM-1528 - Add areActivitiesValid virtual
sophiemoustard/alenvi-api pull request #1065
Opened 2020-10-07 15:34 UTC by KennyCallegari

- [x] Mon code est testé unitairement
- [x] Mon code est testé avec des tests d'intégration

- Périmetre interface : VENDOR

- Périmetre roles : admin / rof

- Cas d'usage : 
Ajout champ virtuel areActivitiesValid à step, qui est à true si step est populé et que ses activités sont toutes valides

2020-10-08 09:13 UTC, cmolle reviewed
Est-ce qu'il ne faudrait pas ajouter des tests pour verifier que le virtuals fonctionne bien ?

2020-10-08 10:10 UTC, felix-commits approved these changes
sur jira ya écrit qu'il faut populate _areActivitiesValid_ dans _ProgramHelper.getProgram_ est-ce que c'est toujours nécessaire?

2020-10-09 07:00 UTC, cmolle approved these changes

2020-10-09 08:26 UTC, sophiemoustard requested changes
je pense qu'il faut que tu rebases

peux tu aussi mieux formater ce bout de code dans le tests unitaire `program.test.js` apresss ton rebase - je ne t'ai pas fait le retour pour fusionner la PR
```
const program = {
  _id: new ObjectID(),
  subPrograms: [{
    _id: new ObjectID(),
    steps: [{
      _id: new ObjectID(),
       activities: [{_id: new ObjectID(), cards: [{ _id: new ObjectID() }] }]
    }]
  }]
};
```

2020-10-09 08:26 UTC, sophiemoustard commented on src/models/Step.js
> +    this.activities[0].type) {
sur une ligne

2020-10-09 08:47 UTC, sophiemoustard commented on tests/integration/courses.test.js
> +          areActivitiesValid: false,
en a t on besoin ?

2020-10-09 09:04 UTC, KennyCallegari commented on tests/integration/courses.test.js
> +          areActivitiesValid: false,
juste en l'enlevant j'ai une erreur, tu voudrais le supprimer ?

2020-10-09 10:04 UTC, sophiemoustard approved these changes

2020-10-09 10:32 UTC, merged