Com 1587 2
sophiemoustard/alenvi-api pull request #1084
Opened 2020-10-21 12:50 UTC by cmolle

- [x] Mon code est testé unitairement
- [x] Mon code est testé avec des tests d'intégration

- Périmetre interface : client

- Périmetre roles : admin/coach

- Cas d'usage : Je ne peux pas creer ou editer une souscription avec un service archivé (cf point 2 du ticket)
J'ai fait une mini refacto sur la suppressoin de souscription en passant une partie du helper dans le prehandler.

2020-10-21 12:58 UTC, sophiemoustard requested changes

2020-10-21 12:58 UTC, sophiemoustard commented on src/controllers/serviceController.js
> +    const services = await ServiceHelper.list(get(req, 'auth.credentials.company._id', null), req.query);
souvent on passe `credentials` du controller a l'helper et ensuite l'helper gere la recuperation de l'id de la structure

2020-10-21 12:58 UTC, sophiemoustard commented on src/routes/preHandlers/customers.js
> +  try {
on ne met pas de try/catch dans les prehandler si ?

2020-10-21 13:12 UTC, cmolle commented on src/routes/preHandlers/customers.js
> +  try {
Je crois qu'on en a besoin lorsqu'on appelle un autre prehandler (ca m'arretait completement mes tests d'integration a la premiere erreur sans ca.

2020-10-22 05:56 UTC, cmolle commented on src/controllers/serviceController.js
> +    const services = await ServiceHelper.list(get(req, 'auth.credentials.company._id', null), req.query);
Done !

2020-10-22 07:25 UTC, sophiemoustard commented on src/routes/preHandlers/customers.js
> +  try {
il faut peut etre mettre `return` a la place de `throw`

2020-10-22 07:25 UTC, sophiemoustard commented on src/routes/preHandlers/customers.js
> +  try {
car si tu throw en effet il faut la catcher quelque part 🤔

2020-10-22 10:11 UTC, cmolle commented on src/routes/preHandlers/customers.js
> +  try {
J'ai l'impression que le return Boom ou throw Boom fait la meme chose :/

2020-10-22 13:14 UTC, sophiemoustard approved these changes

2020-10-22 13:14 UTC, merged