Com 1615
sophiemoustard/alenvi-api pull request #1096
Opened 2020-10-27 13:26 UTC by cmolle

- [x] Mon code est testé unitairement
- [x] Mon code est testé avec des tests d'intégration

- Périmetre interface : mobile

- Périmetre roles : tous

- Cas d'usage : Sur la page a propos d'une formation, j'ai un bouton qui permet de s'inscrire a une formation ou de la continuer si je suis deja inscrit. 

Ce qui n'est pas fait dans cette pr: 
- Je n'arrive pas directement sur l'activité quand j'appuie sur commencer
- La page 'A propos' ne se rafraîchit pas . Je ne savais pas trop comment le gerer (je vois trois solutions):
       Refacto pour ne recevoir que l'_id du program dans a propos et faire un appel avec tout ce dont on a besoin
       Faire un appel pour raffrachir le program quand on s'inscrit (necessite une nouvelle route).
       Renvoyer le program avec les champs voulu dans l'appel d'inscription a une formation eLearning

Dites moi ce que vous en pensez (n'hesitez pas si vous avez d'autres idees :) ) Je propose de faire ca dans une deuxieme pr.

2020-10-27 15:50 UTC, sophiemoustard requested changes

2020-10-27 15:50 UTC, sophiemoustard commented on src/routes/courses.js
> +      handler: addELearningTrainee,
que penses tu de registerToCourse comme nom ?

2020-10-27 15:50 UTC, sophiemoustard commented on src/routes/courses.js
> +      path: '/{_id}/e-learning-trainees',
dans la suite de ma porposition pour le nom du controller : path: '/{_id}/register',

2020-10-27 15:50 UTC, sophiemoustard commented on src/helpers/programs.js
> +        populate: { path: 'trainees', select: '_id', match: { _id: userId }, options: { gettingOwnInfo: true } },
je ne comprends pas ton `gettingOwnInfo`

2020-10-27 15:50 UTC, sophiemoustard commented on src/helpers/courses.js
> +  Course.updateOne({ _id: courseId }, { $addToSet: { trainees: credentials._id } }, { new: true });
pas besoin du `{ new: true }` c'est quand tu fais un `findOneAndUpdate` pour recuperer l'entité mise a jour et non celle precedant le `$addToSet`

2020-10-27 15:50 UTC, sophiemoustard commented on src/helpers/programs.js
> +        populate: { path: 'trainees', select: '_id', match: { _id: userId }, options: { gettingOwnInfo: true } },
et pourquoi a tu besoin de populer les participants ?

2020-10-27 16:17 UTC, cmolle commented on src/routes/courses.js
> +      handler: addELearningTrainee,
registerToELearningCourse ?

2020-10-27 16:19 UTC, cmolle commented on src/helpers/programs.js
> +        populate: { path: 'trainees', select: '_id', match: { _id: userId }, options: { gettingOwnInfo: true } },
J'en ai besoin pour ne pas recuperer tous les stagiaires (je suppose qu'on ne veut pas que tout le monde y ait acces. Mais j'ai quand meme besoin des stagiaires pour verifier si l'utilisateur y est inscrit. 

Sinon je peux faire un filter apres sur les stagiaires mais comme y avait aps mal d'imbrication d'objet ca me paraissait moins lisible.

2020-10-27 16:20 UTC, cmolle commented on src/helpers/courses.js
> +  Course.updateOne({ _id: courseId }, { $addToSet: { trainees: credentials._id } }, { new: true });
Ha oui, merci ! :)

2020-10-28 08:10 UTC, sophiemoustard commented on src/helpers/programs.js
> +        populate: { path: 'trainees', select: '_id', match: { _id: userId }, options: { gettingOwnInfo: true } },
pour vérifier que la personne est bien inscrite, tu as juste besoin de son _id ? ce que tu as deja sans populer. et tant qu'on ne popule pas les infos des participants je ne pense pass que ce soit genant d'avoir un tableau d'_id ...

2020-10-28 08:11 UTC, sophiemoustard commented on src/routes/courses.js
> +      handler: addELearningTrainee,
on peut partir la dessus

2020-10-28 08:33 UTC, cmolle commented on src/helpers/programs.js
> +        populate: { path: 'trainees', select: '_id', match: { _id: userId }, options: { gettingOwnInfo: true } },
Oui tu as raison :)

2020-10-29 08:25 UTC, sophiemoustard approved these changes

2020-10-29 09:22 UTC, ulysseferreira approved these changes

2020-10-29 11:03 UTC, merged