COM-1611
sophiemoustard/alenvi-api pull request #1097
Opened 2020-10-28 14:27 UTC by KennyCallegari

- [x] Mon code est testé unitairement
- [x] Mon code est testé avec des tests d'intégration

- Périmetre interface : VENDOR

- Périmetre roles : ROF / Admin / Coach

- Cas d'usage : 
Création d'une route pour récupérer la liste des courseHistories associés à une course.

2020-10-29 19:54 UTC, sophiemoustard commented on tests/integration/courseHistories.test.js
> +describe('COURSE HISTORIES ROUTES - GET /coursehistories/', () => {
tu as mis un / en trop

2020-10-29 19:54 UTC, sophiemoustard commented on tests/integration/courseHistories.test.js
> +    it('should return all 400 if no query', async () => {
ton titre est bizarre

2020-10-29 19:54 UTC, sophiemoustard commented on tests/unit/helpers/courseHistories.test.js
> +const payload = {
pourquoi tu as sorti  ce payload du describe ?
il vaut mieux definir pour chaque test les données qui vont bien

2020-10-29 19:54 UTC, sophiemoustard commented on tests/integration/courseHistories.test.js
> +      { name: 'coach', expectedCode: 200 },
ce test me fait penser qu'il manque le prehandler
les droits c'est : 
- ROF / admin vendeur peuvent tout voir
- Formateur ne peut voir que les historiques de ses formations
- Coach / admin client : que les formations INTRA de leur structure

si tu veux on peux faire ca dans la PR de demain
si tu preferes ca, ajoute un commentaire dans le ticket

2020-10-30 08:27 UTC, KennyCallegari commented on tests/integration/courseHistories.test.js
> +      { name: 'coach', expectedCode: 200 },
ah oui bien vu !

2020-10-30 09:05 UTC, KennyCallegari commented on tests/integration/courseHistories.test.js
> +describe('COURSE HISTORIES ROUTES - GET /coursehistories/', () => {
done

2020-10-30 09:05 UTC, KennyCallegari commented on tests/integration/courseHistories.test.js
> +    it('should return all 400 if no query', async () => {
done

2020-10-30 09:07 UTC, KennyCallegari commented on tests/unit/helpers/courseHistories.test.js
> +const payload = {
ça marche, je l'avais sorti parce que je l'utilise pour les deux tests mais effectivement je vois le problème que ça pose si on veut ajouter d'autres tests.

2020-10-30 11:02 UTC, felix-commits approved these changes

2020-10-30 16:00 UTC, KennyCallegari commented on src/routes/preHandlers/courseHistories.js
> +    if (course.type !== INTRA || !course.trainees.map(id => id.toHexString()).includes(credentials._id)) {
Ici j'ai changé par rapport à ce qu'on avait fait :
on testait si l'entreprise de l'user était l'entreprise de la formation mais on ne testait pas si l'user était inscrit dans la formation

2020-10-30 16:00 UTC, KennyCallegari commented on src/routes/preHandlers/courseHistories.js
> +    if (course.type !== INTRA || !course.trainees.map(id => id.toHexString()).includes(credentials._id)) {
@sophiemoustard

2020-10-30 16:30 UTC, sophiemoustard requested changes

2020-10-30 16:30 UTC, sophiemoustard commented on tests/integration/courseHistories.test.js
> +    it('should return empty array if wrong query', async () => { // PAS SUR DE CE TEST
ce test n'est pas utile

2020-10-30 16:30 UTC, sophiemoustard commented on tests/integration/courseHistories.test.js
> +    it('should return 200 as user is trainer and course has user as trainer', async () => {
que penses tu de `should return 200 as user is course trainer ?`

2020-10-30 16:30 UTC, sophiemoustard commented on tests/integration/seed/courseHistoriesSeed.js
> +const companyId = authCompany._id;
cette variable ne sert pas car utilisé une seule fois - tu peux mettre directement `authCompany` dans le  courseList

2020-10-30 16:43 UTC, sophiemoustard approved these changes

2020-10-30 22:45 UTC, sophiemoustard commented on src/routes/preHandlers/courseHistories.js
> +    if (course.type !== INTRA || !course.trainees.map(id => id.toHexString()).includes(credentials._id)) {
vu ensemble, ce qu'on avait fait a la base etait juste

2020-10-30 22:45 UTC, merged