Com 1611 infinite scroll
sophiemoustard/alenvi-api pull request #1101
Opened 2020-10-30 18:16 UTC by KennyCallegari

- [ ] Mon code est testé unitairement
- [ ] Mon code est testé avec des tests d'intégration

- Périmetre interface : vendor / client

- Périmetre roles : coach / rof / admin

- Cas d'usage : Ajout du infinite scroll. Ajout sur la PR : https://github.com/sophiemoustard/alenvi-api/pull/1097

- Pas présent sur cette PR :
tests
update history live

2020-11-02 11:52 UTC, KennyCallegari commented on tests/unit/helpers/courseHistories.test.js
> +    const query = { course: returnedList[0].course };
Mes tests passaient malgré cette erreur, je me demande s'il ne faut pas que je les affine un peu plus pour ne pas laisser passer ce genre d'erreur

2020-11-02 12:43 UTC, sophiemoustard commented on tests/unit/helpers/courseHistories.test.js
> +    const query = { course: returnedList[0].course };
en fait puisque tu mock l'appel a la bdd, la requête n'est pas faite
ce `expect(result).toMatchObject(returnedList);` verifie juste que ce que renvoie `CourseHistoriesHelper.list` c'est la meme chose que `CourseHistoryMock`, quelque soit le contenu finalement

2020-11-02 12:46 UTC, sophiemoustard requested changes

2020-11-02 12:46 UTC, sophiemoustard commented on tests/integration/courseHistories.test.js
> +        ch => ch.course === coursesList[2]._id && ch.createdAt < '2020-06-25T06:00:00'
utilise moment pour comparer les date plutot que <

2020-11-02 12:46 UTC, sophiemoustard commented on src/helpers/courseHistories.js
> +    .limit(8)
on avait mis 8 pour tester plus facielement mais c'est plutot 20

2020-11-02 13:22 UTC, KennyCallegari commented on tests/integration/courseHistories.test.js
> +        ch => ch.course === coursesList[2]._id && ch.createdAt < '2020-06-25T06:00:00'
done

2020-11-02 13:22 UTC, KennyCallegari commented on src/helpers/courseHistories.js
> +    .limit(8)
done

2020-11-02 13:42 UTC, sophiemoustard requested changes

2020-11-02 13:42 UTC, sophiemoustard commented on tests/integration/courseHistories.test.js
> +        ch => ch.course === coursesList[2]._id && moment(ch.createdAt) < moment('2020-06-25T06:00:00')
utilise isBefore de moment

2020-11-02 14:15 UTC, sophiemoustard approved these changes

2020-11-03 11:28 UTC, sophiemoustard approved these changes

2020-11-03 11:28 UTC, merged