COM-1612 - Create coursehistory on slot deletion
sophiemoustard/alenvi-api pull request #1104
Opened 2020-11-04 15:03 UTC by KennyCallegari

- [ ] Mon code est testé unitairement
- [ ] Mon code est testé avec des tests d'intégration

- Périmetre interface : VENDOR

- Périmetre roles : ROF / Admin / Coach

- Cas d'usage : 
Lorsque je supprime un créneau, il apparait dans l'historique des modifications de créneau.

2020-11-04 18:53 UTC, sophiemoustard requested changes

2020-11-04 18:53 UTC, sophiemoustard commented on src/helpers/courseSlots.js
> +exports.removeCourseSlot = async (courseSlotId, user) => {
dans ton fichier route sur ta route DELETE tu as `pre: [{ method: getCourseSlot, assign: 'courseSlot' },` ce assign ajoute un dans l'objet `req` recu dans ton controller un champ `pre.courseSlot` qui contient le creneau concerné 
du coup plutot que de passer l'_id, tu peux passer `req.pre.courSlot` et ne plus faire ton appel `findById` ici et tu n'as pas besoin de gerer non plus le cas de l'existence de ce courseSlot car comme il a passé le preHandler, il existe forcement

2020-11-04 18:53 UTC, sophiemoustard commented on src/helpers/courseHistories.js
> +
je trouve cette maniere de faire moins lisible que de faire 
`exports.createHistoryOnSlotCreation = (payload, userId) => exports.createHistory(payload, userId, SLOT_CREATION);`

2020-11-05 15:11 UTC, KennyCallegari commented on src/helpers/courseSlots.js
> +  };
done

2020-11-05 15:11 UTC, KennyCallegari commented on src/helpers/courseSlots.js
> +  courseHistoriesHelper.createHistoryOnSlotDeletion(payload, user._id);
done

2020-11-05 15:15 UTC, KennyCallegari commented on src/helpers/courseSlots.js
> +  return CourseSlot.deleteOne({ _id: courseSlotId });
done

2020-11-05 15:18 UTC, KennyCallegari commented on tests/integration/courseSlots.test.js
> +      const courseHistory = await CourseHistory.findOne({
bien vu !
done

2020-11-05 15:19 UTC, KennyCallegari commented on tests/unit/helpers/courseHistories.test.js
> +        },
done

2020-11-05 15:21 UTC, KennyCallegari commented on src/helpers/courseSlots.js
> +exports.removeCourseSlot = async (courseSlotId, user) => {
oh nice ! done

2020-11-05 15:46 UTC, KennyCallegari commented on src/helpers/courseHistories.js
> +
done

2020-11-05 16:22 UTC, KennyCallegari commented on tests/integration/courseSlots.test.js
> -      const courseHistory = await CourseHistory.findOne({
Ces tests sont inutiles en fait, la courseHistory n'est pas créée. Et je n'ai pas réussi à faire en sorte qu'elle le soit.
On pourra se faire un petit point là dessus @sophiemoustard ?

2020-11-05 16:30 UTC, sophiemoustard commented on src/controllers/courseSlotController.js
> +    await CourseSlotsHelper.removeCourseSlot(req.params._id, req.auth.credentials, req.pre.courseSlot);
tu peux passer uniquemenent `req.pre.courseSlot` et `req.pre.courseSlot` (danss cette ordre) car l'id du sslot est inclu dans `req.pre.courseSlot`

2020-11-05 16:30 UTC, sophiemoustard commented on src/helpers/courseSlots.js
> +    courseHistoriesHelper.createHistoryOnSlotDeletion(payload, user._id),
avec un majuscule a CourseHistoriesHelper

2020-11-05 16:31 UTC, sophiemoustard commented on tests/unit/helpers/courseSlots.test.js
> +  let createCourseHistory;
createHistoryOnSlotDeletion plutot car tu as une methode qui s'appelle createCourseHistory dans CourseHistoriesHelper donc ca porte a confusion

2020-11-05 16:33 UTC, sophiemoustard commented on tests/integration/courseSlots.test.js
> -      const courseHistory = await CourseHistory.findOne({
je ne comprends pas ton point - c'est un probleme si le courseHistory n'est pas crée car cette route doit justement en creer un... 🤔 et ce test passait avant..

2020-11-05 16:45 UTC, KennyCallegari commented on tests/integration/courseSlots.test.js
> -      const courseHistory = await CourseHistory.findOne({
le test passait oui, mais `courseHistory` était null

2020-11-05 16:46 UTC, KennyCallegari commented on src/controllers/courseSlotController.js
> +    await CourseSlotsHelper.removeCourseSlot(req.params._id, req.auth.credentials, req.pre.courseSlot);
done

2020-11-05 16:46 UTC, KennyCallegari commented on src/helpers/courseSlots.js
> +    courseHistoriesHelper.createHistoryOnSlotDeletion(payload, user._id),
done

2020-11-05 16:49 UTC, KennyCallegari commented on tests/unit/helpers/courseSlots.test.js
> +  let createCourseHistory;
done

2020-11-05 19:41 UTC, sophiemoustard approved these changes

2020-11-06 08:35 UTC, sophiemoustard approved these changes

2020-11-06 08:36 UTC, merged