COM-1619 updated model and helper
sophiemoustard/alenvi-api pull request #1111
Opened 2020-11-09 12:19 UTC by felix-commits

- [ ] Mon code est testé unitairement
- [ ] Mon code est testé avec des tests d'intégration

- Périmetre interface : vendeur

- Périmetre roles : formateur

- Cas d'usage : je sais si un créneau a changé d'horaire

2020-11-09 13:20 UTC, sophiemoustard requested changes

2020-11-09 14:31 UTC, felix-commits commented on src/helpers/courseHistories.js
> +  await exports.createHistory(slotFromDb.courseId, userId, SLOT_EDITION, actionPayload);
merci pour cette refacto !

2020-11-09 14:31 UTC, felix-commits commented on src/helpers/courseHistories.js
> +  CourseHistory.create({ course, createdBy, action, ...payload });
super cool d'avoir une fonction universelle d'une ligne !

2020-11-09 14:31 UTC, felix-commits commented on tests/unit/helpers/courseHistories.test.js
> +    await CourseHistoriesHelper.createHistory(course, user, 'action', { trainee: 'bonjour' });
faut il rajouter tous les types de payload possibles?

2020-11-09 14:32 UTC, felix-commits commented on src/helpers/courseHistories.js
> +  const isHourUpdated = moment(slotFromDb.startDate).isSame(payload.startDate, 'm');
en effet merci davoir corrigé

2020-11-09 14:45 UTC, felix-commits commented on src/models/CourseHistory.js
> +      type: mongoose.Schema({ from: { type: Date }, to: { type: Date } }),
avec `mongoose.Schema` on attend un objet qui contient deux dates, c'est bien ça? sans le `schema` j'aurais pu avoir une arborescence fausse mais bien deux date il n’aurait pas détecté l'erreur ?

2020-11-09 16:07 UTC, sophiemoustard commented on src/models/CourseHistory.js
> +      type: mongoose.Schema({ from: { type: Date }, to: { type: Date } }),
j'ai ajouté `type: mongoose.Schema...` pour pouvoir specifier le `required` egalement

2020-11-09 16:08 UTC, sophiemoustard commented on tests/unit/helpers/courseHistories.test.js
> +    await CourseHistoriesHelper.createHistory(course, user, 'action', { trainee: 'bonjour' });
non la on veut juste verifier que la methode formate bien le bon payoload - en fait `create` est agnostique de ce que tu lui passes en 4eme argument - on verifie qu'il fait bien passe plat

2020-11-09 16:10 UTC, KennyCallegari approved these changes

2020-11-09 16:11 UTC, felix-commits commented on src/models/CourseHistory.js
> +      type: mongoose.Schema({ from: { type: Date }, to: { type: Date } }),
daccord merci

2020-11-10 07:39 UTC, sophiemoustard approved these changes

2020-11-10 07:39 UTC, merged