Com 1633
sophiemoustard/alenvi-api pull request #1129
Opened 2020-11-16 18:45 UTC by KennyCallegari

- [ ] Mon code est testé unitairement
- [ ] Mon code est testé avec des tests d'intégration

- Périmetre interface : vendor

- Périmetre roles : rof / admin

- Cas d'usage :
Lorsque je clique sur une formation eLearning dans la liste, je vois la page d'info sur cette formation contenant la liste des apprenants ainsi que leur progression.

PAS ENCORE FAIT :
- Les tests + fix des tests
- Regrouper les appels de getCourse en un seul cas (pas de distinction ELearning). -> Pas réussi

2020-11-16 19:23 UTC, sophiemoustard requested changes

2020-11-16 19:23 UTC, sophiemoustard commented on src/helpers/courses.js
> +  return Course.findById(course._id)
pourquoi ce changement ?

2020-11-16 19:23 UTC, sophiemoustard commented on src/helpers/courses.js
> +  }
en fait ici il ne faut pas que tu passes pas cette route depuis le front mais pas /courses/_id/followup puisque c'est les informations que tu veux

2020-11-16 19:23 UTC, sophiemoustard commented on src/helpers/courses.js
> +    .populate({ path: 'trainees', select: 'identity.firstname identity.lastname' })
il manque le populate sur les slots pour que ca fonctionne coté BLENDED tant qu'a faire

2020-11-16 19:23 UTC, sophiemoustard commented on src/helpers/courses.js
> +      { ...t, followUp: exports.getTraineeProgress(t._id, course.subProgram.steps) })),
du coup ici tu passes aussi les slots

2020-11-16 19:23 UTC, sophiemoustard commented on src/helpers/courses.js
> +exports.getTraineeProgress = (traineeId, steps, slots = null) => steps.map((s) => {
tu n'as pas besoin du = null pour les slots si tu les populates dans `getCourseFollowUp`

2020-11-16 19:23 UTC, sophiemoustard commented on src/routes/courses.js
> +        pre: [{ method: getCourse, assign: 'course' }],
tu peux ajouter ce prehandler sur la route `'/{_id}/follow-up'` et `/{_id}/public-infos`

2020-11-17 10:38 UTC, KennyCallegari commented on src/routes/courses.js
> +        pre: [{ method: getCourse, assign: 'course' }],
Je le laisse sur getCourse ?

2020-11-17 10:38 UTC, KennyCallegari commented on src/helpers/courses.js
> +      { ...t, followUp: exports.getTraineeProgress(t._id, course.subProgram.steps) })),
done

2020-11-17 10:38 UTC, KennyCallegari commented on src/helpers/courses.js
> +exports.getTraineeProgress = (traineeId, steps, slots = null) => steps.map((s) => {
done

2020-11-17 10:38 UTC, KennyCallegari commented on src/helpers/courses.js
> +    .populate({ path: 'trainees', select: 'identity.firstname identity.lastname' })
done

2020-11-17 10:38 UTC, KennyCallegari commented on src/helpers/courses.js
> +  return Course.findById(course._id)
oubli de ma part

2020-11-17 10:38 UTC, KennyCallegari commented on src/helpers/courses.js
> +  }
done

2020-11-17 10:38 UTC, KennyCallegari commented on src/routes/courses.js
> +        pre: [{ method: getCourse, assign: 'course' }],
done

2020-11-17 18:59 UTC, sophiemoustard approved these changes

2020-11-17 19:01 UTC, merged