Com 1625 - WIP
sophiemoustard/alenvi-api pull request #1132
Opened 2020-11-17 17:01 UTC by KennyCallegari

WIP

2020-11-19 16:31 UTC, sophiemoustard commented on src/helpers/historyExport.js
> +    const absenceisOnOneMonth = moment(event.startDate).isSame(event.endDate, 'month');
typo absence*I*sOnOneMonth

2020-11-19 16:33 UTC, KennyCallegari commented on src/helpers/historyExport.js
> +    const absenceisOnOneMonth = moment(event.startDate).isSame(event.endDate, 'month');
done

2020-11-19 16:50 UTC, sophiemoustard requested changes

2020-11-19 16:50 UTC, sophiemoustard commented on tests/unit/helpers/draftPay.test.js
>    let getMatchingVersion;
a enlever ce n'est pas appeler dans la methode que tu testes

2020-11-19 16:50 UTC, sophiemoustard commented on tests/unit/helpers/draftPay.test.js
> +describe('getHoursFromDailyAbsence', () => {
a mettre avant le describe de getPayFromAbsences pour garder le meme ordre que celui du helper - ca aide a retrouver plus facilement

2020-11-19 16:50 UTC, sophiemoustard commented on tests/unit/helpers/draftPay.test.js
> +    sinon.assert.calledWithExactly(getHoursFromDailyAbsence, absences[0], contract, query);
called**Once**WithExactly

2020-11-19 16:50 UTC, sophiemoustard commented on tests/unit/helpers/draftPay.test.js
> +    sinon.assert.called(getHoursFromDailyAbsence);
ici tu peux faire deux assertions pour preciser ton test
```
sinon.assert.calledWithExactly(getHoursFromDailyAbsence.getCall(0), ...);
sinon.assert.calledWithExactly(getHoursFromDailyAbsence.getCall(1), ...);
```

2020-11-19 16:50 UTC, sophiemoustard commented on tests/unit/helpers/historyExport.test.js
> +        versions: [{ weeklyHours: 12 }],
pour que tes tests ait du sens, il vaut mieux prendre des données plausibles donc ic des contrats qui s'enchainent mais ne se chevauchent pas - date de debut du 2 eme contrat = date de fin du premier contrat + 1 jour

2020-11-19 16:50 UTC, sophiemoustard commented on tests/unit/helpers/historyExport.test.js
> +    sinon.assert.called(getHoursFromDailyAbsence);
precise ton assert avec calledWithExactly ou calledOnceWithExactly selon les cas - idem pour les autres tests

2020-11-19 16:50 UTC, sophiemoustard commented on tests/unit/helpers/historyExport.test.js
> +        versions: [{ weeklyHours: 12 }],
idem

2020-11-19 16:50 UTC, sophiemoustard commented on tests/unit/helpers/historyExport.test.js
> +    const exportArray = await ExportHelper.getAbsenceHours(absence, contracts);
exportArray ?

2020-11-19 16:50 UTC, sophiemoustard commented on tests/unit/helpers/historyExport.test.js
> +    const exportArray = await ExportHelper.getAbsenceHours(absence, contracts);
idem pour les suivants

2020-11-19 16:50 UTC, sophiemoustard commented on tests/unit/helpers/historyExport.test.js
> +  const events = [
definis chaque evenement dans le test plutot

2020-11-19 16:50 UTC, sophiemoustard commented on tests/unit/helpers/historyExport.test.js
> +  it('should return an array with the header and 1 rows for event on 2 months with (endDate + 2 months) < startDate', async () => {
je ne comprends pas le cas que tu veux tester

2020-11-19 16:50 UTC, sophiemoustard commented on tests/unit/helpers/historyExport.test.js
> +  });
comme les tests d'integration teste le contenu des fichiers, ici tu pourrais stuber la methode car la globalité de la fonctionnalité est validée par l'integration

2020-11-20 10:35 UTC, KennyCallegari commented on tests/unit/helpers/historyExport.test.js
> +  });
done

2020-11-20 10:57 UTC, KennyCallegari commented on tests/unit/helpers/historyExport.test.js
> +  it('should return an array with the header and 1 rows for event on 2 months with (endDate + 2 months) < startDate', async () => {
Le dernier 'if' de exportAbsencesHistory, qui vient palier le soucis qui se pose si le jour de la endDate est avant le jour de la startDate.

2020-11-20 10:59 UTC, KennyCallegari commented on tests/unit/helpers/draftPay.test.js
>    let getMatchingVersion;
done

2020-11-20 11:00 UTC, KennyCallegari commented on tests/unit/helpers/draftPay.test.js
> +describe('getHoursFromDailyAbsence', () => {
done

2020-11-20 15:01 UTC, KennyCallegari commented on tests/unit/helpers/draftPay.test.js
> +    sinon.assert.calledWithExactly(getHoursFromDailyAbsence, absences[0], contract, query);
done

2020-11-20 15:02 UTC, KennyCallegari commented on tests/unit/helpers/historyExport.test.js
> +    sinon.assert.called(getHoursFromDailyAbsence);
done

2020-11-20 15:02 UTC, KennyCallegari commented on tests/unit/helpers/historyExport.test.js
> +        versions: [{ weeklyHours: 12 }],
done

2020-11-20 17:27 UTC, KennyCallegari reviewed
Il faut décommenter le fichier exports.test ^^

2020-11-20 17:27 UTC, KennyCallegari commented on package.json
> +    "test": "NODE_ENV=test node_modules/.bin/mocha  --timeout 999999 --colors --exit tests/integration/exports.test.js",
tests/* ?

2020-11-23 11:17 UTC, cmolle commented on tests/unit/helpers/draftPay.test.js
>        expect(result).toBeDefined();
Il n'y en a pas besoin si ?

2020-11-23 11:17 UTC, cmolle commented on tests/unit/helpers/draftPay.test.js
> +    it('should return paid hours from absence', () => {
Je ne vois pas la difference avec le test au dessus, tu pourrais preciser dans le nom ? :)

2020-11-23 11:17 UTC, cmolle commented on tests/unit/helpers/draftPay.test.js
>        getMatchingVersion.onCall(2).returns({ weeklyHours: 24 });
J'ai l'impression que l'absence que tu consideres n'est que sur un jour, pourquoi il y a trois appels a getMatchingVersion ?

2020-11-23 11:52 UTC, KennyCallegari commented on tests/unit/helpers/draftPay.test.js
> +    it('should return paid hours from absence', () => {
Il me semble que ce test ne sert pas, j'ai oublié de le supprimer avec l'autre test

2020-11-23 11:52 UTC, KennyCallegari reviewed
✅ pour tes ajouts, @sophiemoustard

2020-11-23 12:13 UTC, cmolle approved these changes

2020-11-23 13:30 UTC, sophiemoustard approved these changes

2020-11-23 13:30 UTC, merged