COM-1653: create route
sophiemoustard/alenvi-api pull request #1146
Opened 2020-11-24 18:06 UTC by ulysseferreira

- [x] Mon code est testé unitairement
- [x] Mon code est testé avec des tests d'intégration

- Périmetre interface : mobile

- Périmetre roles : tous

- Cas d'usage : vérifier si l'email entré existe déjà ou non

2020-11-25 07:41 UTC, cmolle commented on tests/integration/users.test.js
> +    expect(res.result.data).toBeTruthy();
Tu peux utiliser plutot `toBe(true)`. toBeTruthy va etre vrai pour toute expression qui s'evalue a true, or ici on aura bien un boolean normalement

2020-11-25 08:18 UTC, sophiemoustard requested changes
tu peux reutiliser la route `/exists` en ajoutant une condition : si l'utilisateur existe et que la personne qui demande n'est pas loggué (pas de credentials je pense) tu renvoies `{ exists: true, user: {} }`

2020-11-25 12:37 UTC, ulysseferreira commented on tests/integration/users.test.js
> +    expect(res.result.data).toBeTruthy();
outdated

2020-11-25 13:02 UTC, sophiemoustard requested changes

2020-11-25 13:02 UTC, sophiemoustard commented on tests/unit/helpers/users.test.js
> +  it('should find a user if credential', async () => {
credential**s**

2020-11-25 13:02 UTC, sophiemoustard commented on tests/unit/helpers/users.test.js
> +  it('should find an email but no user if no crendential', async () => {
crendentials

2020-11-25 13:02 UTC, sophiemoustard commented on tests/unit/helpers/users.test.js
> +  it('should not find as email and credential do not exist', async () => {
je me demande si ce test est utile car le find de l'email n'est pas lié a credentials

2020-11-25 13:02 UTC, sophiemoustard commented on src/helpers/users.js
>    const targetUser = await User.findOne({ 'local.email': email }).lean();
et ici tu peux ajouter un deuxieme argument a ton find pour ne recuperer de la bdd que les données necessaires
`{ role: 1, company: 1 }`

2020-11-25 13:05 UTC, ulysseferreira commented on src/helpers/users.js
> +  return { exists: true, user: {} };
done

2020-11-25 13:07 UTC, ulysseferreira commented on tests/integration/users.test.js
> +    expect(res.result.data.users).toBeUndefined();
done

2020-11-25 13:08 UTC, ulysseferreira commented on tests/unit/helpers/users.test.js
> +  it('should find a user if credential', async () => {
done

2020-11-25 13:09 UTC, ulysseferreira commented on tests/unit/helpers/users.test.js
> +  it('should find an email but no user if no crendential', async () => {
done

2020-11-25 13:09 UTC, ulysseferreira commented on tests/unit/helpers/users.test.js
> +  it('should not find as email and credential do not exist', async () => {
done

2020-11-25 16:10 UTC, ulysseferreira commented on src/helpers/users.js
>    const targetUser = await User.findOne({ 'local.email': email }).lean();
done

2020-11-25 16:21 UTC, sophiemoustard commented on tests/unit/helpers/users.test.js
> +    ).chain('lean').returns(user);
le formatage n'est pas le bon
```
userMock
   .expects('findOne')
   .withExactArgs({ 'local.email': email }, { company: 1, role: 1 })
   .chain('lean')
   .returns(user);
```

2020-11-25 16:21 UTC, sophiemoustard commented on tests/unit/helpers/users.test.js
> +    ).chain('lean').returns(user);
et idem pour les autres

2020-11-25 16:25 UTC, cmolle commented on tests/integration/users.test.js
> +    expect(res.result.data.exists).toBeTruthy();
Tu peux utiliser plutot toBe(true). toBeTruthy va etre vrai pour toute expression qui s'evalue a true, or ici on aura bien un boolean normalement

2020-11-25 16:25 UTC, cmolle commented on tests/integration/users.test.js
>        expect(res.result.data.exists).toBeFalsy();
idem

2020-11-25 16:57 UTC, ulysseferreira commented on tests/integration/users.test.js
> +    expect(res.result.data.exists).toBeTruthy();
done

2020-11-25 16:57 UTC, ulysseferreira commented on tests/integration/users.test.js
>        expect(res.result.data.exists).toBeFalsy();
done

2020-11-25 17:02 UTC, ulysseferreira commented on tests/unit/helpers/users.test.js
> +    ).chain('lean').returns(user);
done

2020-11-25 17:59 UTC, sophiemoustard approved these changes

2020-11-26 07:41 UTC, cmolle approved these changes

2020-11-26 11:01 UTC, merged