Com 1630 fix
sophiemoustard/alenvi-api pull request #1148
Opened 2020-11-25 14:26 UTC by felix-commits

- [x] Mon code est testé unitairement
- [ ] Mon code est testé avec des tests d'intégration

- Périmetre interface : vendeur / client

- Périmetre roles : rof / coach

- Cas d'usage : le format de la formation s'affiche correctement sur ProfileCourse

2020-11-25 14:46 UTC, KennyCallegari approved these changes

2020-11-25 15:57 UTC, sophiemoustard requested changes

2020-11-25 15:57 UTC, sophiemoustard commented on src/helpers/courses.js
> +    return Course.find(query, { misc: 1 })
en fait tu peux enlever ce if car il n'est plus utilisé et enlever `trainees` de la validation de `query`

2020-11-25 15:57 UTC, sophiemoustard commented on src/helpers/courses.js
> +    return Course.find(query, { misc: 1 })
pense a faire en tour dans les tests aussi pour mettre a jour ce qu'il faut si besoin

2020-11-25 16:36 UTC, felix-commits commented on src/helpers/courses.js
> +    return Course.find(query, { misc: 1 })
done

2020-11-26 09:59 UTC, sophiemoustard approved these changes

2020-11-26 09:59 UTC, merged