Com 1657 view and add categories
sophiemoustard/alenvi-api pull request #1149
Opened 2020-11-25 15:53 UTC by felix-commits

- [x] Mon code est testé unitairement
- [x] Mon code est testé avec des tests d'intégration

- Périmetre interface : vendeur

- Périmetre roles : rof admin

- Cas d'usage : je peux voir et ajouter des catégories dans l'onglet configuration

2020-11-25 16:26 UTC, sophiemoustard requested changes

2020-11-25 16:26 UTC, sophiemoustard commented on src/controllers/categoryController.js
> +    };
sur une ligne

2020-11-25 16:26 UTC, sophiemoustard commented on src/routes/preHandlers/categories.js
> +  for (const category of categories) if (category.name === req.payload.name) throw Boom.forbidden();
tu peux faire un findOne directement sur le name pour savoir si elle existe

2020-11-25 16:26 UTC, sophiemoustard commented on src/helpers/categories.js
> +exports.list = async () => Category.find({}).lean();
tu n'as pas besoin de {} dnas find tu peux juste mettre `find()`

2020-11-25 16:40 UTC, sophiemoustard commented on src/routes/preHandlers/categories.js
> +  for (const category of categories) if (category.name === req.payload.name) throw Boom.forbidden();
et renvoie plutot une 409 (conflit) pour exploiter l'erreur en front et afficher le bon messsage d'erreur

2020-11-26 09:27 UTC, KennyCallegari commented on src/routes/preHandlers/categories.js
> +  for (const category of categories) if (category.name === req.payload.name) throw Boom.forbidden();
On peut tester avec name .toLowerCase() ou .trim(), ce qui permet de ne pas faire de doublon entre 'Catégorie ' et 'catégorie'. Qu'en pensez vous ?

2020-11-26 09:27 UTC, KennyCallegari commented on src/routes/categories.js
> +            name: Joi.string().required(),
On n'impose pas de limitation de caractère ?

2020-11-26 10:12 UTC, felix-commits commented on src/controllers/categoryController.js
> +    };
done

2020-11-26 10:12 UTC, felix-commits commented on src/routes/categories.js
> +            name: Joi.string().required(),
on le fait habituellement?

2020-11-26 10:13 UTC, felix-commits commented on src/helpers/categories.js
> +exports.list = async () => Category.find({}).lean();
done

2020-11-26 10:26 UTC, felix-commits commented on src/routes/preHandlers/categories.js
> +  for (const category of categories) if (category.name === req.payload.name) throw Boom.forbidden();
bien vu je rajoute toLowerCase! merci

2020-11-26 10:31 UTC, sophiemoustard commented on src/routes/preHandlers/categories.js
> +exports.checkCategoryNameExists = async req => (await Category.findOne({ name: req.payload.name.toLowerCase() })
si tu fais ca, il faut que tu les enregistres en base en minuscule 
tu peux donc mettre `lowercase: true` dans le model

2020-11-26 10:32 UTC, sophiemoustard commented on src/routes/preHandlers/categories.js
> +exports.checkCategoryNameExists = async req => (await Category.findOne({ name: req.payload.name.toLowerCase() })
et je trouve ca plus lisible d'ecrire : 
```
exports.checkCategoryNameExists = async req => {
const existingCourse = await Category.countDocuments({ name: req.payload.name.toLowerCase() });

return !existingCourse ? Boom.conflict()  : null
```

2020-11-26 10:32 UTC, sophiemoustard requested changes

2020-11-26 10:32 UTC, sophiemoustard commented on src/routes/preHandlers/categories.js
> +exports.checkCategoryNameExists = async req => (await Category.findOne({ name: req.payload.name.toLowerCase() })
j'ai dailleurs changer ton findone en countDocuments

2020-11-26 10:34 UTC, sophiemoustard commented on src/routes/preHandlers/categories.js
> +exports.checkCategoryNameExists = async req => (await Category.findOne({ name: req.payload.name.toLowerCase() })
et j'ai d'ailleurs changer ton findone en countdocuments

2020-11-26 10:38 UTC, KennyCallegari commented on src/routes/categories.js
> +            name: Joi.string().required(),
non tu as raison

2020-11-26 10:44 UTC, felix-commits commented on src/routes/preHandlers/categories.js
> +exports.checkCategoryNameExists = async req => (await Category.findOne({ name: req.payload.name.toLowerCase() })
d'accord merci bcp, sans le `!` devant existingCourse ?

2020-11-26 10:52 UTC, KennyCallegari approved these changes

2020-11-26 11:26 UTC, sophiemoustard approved these changes

2020-11-26 14:01 UTC, merged