COM-1665: externalize getprogress in back
sophiemoustard/alenvi-api pull request #1152
Opened 2020-11-26 09:59 UTC by ulysseferreira

- [x] Mon code est testé unitairement
- [ ] Mon code est testé avec des tests d'intégration (np)

- Périmetre interface : mobile

- Périmetre roles : tous

- Cas d'usage : externaliser dans le back le calcul de la progression pour une formation

2020-11-26 10:04 UTC, sophiemoustard requested changes

2020-11-26 10:04 UTC, sophiemoustard commented on src/helpers/courses.js
> +        progress: exports.getCourseProgress(steps),
je mettrai la progression au niveau de la formation et pas dans le sous programme non ?

2020-11-26 10:04 UTC, sophiemoustard commented on src/helpers/courses.js
> +  });
pour plus de lissibilité tu peux creer une methode `formatCourseWithProgress` qui fait ca

2020-11-26 10:04 UTC, sophiemoustard commented on src/helpers/courses.js
> +  });
et du coup ici tu retourner `return courses.map(exports.formatCourseWithProgress)

2020-11-26 10:04 UTC, sophiemoustard commented on src/helpers/courses.js
> +  });
et je pense que tu pourrais utiliser cette methode aussi pour la route `getTraineeCourse`

2020-11-26 10:04 UTC, sophiemoustard commented on tests/unit/helpers/courses.test.js
> +describe('getCourseProgress', () => {
tu peux ajouter un cas ou il n'y a pas de steps

2020-11-26 10:24 UTC, ulysseferreira commented on src/helpers/courses.js
> +        progress: exports.getCourseProgress(steps),
done

2020-11-26 13:35 UTC, ulysseferreira commented on src/helpers/courses.js
> +  });
done

2020-11-26 15:35 UTC, sophiemoustard commented on src/helpers/courses.js
> +  return steps.length ? (progressSum / steps.length) : 0;
dans ton premier if, prendss aussi le cas ou steps.length === 0

```
if (!steps || !steps.length) return 0;

return steps.map(step => step.progress).reduce((acc, value) => acc + value, 0) / steps.length;
```

2020-11-26 15:37 UTC, sophiemoustard requested changes

2020-11-26 15:37 UTC, sophiemoustard commented on src/helpers/courses.js
> +    },
sur une ligne

2020-11-26 15:37 UTC, sophiemoustard commented on tests/unit/helpers/courses.test.js
> +    const steps = null;
[] plutot

2020-11-26 19:19 UTC, ulysseferreira commented on src/helpers/courses.js
> +  return steps.length ? (progressSum / steps.length) : 0;
done

2020-11-26 19:19 UTC, ulysseferreira commented on src/helpers/courses.js
> +    },
done

2020-11-26 19:21 UTC, ulysseferreira commented on tests/unit/helpers/courses.test.js
> +    const steps = null;
done

2020-11-26 20:17 UTC, sophiemoustard approved these changes

2020-11-27 07:19 UTC, sophiemoustard approved these changes

2020-11-27 07:33 UTC, cmolle approved these changes

2020-11-27 07:33 UTC, merged