Com 1657 update (GET ROUTE)
sophiemoustard/alenvi-api pull request #1153
Opened 2020-11-26 14:30 UTC by felix-commits

- [x] Mon code est testé unitairement
- [x] Mon code est testé avec des tests d'intégration

- Périmetre interface : vendeur

- Périmetre roles : rof admin

- Cas d'usage : je peux modifier le nom dune categorie

2020-11-26 14:40 UTC, KennyCallegari commented on src/routes/preHandlers/categories.js
> +  return this.checkCategoryNameExists(req);
saut de ligne 😄

2020-11-26 14:40 UTC, KennyCallegari commented on src/routes/preHandlers/categories.js
> +  return this.checkCategoryNameExists(req);
D'ailleurs dans `checkCategoryNameExists`, il ne faut pas `throw Boom.conflict()` plutôt que return ?

2020-11-26 14:40 UTC, KennyCallegari commented on tests/integration/categories.test.js
> +      expect(categoryUpdated._id).toEqual(categoryId);
pas sûr que ce test soit utile

2020-11-26 14:40 UTC, KennyCallegari commented on tests/integration/categories.test.js
> +  const payload = { name: 'nouveau nom' };
pas besoin de cette constante, défini le directement dans chaque test plutôt

2020-11-26 14:40 UTC, KennyCallegari commented on tests/unit/helpers/categories.test.js
> +    const payload = { name: 'nouveau nom' };
pas besoin de cette constante

2020-11-26 14:40 UTC, KennyCallegari commented on tests/unit/helpers/categories.test.js
> +    expect(result).toMatchObject({ _id: categoryId, name: 'nouveau nom' });
saut de ligne

2020-11-26 14:54 UTC, felix-commits commented on src/routes/preHandlers/categories.js
> +  return this.checkCategoryNameExists(req);
je crois que les deux fonctionnent, je ne sais pas lequel est le mieux

2020-11-26 14:54 UTC, felix-commits commented on tests/integration/categories.test.js
> +      expect(categoryUpdated._id).toEqual(categoryId);
en effet

2020-11-26 15:48 UTC, sophiemoustard requested changes

2020-11-26 15:48 UTC, sophiemoustard commented on src/routes/preHandlers/categories.js
> +  if (!req.payload.name) throw Boom.badRequest();
tu n'as pas besoin de cette verification car le name est requis dans la route

2020-11-26 15:48 UTC, sophiemoustard commented on src/routes/preHandlers/categories.js
> +exports.authorizeCategoryAddition = async (req) => {
pourquoi aveoir changer le nom de cette methode ? car la c'est bizare d'appeler `authorizeCategoryAddition` dans `authorizeCategoryUpdate`

2020-11-26 15:48 UTC, sophiemoustard commented on tests/integration/categories.test.js
> +// describe('CATEGORIES ROUTES - POST /categories', () => {
oups

2020-11-26 15:48 UTC, sophiemoustard commented on tests/integration/categories.test.js
> +      expect(categoryUpdated._id).toEqual(categoryId);
tu peux verifier que le nom a bien changé par contre

2020-11-26 16:12 UTC, felix-commits commented on src/routes/preHandlers/categories.js
> +exports.authorizeCategoryAddition = async (req) => {
comme j'avais rajouté le `if` sur le payload ca n'avait plus a voir avec l'ancien nom

2020-11-26 16:12 UTC, felix-commits commented on src/routes/preHandlers/categories.js
> +  if (!req.payload.name) throw Boom.badRequest();
cool!

2020-11-26 16:12 UTC, felix-commits commented on src/routes/preHandlers/categories.js
> +  if (!req.payload.name) throw Boom.badRequest();
je n'etais pas sur que lerreur renvoyée allait etre une 400

2020-11-26 16:13 UTC, felix-commits commented on tests/integration/categories.test.js
> +// describe('CATEGORIES ROUTES - POST /categories', () => {
done

2020-11-26 17:06 UTC, sophiemoustard requested changes

2020-11-26 17:13 UTC, KennyCallegari approved these changes

2020-11-26 17:15 UTC, sophiemoustard commented on tests/integration/categories.test.js
> +      expect(response.statusCode).toBe(200);
et tu peux verifier ca avant e faire l'appel `categoryUpdated`

2020-11-27 09:25 UTC, sophiemoustard approved these changes

2020-11-27 09:27 UTC, merged