Com 1658
sophiemoustard/alenvi-api pull request #1157
Opened 2020-11-27 16:34 UTC by felix-commits

- [x] Mon code est testé unitairement
- [ ] Mon code est testé avec des tests d'intégration - a faire

- Périmetre interface : vendeur

- Périmetre roles : rof admin

- Cas d'usage : a la creation dun programme jajoute une categorie

2020-11-27 16:44 UTC, sophiemoustard requested changes

2020-11-27 16:44 UTC, sophiemoustard commented on src/routes/programs.js
> +            category: Joi.objectId().required(),
tu pourrais envoyer directement `categories: Joi.array().items(Joi.objectId()).length(1)`

2020-11-27 16:44 UTC, sophiemoustard commented on src/routes/programs.js
> +            category: Joi.objectId().required(),
et comme le champs est requis il faut que tu changes aussi tes tests d'intégration

2020-11-27 17:10 UTC, KennyCallegari commented on src/routes/programs.js
> +            category: Joi.objectId().required(),
Pour garder la même logique qu'accessRules, il vaut mieux avoir qu'une catégorie dans le payload.
Qu'en penses-tu ?

2020-11-30 15:47 UTC, KennyCallegari submitted a review, later dismissed

2020-11-30 17:34 UTC, sophiemoustard requested changes

2020-11-30 17:34 UTC, sophiemoustard commented on src/routes/preHandlers/categories.js
> +exports.checkCategoryIsEmpty = async (req) => {
le nom n'est pas tres clair...
tu peux mettre `authorizeCategoryDeletion`

2020-11-30 17:34 UTC, sophiemoustard commented on src/routes/preHandlers/categories.js
> +  return !isEmpty(emptyCategory.programs) ? Boom.forbidden() : null;
ici tu peux faire un requete directement sur les programmes `Program.countDocuments({ categories: req.params._id })

2020-11-30 17:34 UTC, sophiemoustard commented on src/routes/preHandlers/programs.js
> +  const category = await Category.countDocuments({ _id: req.payload.categories[0] });
il faut que tu fasse un if sur `req.payload.categories` car ce n'est pas toujours present si tu mets a jour le nom du programme par exemple

2020-11-30 17:34 UTC, sophiemoustard commented on src/routes/programs.js
> +            categories: Joi.array().items(Joi.objectId()).length(1).required(),
ici tu peux utiliser 
```
Joi.alternatives().try(
   Joi.object({ name: Joi.string().required() }),
   Joi.object({ categories: Joi.array().items(Joi.objectId()).length(1).required() })
),
```
car tu veux soit le nom soit les categories

2020-11-30 17:34 UTC, sophiemoustard commented on tests/integration/categories.test.js
> +// describe('CATEGORIES ROUTES - POST /categories', () => {
oups

2020-11-30 17:34 UTC, sophiemoustard commented on tests/integration/programs.test.js
>      it('should create program', async () => {
ici tu peux faire 2 tests distincts `should create program name` et `should create program categories`

2020-11-30 17:34 UTC, sophiemoustard commented on src/models/Category.js
> +CategorySchema.virtual('programs', {
il fait que tu populate ce virtual dans le liste de categories pour pouvoir envoyer un NotifyWarning en front sans faire l'appel au back pour bloquer la suppresssion - c'est une petite amelioration UX sympathique

2020-11-30 17:35 UTC, sophiemoustard commented on src/routes/preHandlers/programs.js
> +exports.checkCategoryExists = async (req) => {
a appeler authorizeProgramUpdate plutot

2020-11-30 17:44 UTC, sophiemoustard commented on src/models/Category.js
> +});
tu peux l'appeler programsCount et jusste recuperer le nombre de programmes d'ailleurs

2020-12-01 10:16 UTC, KennyCallegari commented on tests/integration/categories.test.js
> +      const categoriesNumber = await Category.count();
categoriesCount plutôt 😄

2020-12-01 11:21 UTC, sophiemoustard commented on tests/integration/categories.test.js
> +      expect(await Category.count()).toEqual(categoriesCount - 1);
countDocuments

2020-12-01 11:24 UTC, KennyCallegari approved these changes

2020-12-01 11:24 UTC, KennyCallegari commented on src/routes/preHandlers/categories.js
> +  return isUsed ? Boom.forbidden() : null;
saut de ligne

2020-12-01 11:26 UTC, sophiemoustard commented on tests/integration/categories.test.js
> +      const categoriesCount = await Category.count();
countDocuments

2020-12-01 11:27 UTC, felix-commits commented on tests/integration/categories.test.js
> +      const categoriesCount = await Category.count();
oui jallais push force

2020-12-01 12:53 UTC, sophiemoustard approved these changes

2020-12-01 12:53 UTC, merged