Com 1655 - Tabs
sophiemoustard/alenvi-api pull request #1158
Opened 2020-11-27 16:54 UTC by KennyCallegari

- [x] Mon code est testé unitairement
- [ ] Mon code est testé avec des tests d'intégration - np

- Périmetre interface : vendor

- Périmetre roles : admin / rof

- Cas d'usage : 
populate de accessRules pour les récupérer en front

2020-11-27 19:14 UTC, sophiemoustard approved these changes

2020-11-30 10:01 UTC, felix-commits approved these changes

2020-11-30 16:41 UTC, sophiemoustard requested changes
comme tu as changé la methode, il faudrait que tu mettes a jour les tests aussi `getTraineeProgress`

2020-11-30 16:41 UTC, sophiemoustard commented on src/helpers/courses.js
> +  return { steps: formattedSteps, progress: courseProgress };
tu peux mettre directement `  return { steps: formattedSteps, progress: exports.getCourseProgress(formattedSteps); };`

2020-12-01 09:54 UTC, KennyCallegari commented on src/helpers/courses.js
> +  return { steps: formattedSteps, progress: courseProgress };
done

2020-12-01 10:30 UTC, sophiemoustard requested changes

2020-12-01 10:30 UTC, sophiemoustard commented on tests/unit/helpers/courses.test.js
> +    const formattedSteps = [{
ne pas definir cette variable et mettre les objets / tableau directement dans `calledOnceWithExactly` etc
pour notamement ne pas utiliser de pick

2020-12-01 10:51 UTC, sophiemoustard approved these changes

2020-12-01 12:17 UTC, merged