Com 1659
sophiemoustard/alenvi-api pull request #1168
Opened 2020-12-02 16:43 UTC by felix-commits

- [ ] Mon code est testé unitairement - np
- [x] Mon code est testé avec des tests d'intégration

- Périmetre interface : vendeur

- Périmetre roles : rof admin

- Cas d'usage : je peux ajouter des catégories

2020-12-03 08:47 UTC, sophiemoustard commented on src/routes/preHandlers/programs.js
> +exports.authorizeCategoryAddition = async (req) => {
je ne comprends pas ce que tu cherches a faire ici...

2020-12-03 08:55 UTC, sophiemoustard commented on src/routes/preHandlers/programs.js
> +exports.authorizeCategoryAddition = async (req) => {
aussi des qu'on fait une requete a la base, on ajoute toujours `lean` a la fin pour transformer l'objet mongoose en objet js moins lourd et plus manipulable

2020-12-03 08:57 UTC, sophiemoustard requested changes

2020-12-03 08:57 UTC, sophiemoustard commented on tests/integration/programs.test.js
> +        categories: [categoriesList[0]._id, categoriesList[1]._id],
pour etre coherent avec la realité tu peux mettre juste un id dans le tableau

2020-12-03 12:48 UTC, KennyCallegari commented on src/routes/preHandlers/programs.js
> +  return difference(req.payload.categories, categories).length === 0 ? null : Boom.badRequest();
C'est sympa cette fonction !
Tu peux aussi verifier 2 choses avant :
- si categories de ton payload a une length = categories + 1
- si l'id du dernier élement est bien un id de catégorie

Fait gaffe au saut de ligne aussi 😄

2020-12-03 14:59 UTC, felix-commits commented on src/routes/preHandlers/programs.js
> +exports.authorizeCategoryAddition = async (req) => {
j'aimerais vérifier que tous les ids que je passe dans mon payload sont bien des ids de catégories existantes en base, sinon il renvoie une bad request, je ne sais pas si il y a plus simple, jutilise difference de lodash qui soustrait deux arrays https://github.com/lodash/lodash/issues/1743

2020-12-04 13:27 UTC, sophiemoustard requested changes

2020-12-04 13:27 UTC, sophiemoustard commented on src/controllers/programController.js
> +    };
sur une ligne

2020-12-04 13:27 UTC, sophiemoustard commented on src/controllers/programController.js
> +    };
sur une ligne

2020-12-04 13:27 UTC, sophiemoustard commented on src/routes/preHandlers/programs.js
> +  if (!categoryId) categoryId = get(req, 'payload.categoryId');
tu peux mettre `const categoryId = get(req, 'payload.categories[0]') || get(req, 'payload.categoryId')`;

2020-12-04 13:27 UTC, sophiemoustard commented on src/routes/preHandlers/programs.js
> +  if (!category) throw Boom.notFound();
passe une ligne apres

2020-12-04 13:27 UTC, sophiemoustard commented on src/routes/programs.js
> +      },
il faut aussi que tu mettes `pre: [{ method: checkProgramExists }, { method: checkCategoryExists }],`

2020-12-04 13:27 UTC, sophiemoustard commented on tests/integration/programs.test.js
> +  const payload = { categoryId: categoriesList[1]._id };
a mettre dans les it ou c'est utile

2020-12-04 15:08 UTC, KennyCallegari approved these changes

2020-12-04 16:35 UTC, sophiemoustard requested changes

2020-12-04 16:35 UTC, sophiemoustard commented on tests/integration/programs.test.js
> +        url: `/subprograms/${programsList[0]._id}/steps/${categoryId}`,
tu t'es trompé dans l'url

2020-12-04 16:35 UTC, sophiemoustard commented on tests/integration/programs.test.js
> +
il manque les tests sur la route POST non ?

2020-12-04 19:15 UTC, sophiemoustard approved these changes

2020-12-04 19:15 UTC, merged