Com 1656
sophiemoustard/alenvi-api pull request #1170
Opened 2020-12-03 15:48 UTC by ulysseferreira

- [x] Mon code est testé unitairement
- [x] Mon code est testé avec des tests d'intégration

- Périmetre interface : mobile

- Périmetre roles : tous

- Cas d'usage : un apprenan a accès aux formations de sa structure et aux formations en libre accès

2020-12-03 18:19 UTC, cmolle reviewed
Je pense qu'il faut aussi changer la route courses/user. Je pense que si quelqu'un s'est inscrit a une formation a laquelle il n'avait pas le droit, il ne faut pas qu'elle apparaisse dans ses formations.

2020-12-03 18:19 UTC, cmolle commented on src/helpers/programs.js
> +  const companyId = credentials.company ? credentials.company._id : null;
get(credentials, 'company._id'). comme tu ne l'utilises que dans le find tu n'as pas besoin d'une variable

2020-12-03 18:19 UTC, cmolle commented on tests/integration/courses.test.js
> +  it('should get course if has access authorization', async () => {
il manque une ligne avant ton it

2020-12-03 18:19 UTC, cmolle commented on tests/integration/courses.test.js
> +  it('should not get course if has not access authorization', async () => {
idem

2020-12-03 21:37 UTC, sophiemoustard commented on src/routes/preHandlers/courses.js
> +      $expr: {
ssi l'apprenant a reussi a s'inscrire c'est que a priori il a le droit de voir cette formation non ?
je pense qu'il vaut meiux faire la verification au moment de l'inscription pour empecher l'inscription si en desaccord avec les regles d'acces. mais une fois qu'il est inscrit, ne plus faire la verification

2020-12-04 13:52 UTC, ulysseferreira commented on src/helpers/programs.js
> +  const companyId = credentials.company ? credentials.company._id : null;
done

2020-12-04 13:53 UTC, ulysseferreira commented on tests/integration/courses.test.js
> +  it('should get course if has access authorization', async () => {
done

2020-12-04 13:53 UTC, ulysseferreira commented on tests/integration/courses.test.js
> +  it('should not get course if has not access authorization', async () => {
done

2020-12-04 13:55 UTC, ulysseferreira commented on src/routes/preHandlers/courses.js
> +      $expr: {
🤷‍♂️ c'est ce qui était demandé dans le ticket
c'est sans doute pour éviter des contournements avec postman

2020-12-07 13:34 UTC, sophiemoustard requested changes

2020-12-07 13:34 UTC, sophiemoustard commented on src/helpers/courses.js
> +  const traineeId = trainee._id;
en as tu vraiment besoin ?

2020-12-07 13:34 UTC, sophiemoustard commented on src/routes/preHandlers/courses.js
> +    (!companyId || !accessRules.map(id => id.toHexString()).includes(companyId.toHexString()))) throw Boom.forbidden();
tu peux faire un some au lieu d'un map non ?

2020-12-07 13:34 UTC, sophiemoustard commented on src/routes/preHandlers/courses.js
> +
ilvaut meiux mettre la ligne vide avant non ?

2020-12-07 13:34 UTC, sophiemoustard commented on src/routes/preHandlers/courses.js
> +  return { _id: get(credentials, '_id'), company: get(credentials, 'company._id') };
tu peux inverser la logique la 
```
if (!traineeId)   return { _id: get(credentials, '_id'), company: get(credentials, 'company._id') };

....
```

2020-12-07 13:47 UTC, sophiemoustard approved these changes

2020-12-07 15:40 UTC, merged