Com 1661
sophiemoustard/alenvi-api pull request #1171
Opened 2020-12-03 17:39 UTC by KennyCallegari

- [x] Mon code est testé unitairement
- [x] Mon code est testé avec des tests d'intégration

- Périmetre interface : vendor

- Périmetre roles : rof / admin / coach /trainer

- Cas d'usage : 
Refacto de la convocation papier, qui est maintenant sous format pdf et généré par le back

2020-12-03 17:53 UTC, KennyCallegari commented on src/routes/courses.js
> +        pre: [{ method: getCourse, assign: 'course' }],
Pas sûr de moi ici
Je ne vois pas pourquoi client_admin aurait accès à ce pdf et je ferai bien des test pour vérifier que le trainer consulte bien sa formation, que le coach est bien sur une formation de sa company dans le cas des intra. Peut-être un checkAuthorization ?
Qu'en pensez-vous ?

2020-12-04 09:30 UTC, sophiemoustard requested changes

2020-12-04 09:30 UTC, sophiemoustard commented on src/controllers/courseController.js
> +const generatePdf = async (req, h) => {
idem que le front tu peux mettre convocation plutot que pdf

2020-12-04 09:30 UTC, sophiemoustard commented on src/controllers/courseController.js
> +const generatePdf = async (req, h) => {
et pour les autres methodes et le nom du fichiers html

2020-12-04 09:30 UTC, sophiemoustard commented on src/data/blendedCourseInfo.html
> +<style>
que penses tu de courseConvocation ?

2020-12-04 09:30 UTC, sophiemoustard commented on src/data/blendedCourseInfo.html
> +  }
ce n'est pas utilisé

2020-12-04 09:30 UTC, sophiemoustard commented on src/data/blendedCourseInfo.html
> +  }
j'enleverais cette classe car il y je pense qu'il vaut mieux ne pas centrer verticalement

2020-12-04 09:30 UTC, sophiemoustard commented on src/data/blendedCourseInfo.html
> +    width: 110px;
tu peux reduire un peu a 96px

2020-12-04 09:30 UTC, sophiemoustard commented on src/data/blendedCourseInfo.html
> +    margin-right: 23px;
base 8 donc 16 et 24

2020-12-04 09:30 UTC, sophiemoustard commented on src/data/blendedCourseInfo.html
> +    margin-right: 60px;
48

2020-12-04 09:30 UTC, sophiemoustard commented on src/data/blendedCourseInfo.html
> +  .item-container {
a supprimer
et plutot mettre 
```
.col-6 {
   width: 50%
}
```
sur les 2 blocs qui sont cote a cote et pour celui des programmes quie st tout seul il vaut mieux qu'il prenne toute la largeur

2020-12-04 09:30 UTC, sophiemoustard commented on src/data/blendedCourseInfo.html
> +    font-size: 14px;
je trouve que 14 c'est un peu gros, tu pourrais mettre 12 qu'en penses tu ? et idem pour tous les 14px

2020-12-04 09:30 UTC, sophiemoustard commented on src/data/blendedCourseInfo.html
> +    color: #E2007A;
tu peux ajouter font-size: 12px

2020-12-04 09:30 UTC, sophiemoustard commented on src/data/blendedCourseInfo.html
> +    margin-left: 15px;
16px

2020-12-04 09:30 UTC, sophiemoustard commented on src/data/blendedCourseInfo.html
> +    font-size: 18px;
on pourrait juste mettre 16px

2020-12-04 09:30 UTC, sophiemoustard commented on src/data/blendedCourseInfo.html
> +  }
a enlever

2020-12-04 09:30 UTC, sophiemoustard commented on src/data/blendedCourseInfo.html
> +            src="https://res.cloudinary.com/alenvi/image/upload/v1587048743/images/business/Compani/doct-explication.png">
une indentation en trop - idem pour toutes les images

2020-12-04 09:30 UTC, sophiemoustard commented on src/helpers/courses.js
> +    : '';
ca pourrait etre une methode utils qu'en penses tu ?

2020-12-04 09:30 UTC, sophiemoustard commented on src/routes/courses.js
> +        pre: [{ method: getCourse, assign: 'course' }],
est ce que ca ne correspondrait pas a `authorizeCourseEdit` ?

2020-12-04 13:12 UTC, sophiemoustard requested changes

2020-12-04 13:12 UTC, sophiemoustard commented on src/routes/courses.js
> +        pre: [{ method: getCourse, assign: 'course' }],
vu ensemble reprendre la même authentification que `/public-infos` donc `auth: { mode: 'optional' },`

2020-12-04 15:19 UTC, KennyCallegari commented on src/controllers/courseController.js
> +const generatePdf = async (req, h) => {
done

2020-12-04 15:21 UTC, KennyCallegari commented on src/data/blendedCourseInfo.html
> +<style>
top !
done

2020-12-04 15:22 UTC, KennyCallegari commented on src/data/blendedCourseInfo.html
> +  }
done

2020-12-04 15:22 UTC, KennyCallegari commented on src/data/blendedCourseInfo.html
> +  }
done

2020-12-04 15:23 UTC, KennyCallegari commented on src/data/blendedCourseInfo.html
> +    margin-right: 23px;
done

2020-12-04 15:23 UTC, KennyCallegari commented on src/data/blendedCourseInfo.html
> +    width: 110px;
done

2020-12-04 15:25 UTC, KennyCallegari commented on src/data/blendedCourseInfo.html
> +    font-size: 14px;
done

2020-12-04 15:26 UTC, KennyCallegari commented on src/data/blendedCourseInfo.html
> +    color: #E2007A;
done

2020-12-04 15:26 UTC, KennyCallegari commented on src/data/blendedCourseInfo.html
> +  }
done

2020-12-04 15:32 UTC, KennyCallegari commented on src/data/blendedCourseInfo.html
> +            src="https://res.cloudinary.com/alenvi/image/upload/v1587048743/images/business/Compani/doct-explication.png">
done

2020-12-04 15:35 UTC, KennyCallegari commented on src/helpers/courses.js
> +    : '';
yes! done

2020-12-04 15:47 UTC, felix-commits approved these changes
la convocation rend super bien je trouve! trop fort

2020-12-04 15:47 UTC, felix-commits commented on src/data/blendedCourseInfo.html
> +  .img {
est-ce voulu qu'il n'y ai pas le titre avec bandeau violet _Votre formation Compani_
et peut-etre ajouter le logo de Compani ( a voir avec Romain)

2020-12-04 15:47 UTC, felix-commits commented on src/data/blendedCourseInfo.html
> +  .img {
<img width="794" alt="Capture d’écran 2020-12-04 à 16 45 04" src="https://user-images.githubusercontent.com/70573684/101183912-5e299880-3650-11eb-8ec7-9bdae746e8f8.png">

2020-12-04 16:07 UTC, KennyCallegari commented on src/helpers/courses.js
> +    : '';
done

2020-12-04 16:08 UTC, KennyCallegari commented on src/data/blendedCourseInfo.html
> +    font-size: 18px;
done

2020-12-04 16:08 UTC, KennyCallegari commented on src/data/blendedCourseInfo.html
> +  .item-container {
done

2020-12-04 16:08 UTC, KennyCallegari commented on src/data/blendedCourseInfo.html
> +    margin-left: 15px;
done

2020-12-04 16:28 UTC, sophiemoustard requested changes

2020-12-04 16:28 UTC, sophiemoustard commented on src/data/courseConvocation.html
> +  }
a enlever

2020-12-04 16:28 UTC, sophiemoustard commented on tests/integration/courses.test.js
> +  });
puique ur teste pour un utilisateur non authentifie2 tu n'es pas obligé de faire ces tests

2020-12-04 16:28 UTC, sophiemoustard commented on tests/integration/courses.test.js
> +    });
a sortir du describe VENDOR admin

2020-12-04 16:28 UTC, sophiemoustard commented on src/data/courseConvocation.html
> +  .container {
a enlever

2020-12-04 16:28 UTC, sophiemoustard commented on src/data/courseConvocation.html
> +  .course {
a enlever

2020-12-04 16:28 UTC, sophiemoustard commented on src/data/courseConvocation.html
> +  .title {
ajouter 
    align-items: center;

2020-12-04 16:28 UTC, sophiemoustard commented on src/data/courseConvocation.html
> +  <div class="container">
tu peux utiliser une classe specifique
```
.slots {
    display: flex;
    flex-direction: column;
    align-items: center;
    margin-bottom: 16px;
  }
```

2020-12-04 16:28 UTC, sophiemoustard commented on src/data/courseConvocation.html
> +    margin: 16px 8px;
a enlever et remplacer par 
```
    align-items: center;
    margin-bottom: 16px;
```

2020-12-04 16:28 UTC, sophiemoustard commented on src/data/courseConvocation.html
> +  <div class="container">
as tu besoin de cette div ?

2020-12-04 16:28 UTC, sophiemoustard commented on src/helpers/courses.js
> +  const course = await exports.getCoursePublicInfos({ _id: courseId });
tu peux supprimer cette methode et faire directement l'appel a la base ici

2020-12-04 17:26 UTC, KennyCallegari commented on src/data/courseConvocation.html
> +  }
done

2020-12-04 17:29 UTC, KennyCallegari commented on tests/integration/courses.test.js
> +  });
done

2020-12-04 17:29 UTC, KennyCallegari commented on tests/integration/courses.test.js
> +    });
done

2020-12-04 17:30 UTC, KennyCallegari commented on src/data/courseConvocation.html
> +  .container {
done

2020-12-04 17:31 UTC, KennyCallegari commented on src/data/courseConvocation.html
> +  .course {
done

2020-12-04 17:31 UTC, KennyCallegari commented on src/data/courseConvocation.html
> +  .title {
done

2020-12-04 17:32 UTC, KennyCallegari commented on src/data/courseConvocation.html
> +    margin: 16px 8px;
done

2020-12-04 17:33 UTC, KennyCallegari commented on src/data/courseConvocation.html
> +  <div class="container">
done

2020-12-04 17:33 UTC, KennyCallegari commented on src/data/courseConvocation.html
> +  <div class="container">
done

2020-12-04 17:45 UTC, KennyCallegari commented on src/helpers/courses.js
> +  const course = await exports.getCoursePublicInfos({ _id: courseId });
done

2020-12-04 17:46 UTC, KennyCallegari commented on src/data/courseConvocation.html
> +    margin: 16px 8px;
le align-items center ne fonctionne pas :/
Le title + l'image ne se mettent pas au centre, je creuse ça

2020-12-04 18:00 UTC, sophiemoustard commented on src/data/courseConvocation.html
> +      <h2>{{ subProgram.program.name }}<div>{{#if misc}}{{ misc }}{{/if}}</div></h2>
tu peux enlever la div pour que le misc n'aille pas automatiquement a la ligne

2020-12-04 18:03 UTC, KennyCallegari commented on src/data/courseConvocation.html
> +      <h2>{{ subProgram.program.name }}<div>{{#if misc}}{{ misc }}{{/if}}</div></h2>
done

2020-12-04 18:06 UTC, sophiemoustard approved these changes

2020-12-04 22:11 UTC, merged