Com 1691 - refacto qcm/qcu/questionAnswers
sophiemoustard/alenvi-api pull request #1185
Opened 2020-12-09 14:58 UTC by KennyCallegari

- [x] Mon code est testé unitairement
- [x] Mon code est testé avec des tests d'intégration

- Périmetre interface : vendor

- Périmetre roles : admin / rof

- Cas d'usage : 
qcuFalsyAnswers, qcmAnswers et questionAnswers sont fondus en un seul champ qAnswers.
L'utilisation des qcm et des qcu se fera sous la même forme que question answer :
- ajout des champs answer en plus via un bouton
- passage par les routes /{_id}/answers (POST, PUT, DELETE)

Dans cette PR :
- uniquement la refonte en un seul champ
- le fait que qcm et qcu ne soit plus comme avant est voulu (préparation à l'ajout de réponse par bouton)
- on reste sur une modification par la route updateCard, donc les tests seront amenés à être changés. Pour l'instant je les ai adapté pour ne pas avoir d'erreurs et tester que le comportement reste bien le même malgré la fusion des champs.

2020-12-09 15:05 UTC, KennyCallegari commented on tests/integration/cards.test.js
> +          code: 200, // A GÉRER ?
Ici je ne gère plus la taille des réponses car la taille des réponses diffère entre questionAnswer et qcm/qcuAnswer.
Les solutions que je vois : 
- distinguer les cas avec un preHandler
- laisser comme ça et l'utilisateur aura un champ invalide (donc pas de publication) mais pas d'erreur back

Qu'en pensez-vous ?

2020-12-09 15:05 UTC, KennyCallegari commented on tests/integration/cards.test.js
> +          code: 200, // A GÉRER ?
same

2020-12-09 15:05 UTC, KennyCallegari commented on src/routes/cards.js
> +            })).min(1),
cf mes messages pour la suppression du .max() ici

2020-12-09 15:07 UTC, sophiemoustard requested changes

2020-12-09 15:07 UTC, sophiemoustard commented on src/helpers/cards.js
> +exports.addCardAnswer = async cardId => Card.updateOne({ _id: cardId }, { $push: { qAnswers: { text: '' } } });
on etait plutot parti sur `qcAnswers`

2020-12-09 15:12 UTC, sophiemoustard commented on tests/integration/cards.test.js
> +          code: 200, // A GÉRER ?
cf notre point de ce midi ce test est a enlever car il ne sera plus dans cette route a terme

2020-12-09 15:20 UTC, sophiemoustard commented on src/routes/cards.js
> +            })).min(1),
c'est un peu dommage de modifier cette partie que tu vas supprimer dans la prochaine PR - je pense tu peux carrement supprimer l'edition des reponses sur cette route 
Ce n'est pas grave si on ne peut plus editer suite a cette PR, la suite viendra - le perimetre etant ici : 
- si je cree une QCU, j'ai une mauvaise reponse d'initialise
- si je cree une QCM, j'ai deux mauvaises reponses d'initialisees
- si je cree une QA, j'ai deux mauvaises reponses d'initialisees

2020-12-09 15:20 UTC, sophiemoustard commented on src/routes/cards.js
> +            })).min(1),
tu peux aussi enlever ce qui en decoulke dans le prehandler et les tests

2020-12-09 16:20 UTC, KennyCallegari commented on src/routes/cards.js
> +            })).min(1),
done

2020-12-09 16:20 UTC, KennyCallegari commented on tests/integration/cards.test.js
> +          code: 200, // A GÉRER ?
done

2020-12-09 16:21 UTC, KennyCallegari commented on src/helpers/cards.js
> +exports.addCardAnswer = async cardId => Card.updateOne({ _id: cardId }, { $push: { qAnswers: { text: '' } } });
done

2020-12-09 16:54 UTC, sophiemoustard approved these changes

2020-12-10 09:50 UTC, felix-commits commented on src/helpers/cards.js
> +exports.addCardAnswer = async cardId => Card.updateOne({ _id: cardId }, { $push: { qcAnswers: { text: '' } } });
dans le cas de `multipleQuestionAnswer` tu peux set `correct` à `false`?

2020-12-10 09:50 UTC, felix-commits commented on src/helpers/cards.js
> +  { $set: { 'qcAnswers.$.text': payload.text } }
je crois que sophie avait parlé de la méthode `flat` qui met a jour uniquement text ou correct en fonction du payload.. quelquechose comme ca ? : `{ $set: flat({ ['${field}.$']: payload }) }`

2020-12-10 09:58 UTC, felix-commits reviewed
tu peux enlever `SINGLE_CHOICE_QUESTION_MAX_FALSY_ANSWERS_COUNT` `MULTIPLE_CHOICE_QUESTION_MAX_ANSWERS_COUNT` `QUESTION_ANSWER_MAX_ANSWERS_COUNT` de constants.js

2020-12-10 10:05 UTC, sophiemoustard commented
> tu peux enlever `SINGLE_CHOICE_QUESTION_MAX_FALSY_ANSWERS_COUNT` `MULTIPLE_CHOICE_QUESTION_MAX_ANSWERS_COUNT` `QUESTION_ANSWER_MAX_ANSWERS_COUNT` de constants.js

non car on va les reutiliser dans la PR suivantess

2020-12-10 10:07 UTC, felix-commits commented
> > tu peux enlever `SINGLE_CHOICE_QUESTION_MAX_FALSY_ANSWERS_COUNT` `MULTIPLE_CHOICE_QUESTION_MAX_ANSWERS_COUNT` `QUESTION_ANSWER_MAX_ANSWERS_COUNT` de constants.js
> 
> non car on va les reutiliser dans la PR suivante normalement

coté webapp aussi decoup?

2020-12-10 12:36 UTC, felix-commits approved these changes

2020-12-10 13:02 UTC, merged