COM-1690 refacto orderTheSequence
sophiemoustard/alenvi-api pull request #1193
Opened 2020-12-14 16:00 UTC by felix-commits

- [ ] Mon code est testé unitairement -np
- [ ] Mon code est testé avec des tests d'intégration - np

- Périmetre interface : vendeur

- Périmetre roles : rof

- Cas d'usage : get orderedAnswers

2020-12-14 16:00 UTC, KennyCallegari approved these changes

2020-12-14 18:15 UTC, sophiemoustard requested changes

2020-12-14 18:15 UTC, sophiemoustard commented on tests/integration/cards.test.js
> +      const cardUpdated = await Card.findById(card._id).lean();
Est ce que tu pourrais faire comme suit ?
```
const cardUpdated = await Card.countDocuments({ _id: card._id,  orderedAnswers: { _id: card.orderedAnswers[0]._id, text: 'je suis un texte' } });
expect(cardUpdated).toEqual(1);
```

2020-12-15 08:28 UTC, felix-commits commented on tests/integration/cards.test.js
> +      const cardUpdated = await Card.findById(card._id).lean();
j'ai changé les deux, ça fonctionne bien sur les tests locaux

2020-12-15 09:08 UTC, sophiemoustard approved these changes

2020-12-15 11:31 UTC, merged