Com 1693 refacto put
sophiemoustard/alenvi-api pull request #1196
Opened 2020-12-15 14:14 UTC by KennyCallegari

- [x] Mon code est testé unitairement
- [x] Mon code est testé avec des tests d'intégration

- Périmetre interface : vendor

- Périmetre roles : admin / rof

- Cas d'usage : 
Pour update les réponses des cartes 'texte à trou', je passe désormais par la route updateAnswer

2020-12-15 15:38 UTC, sophiemoustard requested changes

2020-12-15 15:38 UTC, sophiemoustard commented on src/routes/preHandlers/cards.js
>  const isValidAnswersCaracters = answers => answers.every(v => /^[a-zA-Z0-9àâçéèêëîïôûùü\040'-]*$/.test(v));
si c'est la meme regex il faudrait mutualiser : une methode qui valide pour une reponse et passser le every dans la methode `checkFillTheGap`

2020-12-15 15:43 UTC, KennyCallegari commented on src/routes/preHandlers/cards.js
>  const isValidAnswersCaracters = answers => answers.every(v => /^[a-zA-Z0-9àâçéèêëîïôûùü\040'-]*$/.test(v));
done

2020-12-15 16:25 UTC, sophiemoustard approved these changes

2020-12-16 09:53 UTC, felix-commits approved these changes

2020-12-16 10:14 UTC, merged