COM-1713: don't send refreshToken after create account
sophiemoustard/alenvi-api pull request #1221
Opened 2020-12-31 10:18 UTC by ulysseferreira

- [x] Mon code est testé unitairement
- [ ] Mon code est testé avec des tests d'intégration -np

- Périmetre interface : tous

- Périmetre roles : formateur & sans role

- Cas d'usage : ne pas renvoyer le refreshToken et le mot de passe quand on créé un utilisateur formateur depuis la web app ou apprenant depuis le mobile

2021-01-04 07:33 UTC, cmolle commented on src/helpers/users.js
> +      .lean({ virtuals: true, autopopulate: true });
sur une ligne

2021-01-04 07:33 UTC, cmolle commented on src/helpers/users.js
> +      .lean({ virtuals: true });
sur une ligne

2021-01-04 07:33 UTC, cmolle commented on tests/unit/helpers/users.test.js
> +    UserMock.expects('findOne')
Tu pourrais changer les tests pour createUser avec la nouvelle methode sans utiliser sinonMongoose ?

2021-01-04 07:35 UTC, cmolle commented
Est-ce que tu as pu creuser pour voir pourquoi le `select: false` ne fonctionnait pas lors d'un `create` ?

2021-01-04 08:46 UTC, ulysseferreira commented on src/helpers/users.js
> +      .lean({ virtuals: true, autopopulate: true });
done

2021-01-04 08:46 UTC, ulysseferreira commented on src/helpers/users.js
> +      .lean({ virtuals: true });
done

2021-01-04 14:25 UTC, ulysseferreira commented on tests/unit/helpers/users.test.js
> +    UserMock.expects('findOne')
done

2021-01-05 08:21 UTC, sophiemoustard commented on tests/unit/helpers/users.test.js
ce n'est pas le bon format ; 
soit tu mets `[payload]` et `[payload]` sur la meme ligne
soit tu mets chacun sur une ligne

idem pour le reste

2021-01-05 08:22 UTC, sophiemoustard reviewed
As tu pu regarder le post hook

2021-01-05 08:23 UTC, sophiemoustard commented on src/helpers/users.js
> +    return User.findOne({ _id: user._id }).lean({ virtuals: true, autopopulate: true });
pourquoi ne l'as tu mis en place que pour 2 cas et pas tous les `return User.create` ?
Cela dit si le post hook fonctionne c'est mieux de l'utiliser

2021-01-05 17:44 UTC, sophiemoustard requested changes

2021-01-06 13:27 UTC, cmolle commented on src/models/User.js
> +async function formatPayload(doc, next) {
Je crois que tu peux enlever tous les no-param-reassign

2021-01-06 13:27 UTC, cmolle commented on tests/unit/helpers/users.test.js
> -    UserMock.expects('findOne').never();
Je crois que tu n'as pas ajouter le sinon.assert.notCalled(userfindOne)

2021-01-06 14:23 UTC, ulysseferreira commented on src/models/User.js
> +async function formatPayload(doc, next) {
done

2021-01-06 14:32 UTC, ulysseferreira commented on tests/unit/helpers/users.test.js
> -    UserMock.expects('findOne').never();
done

2021-01-06 14:34 UTC, cmolle approved these changes

2021-01-06 18:04 UTC, sophiemoustard approved these changes

2021-01-07 08:06 UTC, merged