Com 1789
sophiemoustard/alenvi-api pull request #1224
Opened 2021-01-04 15:10 UTC by KennyCallegari

npm update

+ Fix des tests unitaires qui cassaient depuis le nouvel an

2021-01-04 15:32 UTC, felix-commits commented on src/extensions/moment.js
> +  ...holidays.getHolidays(currentYear - 2),
faudrait-il plutot écrire ` ...holidays.getHolidays(2019)` pour ne pas le refaire chaque année?

2021-01-04 15:37 UTC, KennyCallegari commented on src/extensions/moment.js
> +  ...holidays.getHolidays(currentYear - 2),
Yes, je me demande qu'elle est la meilleure façon de faire, je suis entrain de chercher une meilleure solution pour ne pas avoir à le faire chaque année.
Surtout vu qu'on va enlever moment, il faudra surtout préciser dans le ticket de bien faire attention à ce problème de holidays

2021-01-04 15:37 UTC, sophiemoustard requested changes

2021-01-04 15:37 UTC, sophiemoustard commented on src/extensions/moment.js
> +  ...holidays.getHolidays(currentYear - 2),
je pense que ce n'est pas la bonne solution pour corriger le probleme de tests unitaires qui plantent car l'année prochaine on aura le meme souci

2021-01-04 15:37 UTC, sophiemoustard commented on src/extensions/moment.js
> +  ...holidays.getHolidays(currentYear - 2),
soit on gere ces tests la sur 2022 et comme ca on repousse le probleme a 2024

2021-01-04 15:37 UTC, sophiemoustard commented on src/extensions/moment.js
> +  ...holidays.getHolidays(currentYear - 2),
soit on arrive a s'affranchir de fixer la date

2021-01-04 15:38 UTC, sophiemoustard commented on src/extensions/moment.js
> +  ...holidays.getHolidays(currentYear - 2),
car en fait la tu alourdis le serveur de l'app pour gerer une histoire de test c'est dommage

2021-01-05 07:59 UTC, sophiemoustard requested changes

2021-01-05 07:59 UTC, sophiemoustard commented on src/extensions/moment.js
> +  ...holidays.getHolidays(2022),
tu ne peux pas faire ca car c'est imports sont utilisés dans le code avant d'etre utilisé dans les tests - coder ainsi nous forcerai a  faire une maj du code chaque année pour que ca fonctionne et c'est dommage

Pour t'aider a comprendre, importer les `holidays` nous permet de gerer les jours fériés dans le planning, la paie et la facturation.
On importe donc ceux de l'année en cours pour gerer le travail courant.
On importe egalement ceux de l'annee passée pour qu'en janvier on ait toujours un planning / facturation / paie correct pour decembre dernier.
Et de meme on importe ceux de l'année d'apres pour qu'en decembre on puisse travailler sur le planning de janvier / février / mars avec des données correctes.

ON n'importe pas les autres années car ce ne serait pas tres utile a premiere vue : personne en 2019 ne va bosser sur le planning previsionnel de 2021 par exemple

2021-01-05 07:59 UTC, sophiemoustard commented on src/extensions/moment.js
> +  ...holidays.getHolidays(2022),
le probleme qu'on a aujourd'hui est dans les tests donc il faut corriger les tests et ne pas toucher a ce code la

2021-01-05 08:17 UTC, sophiemoustard commented on src/extensions/moment.js
> +  ...holidays.getHolidays(2022),
`getHoursFromDailyAbsence` : tu peux passer l'année des dates en 2022
`getSurchargeSplit`: idem
`getMatchingFunding` : idem a priori
`getEventSurcharges`: idem
`getDaysRatioBetweenTwoDates`: idem

2021-01-05 10:39 UTC, KennyCallegari commented on tests/unit/helpers/utils.test.js
> -    const end = new Date('2019/05/09');
le 08 mai est un dimanche en 2022 donc il n'est pas considéré comme un `holiday` mais un `sunday`

2021-01-05 11:29 UTC, sophiemoustard commented on tests/unit/helpers/utils.test.js
> -    const end = new Date('2019/05/09');
tu peux faire le test avec un autre jour ferie du coup

2021-01-05 12:55 UTC, KennyCallegari commented on tests/unit/helpers/utils.test.js
> -    const end = new Date('2019/05/09');
c'est ce que j'ai fait 😄

2021-01-05 15:28 UTC, KennyCallegari reviewed
Pour les tests d'intégration. Le problème vient du fait qu'on ne calcule plus les `holidaysHours` ce qui vient modifier certain résultats pour les `hoursToWork`.
J'ai préféré modifier le quelques paramètres affecté plutôt que de changer les dates pour 2 raisons :
- ça évitera qu'on doivent le refaire en 2024
- ça m'évite de changer plein de tests (puisqu'il faut modifier les seeds)
- on le fait pour 2018. Par exemple, `oldSectorResult` (dans les pay tests) se base sur les jours fériés de 2018, qui ne sont plus calculés

2021-01-06 15:25 UTC, KennyCallegari commented on src/helpers/draftPay.js
>    const contract = auxiliary.contracts.find(cont => !cont.endDate || moment(cont.endDate).isAfter(query.endDate));
pourquoi avoir supprimé cette partie ?

2021-01-06 17:09 UTC, sophiemoustard commented on src/helpers/draftPay.js
>    const contract = auxiliary.contracts.find(cont => !cont.endDate || moment(cont.endDate).isAfter(query.endDate));
car en fait ce n'est pas pertinent et pas utilisé ^^

2021-01-06 17:37 UTC, KennyCallegari reviewed
✅

2021-01-06 19:06 UTC, cmolle commented on src/helpers/draftPay.js
> -
Je ne suis pas sure de bien comprendre cette partie, mais ca n'a pas pu engendrer des erreurs si la paie etait validee avant la fin du mois ? (du coup query.endDate est apres le debut du mois en cours et la diff n'est pas calculee ? )

2021-01-06 19:06 UTC, cmolle commented on tests/integration/pay.test.js
> +        url: `/pay/hours-to-work?sector=${sectorFromOtherCompany._id}&month=12-2021`,
Tu ne mets pas 2022 ici aussi ?

2021-01-06 19:06 UTC, cmolle commented on tests/integration/pay.test.js
> +          url: `/pay/hours-to-work?sector=${sectors[0]._id}&month=12-2021`,
idem

2021-01-06 19:06 UTC, cmolle commented on tests/integration/seed/paySeed.js
> +  createdAt: '2021-12-04T16:34:04',
idem

2021-01-07 08:02 UTC, sophiemoustard commented on src/helpers/draftPay.js
> -
je t'avoue que je me suis posé la meme question et en fait le `query` la correspond au query pour le mois precedent donc la query qu'on envoie du front moins 1 mois donc pas de souci sur les paie

2021-01-07 08:04 UTC, sophiemoustard commented on tests/integration/pay.test.js
> +        url: `/pay/hours-to-work?sector=${sectorFromOtherCompany._id}&month=12-2021`,
je trouvais ca plus simple de passer tous les 2018 > 2021 et 2019 > 2022 c'etait plus simple et sur ... 🤔

2021-01-07 08:05 UTC, cmolle approved these changes

2021-01-07 08:06 UTC, sophiemoustard approved these changes

2021-01-07 08:06 UTC, merged