Com 1747
sophiemoustard/alenvi-api pull request #1236
Opened 2021-01-12 14:36 UTC by cmolle

- [x] Mon code est testé unitairement
- [ ] Mon code est testé avec des tests d'intégration - np

- Périmetre interface : client

- Périmetre roles : auxiliaire/coach/admin

- Cas d'usage : Sur le tableau de bord, je vois le compteur 
Trois cas: 
- mois passés: verifier que la valeur correspond a celle de la paie enregistre en bdd
- mois en cours: le compteur doit correspondre a ce qu'il y a sur la page de la paie
- mois suivant: le compteur ne doit pas s'afficher

Vous pouvez egalement verifier les autres valeurs (doit etre coherent avec le planning) car j'ai fait quelques changements a ce niveau la egalement. 

Note: dans les tests unitaires, pour eviter que ce soit trop verbeux, j'ai enleve les 'callwithexactly' lorsque cela ne me paraissait pas pertinent (test similaire a un autre avec un petit changement n'impliquant pas les valeurs passées a d'autres fonctions). Dites moi ce que vous en pensez :)

2021-01-12 17:52 UTC, sophiemoustard requested changes

2021-01-12 17:52 UTC, sophiemoustard commented on src/helpers/pay.js
>      companyId
j'ai l'impression que cet appel peut etre fait bien plus bas dans la methode car le resultata n'est utilisé que pour `computeAuxiliaryDraftPay` non ?

2021-01-12 17:52 UTC, sophiemoustard commented on src/helpers/pay.js
>      companyId
aussi pour plus de lisibilité, que penses tu de le formatter 
```
const auxiliaryEvents =
    await EventRepository.getEventsToPay(startDate, endDate, [new ObjectID(auxiliaryId)], companyId);
```

2021-01-12 17:52 UTC, sophiemoustard commented on src/helpers/pay.js
> +  const sectorsId = [...new Set(sectors.map(sh => sh.sector.toHexString()))];
pour plus de lisiblité tu pourrais le mettre dans une autre methode ?

2021-01-12 17:52 UTC, sophiemoustard commented on src/helpers/pay.js
> +  return draft ? { ...draft, sectors: sectorsId, counterAndDiffRelevant: !!prevPay || firstMonthContract } : null;
tu peux passer une ligne

2021-01-12 18:05 UTC, sophiemoustard commented
vu ensemble, a t on besoin de sectors sur paid-interventions ?

2021-01-13 13:12 UTC, cmolle commented on src/helpers/pay.js
>      companyId
Done !

2021-01-13 13:12 UTC, cmolle commented on src/helpers/pay.js
> +  const sectorsId = [...new Set(sectors.map(sh => sh.sector.toHexString()))];
Done !

2021-01-13 13:12 UTC, cmolle commented on src/helpers/pay.js
> +  return draft ? { ...draft, sectors: sectorsId, counterAndDiffRelevant: !!prevPay || firstMonthContract } : null;
Done !

2021-01-13 13:25 UTC, felix-commits commented on src/helpers/pay.js
> +  const firstMonthContract = moment(startDate).startOf('month').isSameOrBefore(contract.startDate);
comme plus haut tu peux ecrire `.startOf('M')` ? ou ce n'est pas la même chose?

2021-01-13 13:32 UTC, KennyCallegari reviewed
vu
(je ne comprends pas assez bien pour valider que c'est la meilleure méthode mais au moins le code est bon et je comprends le fonctionnement)

2021-01-13 17:04 UTC, sophiemoustard approved these changes

2021-01-13 18:36 UTC, felix-commits approved these changes

2021-01-13 18:36 UTC, felix-commits commented on src/helpers/sectorHistories.js
> +  return [...new Set(sectors.map(sh => sh.sector.toHexString()))];
très chouette ce condensé

2021-01-14 07:37 UTC, merged