COM-1771: ⚠️ NE PAS MERGÉ TANT QUE L'APPLI N'A PAS ÉTÉ PUBLIÉE SUR LES STORES !!!!!
sophiemoustard/alenvi-api pull request #1246
Opened 2021-01-15 10:51 UTC by ulysseferreira

- [x] Mon code est testé unitairement
- [x] Mon code est testé avec des tests d'intégration

- Périmetre interface : mobile

- Périmetre roles : tous 

- Cas d'usage : si on reçoit API version, on renvoie false, suppression de firstMobileConnection au moment de la création car c’est maintenant géré par la route d’authentification

⚠️ NE PAS MERGÉ TANT QUE L'APPLI N'A PAS ÉTÉ PUBLIÉE SUR LES STORES !!!!!

2021-01-15 12:16 UTC, cmolle commented on src/helpers/version.js
> +  if (version.apiVersion) return false;
return true non ? Si le mobile nous envoie une apiVersion on veut que l'utilisateur mette a jour son app, c'est bien ca ?

2021-01-15 12:52 UTC, sophiemoustard requested changes

2021-01-15 12:52 UTC, sophiemoustard commented on src/helpers/users.js
> +    return User.create(payload);
tu n'as plus besoin de la distinction du coup

2021-01-15 13:51 UTC, ulysseferreira commented on src/helpers/version.js
> +  if (version.apiVersion) return false;
done

2021-01-15 13:51 UTC, ulysseferreira commented on src/helpers/users.js
> +    return User.create(payload);
done

2021-01-15 15:02 UTC, cmolle commented on tests/integration/version.test.js
> +      expect(response.result.data.mustUpdate).toBeTruthy();
Tu peux changer le titre du test ?

2021-01-15 15:02 UTC, cmolle commented on tests/unit/helpers/version.test.js
> +    expect(result).toBeTruthy();
idem

2021-01-15 15:07 UTC, ulysseferreira commented on tests/integration/version.test.js
> +      expect(response.result.data.mustUpdate).toBeTruthy();
done

2021-01-15 15:07 UTC, ulysseferreira commented on tests/unit/helpers/version.test.js
> +    expect(result).toBeTruthy();
done

2021-01-15 15:33 UTC, cmolle commented on src/helpers/users.js
> +  if (!credentials) return User.create(payload);
Est-ce qu'on a besoin de origin du coup sur cette route ? (Je ne sais pas si il faut l'enlever maintenant parce que ca a des impact cote webapp, mais si ce n'est plus utile c'est interesant de le noter)

2021-01-18 14:23 UTC, cmolle approved these changes

2021-01-18 14:38 UTC, sophiemoustard approved these changes

2021-01-19 10:11 UTC, merged