COM-1806: return description and learningGoals
sophiemoustard/alenvi-api pull request #1256
Opened 2021-01-20 09:13 UTC by ulysseferreira

- [x] Mon code est testé unitairement
- [ ] Mon code est testé avec des tests d'intégration -np

- Périmetre interface : mobile

- Périmetre roles : tous

- Cas d'usage : envoi de description et objectifs pédagogiques dans la route courses

2021-01-20 18:41 UTC, sophiemoustard requested changes

2021-01-20 18:41 UTC, sophiemoustard commented on tests/unit/helpers/courses.test.js
> +          { path: 'program', select: 'name image description learningGoals' },
peux tu transformer ces tests en utilisant le nouveau SinonMongoose ? #boyscoot ;)

2021-01-21 09:48 UTC, ulysseferreira commented on tests/unit/helpers/courses.test.js
> +          { path: 'program', select: 'name image description learningGoals' },
done

2021-01-21 10:57 UTC, sophiemoustard commented on tests/unit/helpers/courses.test.js
> +    courseFindOne.returns(SinonMongoose.stubChainedQueries([course], ['populate', 'populate', 'select', 'lean']));
tu n'as besoin que d'un populate

2021-01-21 11:43 UTC, ulysseferreira commented on tests/unit/helpers/courses.test.js
> +    courseFindOne.returns(SinonMongoose.stubChainedQueries([course], ['populate', 'populate', 'select', 'lean']));
done

2021-01-21 11:49 UTC, sophiemoustard approved these changes

2021-01-21 16:15 UTC, cmolle approved these changes

2021-01-22 09:28 UTC, merged