Com 1831
sophiemoustard/alenvi-api pull request #1257
Opened 2021-01-20 09:56 UTC by cmolle

- [x] Mon code est testé unitairement
- [ ] Mon code est testé avec des tests d'intégration -np

- Périmetre interface : client

- Périmetre roles : coach/auxiliaire

- Cas d'usage : 
Verifier que l'edition des evenements/repetitions fonctionne toujours
Essayer de lancer le script des repetitions avec postman pour un jour avec des repetitions qui ne fonctionnaient pas (ex: 15/01/2021), il ne faut pas avoir de repetition dans l'array d'erreurs
Lorsque l'on supprime l'adresse d'une repetition elle est bien supprimee, (et non laisse a {}), si on met a jour l'auxiliaire, le secteur disparait et inversement. 

Ce qui n'est pas fait dans cette pr: 
- mutualisation d'une fonction pour lors de la creation d'un evenement gerer le cas ou l'evenement est en conflit et ou on passe l'evenement en 'a affecter' (mutualisation entre events et eventRepetition)
- maj des tests unitaires de `createEvent` suite au changement de la fonction isRepetition. Comme la prochaine pr touchera a ces tests et qu'il y a plusieurs tests a revoir, j'ai prefere ne pas les mettre a jour dans cette pr.

2021-01-20 14:44 UTC, KennyCallegari commented on src/helpers/events.js
> +exports.isRepetition = event =>
Pourquoi en avoir fait l'export ?

2021-01-20 15:10 UTC, sophiemoustard requested changes

2021-01-20 15:10 UTC, sophiemoustard commented on src/helpers/eventsRepetition.js
>      }
on pourrait simplifier comme suit qu'en penses tu ?

```
    const detachFromRepetition = eventPayload.auxiliary && eventFromDb.type === INTERVENTION && hasConflicts;
    if (!eventPayload.auxiliary) eventToSet = { ...omit(eventToSet, 'auxiliary'), sector: sectorId };

```

2021-01-20 15:35 UTC, cmolle commented on src/helpers/events.js
> +exports.isRepetition = event =>
Il me semble qu'elle est utilisee dans createEvent et updateEvent mais n'etait pas testée. Je me suis dit qu'on pouvait la tester et du coup je l'ai exporté.

2021-01-20 15:36 UTC, cmolle commented on src/helpers/events.js
> +    const payload = exports.formatEditionPayload(event, eventPayload, exports.isRepetition(event) && !miscUpdatedOnly);
Done !

2021-01-20 15:38 UTC, cmolle commented on tests/unit/helpers/repetitions.test.js
> +    RepetitionMock = sinon.mock(Repetition);
Je me suis trompée, c'est corrigé :)

2021-01-20 15:45 UTC, cmolle commented on src/helpers/events.js
> +  !!event.repetition && !!event.repetition.frequency && event.repetition.frequency !== NEVER;
Done !

2021-01-20 15:48 UTC, cmolle commented on src/helpers/eventsRepetition.js
>      }
Done ! J'ai mis `detachFromRepetition || !eventPayload.auxiliary` dans la condition du if

2021-01-21 10:58 UTC, KennyCallegari approved these changes

2021-01-21 11:03 UTC, sophiemoustard commented on src/helpers/events.js
> +  !!has(event, 'repetition.frequency') && get(event, 'repetition.frequency') !== NEVER;
as tu besoin du !! devant ?

2021-01-21 11:05 UTC, sophiemoustard commented on tests/unit/helpers/events.test.js
> +  it('should update event when misc is updates among other fields', async () => {
updated

2021-01-21 11:05 UTC, sophiemoustard commented on tests/unit/helpers/events.test.js
> +  it('should update event when misc is updates among other fields', async () => {
en dessous aussi

2021-01-21 11:06 UTC, sophiemoustard commented on tests/unit/helpers/events.test.js
> +  it('should update event when misc is updates among other fields', async () => {
tu pourrais ajouter "and event is a repetition" pour comparer avec celui d'en dessous

2021-01-21 11:20 UTC, cmolle commented on src/helpers/events.js
> +  !!has(event, 'repetition.frequency') && get(event, 'repetition.frequency') !== NEVER;
Ca permet de toujours envoyer un boolean et de ne pas renvoyer undefined/null

2021-01-21 11:31 UTC, cmolle commented on src/helpers/events.js
> +  !!has(event, 'repetition.frequency') && get(event, 'repetition.frequency') !== NEVER;
Tu as raison on n'en a plus besoin depuis qu'on utilise has, bien vu !

2021-01-21 11:59 UTC, sophiemoustard approved these changes

2021-01-21 12:10 UTC, merged