COM-1813: code verification if forgot password
sophiemoustard/alenvi-api pull request #1261
Opened 2021-01-20 16:47 UTC by ulysseferreira

- [x] Mon code est testé unitairement
- [x] Mon code est testé avec des tests d'intégration

- Périmetre interface : mobile

- Périmetre roles : tous

- Cas d'usage :
lorsque je fais mot de passe oublié je reçoit un code par mail pour vérifier mon identité (PR1 : la PR s'arrête avec le mail reçu, je ne peux pas encore le rentrer dans l'appli)

2021-01-20 17:19 UTC, cmolle commented on src/helpers/authentication.js
> +      verificationCode: Math.floor(Math.random() * Math.floor(10000)),
Pourquoi as-tu besoin de Math.floor devant le 10000 ?

2021-01-20 17:19 UTC, cmolle commented on src/helpers/authentication.js
> +      creationDate: Date.now(),
Est-ce qu'on pourrait utiliser createdAt qui est mis automatiquement par mongoose ?

2021-01-20 17:19 UTC, cmolle commented on src/models/IdentityVerification.js
> +const IdentityVerificationSchema = mongoose.Schema({
Certains champs sont-ils required ?

2021-01-20 17:19 UTC, cmolle commented on src/models/User.js
> +const TYPE_OPTIONS = [EMAIL, PHONE];
Ici on n'a pas besoin du type_options dans le model user, si ? Il vaut mieux le definir la ou tu en as besoin je pense.

2021-01-20 17:19 UTC, cmolle commented on src/routes/authentication.js
> +        ],
sur une ligne

2021-01-20 17:19 UTC, cmolle commented on src/routes/preHandlers/users.js
> +};
Pas besoin du prehandler ici, tu peux le faire en validation directement avec Joi. Tu as des examples d'utilisation de `when` sur la route PUT/_id des contrats

2021-01-20 17:19 UTC, cmolle commented on tests/integration/authentication.test.js
> +  it('should send a code verification by email if origin mobile and type email', async () => {
Il faut que tu ajoutes un test dans le cas ou tu as origin mobile et type indefini ou invalide

2021-01-20 17:20 UTC, cmolle commented on src/helpers/authentication.js
> +      creationDate: Date.now(),
(il faut ajouter timestamps: true dans le model)

2021-01-20 18:16 UTC, sophiemoustard requested changes

2021-01-20 18:16 UTC, sophiemoustard commented on src/helpers/authentication.js
> +    return EmailHelper.verificationCodeEmail(email, verification.verificationCode);
passe une ligne avant le return

2021-01-20 18:16 UTC, sophiemoustard commented on src/routes/authentication.js
> +            type: Joi.string().valid(...TYPE_OPTIONS),
tu peux mettre directement PHONE, EMAIL

2021-01-20 18:16 UTC, sophiemoustard commented on src/routes/authentication.js
> +            type: Joi.string().valid(...TYPE_OPTIONS),
tu peux mettre un 
```
.when('origin', { is: MOBILE, then: Joi.required() }),
```
et comme ca tu n'as pas besoin du preHandler

2021-01-20 18:16 UTC, sophiemoustard commented on tests/integration/authentication.test.js
> +    );
sur une ligne

2021-01-20 18:16 UTC, sophiemoustard commented on tests/unit/helpers/authentication.test.js
>    it('should return a new access token after checking reset password token', async () => {
tu peux verifier que les methode pour mobile ne sont pas appelée

2021-01-20 18:16 UTC, sophiemoustard commented on src/models/IdentityVerification.js
> +// User schema
a enlever

2021-01-20 18:16 UTC, sophiemoustard commented on src/helpers/authentication.js
> +      verificationCode: Math.floor(Math.random() * Math.floor(10000)),
tu pourrais mettre juste `code` puisque tu es dnans le model `IdentityVerification` on se doute que tu verifies quelque chose avec ce code :)

2021-01-21 10:53 UTC, ulysseferreira commented on src/helpers/authentication.js
> +      verificationCode: Math.floor(Math.random() * Math.floor(10000)),
done

2021-01-21 10:57 UTC, ulysseferreira commented on src/helpers/authentication.js
> +      creationDate: Date.now(),
done

2021-01-21 10:57 UTC, ulysseferreira commented on src/models/IdentityVerification.js
> +const IdentityVerificationSchema = mongoose.Schema({
done

2021-01-21 11:03 UTC, ulysseferreira commented on src/models/User.js
> +const TYPE_OPTIONS = [EMAIL, PHONE];
done

2021-01-21 11:04 UTC, ulysseferreira commented on src/routes/authentication.js
> +        ],
done

2021-01-21 11:08 UTC, ulysseferreira commented on src/routes/preHandlers/users.js
> +};
done

2021-01-21 11:11 UTC, ulysseferreira commented on tests/integration/authentication.test.js
> +  it('should send a code verification by email if origin mobile and type email', async () => {
done

2021-01-21 11:12 UTC, ulysseferreira commented on src/helpers/authentication.js
> +    return EmailHelper.verificationCodeEmail(email, verification.verificationCode);
done

2021-01-21 11:14 UTC, ulysseferreira commented on src/routes/authentication.js
> +            type: Joi.string().valid(...TYPE_OPTIONS),
done

2021-01-21 11:14 UTC, ulysseferreira commented on src/routes/authentication.js
> +            type: Joi.string().valid(...TYPE_OPTIONS),
done

2021-01-21 11:15 UTC, ulysseferreira commented on tests/integration/authentication.test.js
> +    );
done

2021-01-21 11:18 UTC, ulysseferreira commented on tests/unit/helpers/authentication.test.js
>    it('should return a new access token after checking reset password token', async () => {
done

2021-01-21 11:18 UTC, ulysseferreira commented on src/models/IdentityVerification.js
> +// User schema
done

2021-01-21 11:21 UTC, ulysseferreira commented on src/helpers/authentication.js
> +      verificationCode: Math.floor(Math.random() * Math.floor(10000)),
done

2021-01-21 11:36 UTC, cmolle commented on src/helpers/authentication.js
> +      creationDate: Date.now(),
Je proposais d'utiliser le createdAt que mongoose met automatiquement quand tu ajoutes l'options timestamps au modele. Comme ca pas besoin de le mettre ici

2021-01-21 11:38 UTC, cmolle commented on src/helpers/authentication.js
> +      creationDate: Date.now(),
Enfait mongoose propose directement d'ajouter createdAt et updatedAt aux modeles. On ajoute toujours cette options (qu'il faut mettre dans le modele avec timestamps:true) car elle est tres pratique notamment quand il y a des bugs. 
Ici en l'ajoutant au modele, tu pourras utiliser ce champs directement et donc tu n'auras pas besoin de le creer a la main :)

2021-01-21 11:40 UTC, cmolle commented on src/routes/authentication.js
> +            type: Joi.string().valid(...PHONE, EMAIL)
Pas besoin des '...' si ?

2021-01-21 11:55 UTC, sophiemoustard commented on tests/integration/authentication.test.js
> +  it('should return 400 if origin mobile and no type', async () => {
il manque une ligne

2021-01-21 14:02 UTC, ulysseferreira commented on src/helpers/authentication.js
> +      creationDate: Date.now(),
done

2021-01-21 14:03 UTC, ulysseferreira commented on tests/integration/authentication.test.js
> +  it('should return 400 if origin mobile and no type', async () => {
done

2021-01-21 16:57 UTC, cmolle approved these changes

2021-01-21 17:14 UTC, sophiemoustard requested changes

2021-01-21 17:14 UTC, sophiemoustard commented on src/helpers/authentication.js
> +      createdAt: Date.now(),
tu n'as pas besoin de ce createdAt du coup il est mis automatiquement grace a l'option `timestamp` que tu passes dans le model

2021-01-21 17:14 UTC, sophiemoustard commented on src/helpers/authentication.js
> +      createdAt: Date.now(),
et du coup tu peux le mettre sur une ligne

2021-01-21 17:14 UTC, sophiemoustard commented on tests/unit/helpers/authentication.test.js
> +  let creationDate;
et du coup tu n'as plus besoin de ca dans les tests

2021-01-21 18:09 UTC, ulysseferreira commented on src/helpers/authentication.js
> +      createdAt: Date.now(),
done

2021-01-21 18:10 UTC, ulysseferreira commented on tests/unit/helpers/authentication.test.js
> +  let creationDate;
done

2021-01-21 18:15 UTC, sophiemoustard approved these changes

2021-01-21 18:51 UTC, merged