Com 1831 create
sophiemoustard/alenvi-api pull request #1263
Opened 2021-01-22 11:39 UTC by cmolle

- [x] Mon code est testé unitairement
- [ ] Mon code est testé avec des tests d'intégration -np

- Périmetre interface : client

- Périmetre roles : auxiliaire/coach

- Cas d'usage : mutualisation d'une fonction pour detacher un evenement d'une auxiliaire lors de sa creation en cas de conflit
J'ai aussi renommer `event` dans la methode de creation d'evenement pour avoir des constantes plus claires.

2021-01-22 13:43 UTC, KennyCallegari approved these changes

2021-01-22 13:56 UTC, sophiemoustard requested changes

2021-01-22 13:56 UTC, sophiemoustard commented on src/helpers/events.js
> +};
que penses tu de ce formatage ? 
```
const auxiliary = await User.findOne({ _id: event.auxiliary })
    .populate({ path: 'sector', select: '_id sector', match: { company: companyId } })
    .lean({ autopopulate: true, virtuals: true });

  return {
    ...omit(event, 'auxiliary'),
    sector: auxiliary.sector,
    repetition: { ...event.repetition, frequency: NEVER },
  };
```

2021-01-22 13:56 UTC, sophiemoustard commented on tests/unit/helpers/events.test.js
> +  it('should detach auxiliary as event is a repeted intervention with conflicts', async () => {
il manque un a

2021-01-25 08:00 UTC, sophiemoustard requested changes

2021-01-25 08:00 UTC, sophiemoustard commented on src/helpers/events.js
> +    repetition: { frequency: NEVER },
je crois qu'on enleve pas le parent id dans repetition
donc il vaut mieux mettre `repetition: { ...event.repetition, frequency: NEVER }

2021-01-25 08:17 UTC, sophiemoustard approved these changes

2021-01-25 09:17 UTC, merged