Com 1813 2
sophiemoustard/alenvi-api pull request #1267
Opened 2021-01-25 16:21 UTC by ulysseferreira

- [x] Mon code est testé unitairement
- [x] Mon code est testé avec des tests d'intégration

- Périmetre interface : mobile

- Périmetre roles : tous

- Cas d'usage : lorsque j'ai oublié mon mot de passe je peux directement le récupérer depuis l'application grâce à un code envoyé par email

2021-01-25 16:47 UTC, cmolle commented on src/controllers/authenticationController.js
> -
Tu peux laisser cette ligne, non ?

2021-01-25 16:47 UTC, cmolle commented on src/helpers/authentication.js
> +    const code = await IdentityVerification.findOne({ email, code: Number(token) })
Est-ce qu'il ne faudrait pas plutot que code soit un string ?

2021-01-25 16:47 UTC, cmolle commented on src/helpers/authentication.js
> +      .lean({ virtuals: true, autopopulate: true });
As quoi te servent le virtuals et autopopulate ?

2021-01-25 16:47 UTC, cmolle commented on src/helpers/authentication.js
> +      const payload = { _id: user._id, email: user.local.email };
Tu peux passer une ligne apres le throw Boom.notFOund

2021-01-25 16:47 UTC, cmolle commented on src/helpers/authentication.js
> +    throw Boom.unauthorized();
Comment pourrais-tu mettre en commun cette partie avec celle du dessous pour eviter de dupliquer ?

2021-01-25 16:47 UTC, cmolle commented on src/helpers/authentication.js
> +    const code = Math.floor(Math.random() * (10000 - 1000 + 1) + 1000);
Pourquoi ce changement dans le calcul ?

2021-01-25 17:40 UTC, sophiemoustard requested changes
Pense a plus aerer ton code :)

2021-01-25 17:40 UTC, sophiemoustard commented on src/helpers/authentication.js
> +    if (timeElapsed < 3600) {
mets en constante 3600 pour que ce soit plus clair

2021-01-25 17:40 UTC, sophiemoustard commented on src/helpers/authentication.js
> +      const user = await User.findOne({ 'local.email': email }).lean();
tu peux ajouter un deuxieme argument a ton findOne pour ne recuperer que local.email de ton user car tu n'as besoin que de ca et pas toutes les autres données (_id est par defaut)

2021-01-25 17:40 UTC, sophiemoustard commented on src/helpers/authentication.js
> +      return { token: exports.encode(userPayload, expireTime), user: userPayload };
tu peux passser une ligne avant le return

2021-01-25 17:40 UTC, sophiemoustard commented on src/helpers/authentication.js
> +      const expireTime = 86400;
tu as une constante pour ca dnas le model User

2021-01-25 17:40 UTC, sophiemoustard commented on tests/unit/helpers/authentication.test.js
> +    UserfindOne = sinon.stub(User, 'findOne');
pas de majuscule

2021-01-25 17:40 UTC, sophiemoustard commented on tests/unit/helpers/authentication.test.js
> +    IdentityVerificationFindOne = sinon.stub(IdentityVerification, 'findOne');
idem

2021-01-25 17:40 UTC, sophiemoustard commented on src/helpers/authentication.js
> +    throw Boom.unauthorized();
pour que ce soit plus clair, tu peux directement gerer ce cas en faisant 
`if (timeElapsed > 3600) throw....`
et ensuite du découle le reste

c'est mieux de gerer en premier le cas simple / rapide puis de detailler le reste. garde ca en memoire pour tes prochaines dev et au besoin on en reparle

2021-01-25 17:40 UTC, sophiemoustard commented on src/helpers/authentication.js
> +    const timeElapsed = (Date.now() - code.updatedAt) / 1000;
passe une ligen avant

2021-01-26 12:00 UTC, ulysseferreira commented on src/controllers/authenticationController.js
> -
done

2021-01-26 12:07 UTC, ulysseferreira commented on src/helpers/authentication.js
> +    const code = await IdentityVerification.findOne({ email, code: Number(token) })
done

2021-01-26 14:00 UTC, ulysseferreira commented on src/helpers/authentication.js
> +      .lean({ virtuals: true, autopopulate: true });
done

2021-01-26 14:01 UTC, ulysseferreira commented on src/helpers/authentication.js
> +      const payload = { _id: user._id, email: user.local.email };
done

2021-01-26 14:02 UTC, ulysseferreira commented on src/helpers/authentication.js
> +    const code = Math.floor(Math.random() * (10000 - 1000 + 1) + 1000);
parce qu'on renvoyait un nombre entre 0 et 10000 hors on veut un nombre entre 1000 et 10000 (pour qu'il ait 4 chiffres)

2021-01-26 14:04 UTC, ulysseferreira commented on src/helpers/authentication.js
> +    if (timeElapsed < 3600) {
done

2021-01-26 14:43 UTC, ulysseferreira commented on src/helpers/authentication.js
> +    throw Boom.unauthorized();
done

2021-01-26 14:52 UTC, ulysseferreira commented on src/helpers/authentication.js
> +      const user = await User.findOne({ 'local.email': email }).lean();
done

2021-01-26 14:52 UTC, ulysseferreira commented on src/helpers/authentication.js
> +      return { token: exports.encode(userPayload, expireTime), user: userPayload };
done

2021-01-26 14:53 UTC, ulysseferreira commented on src/helpers/authentication.js
> +      const expireTime = 86400;
done

2021-01-26 14:55 UTC, ulysseferreira commented on tests/unit/helpers/authentication.test.js
> +    UserfindOne = sinon.stub(User, 'findOne');
done

2021-01-26 14:58 UTC, ulysseferreira commented on tests/unit/helpers/authentication.test.js
> +    IdentityVerificationFindOne = sinon.stub(IdentityVerification, 'findOne');
done

2021-01-26 15:04 UTC, ulysseferreira commented on src/helpers/authentication.js
> +    throw Boom.unauthorized();
d'acc ça marche :)

2021-01-26 15:05 UTC, ulysseferreira commented on src/helpers/authentication.js
> +    const timeElapsed = (Date.now() - code.updatedAt) / 1000;
done

2021-01-26 16:18 UTC, sophiemoustard approved these changes

2021-01-27 09:35 UTC, cmolle commented on src/helpers/authentication.js
> +    const code = String(Math.floor(Math.random() * (10000 - 1000 + 1) + 1000));
Est-ce que tu peux mettre directement le resultat du calcul 10000 - 1000 + 1 ?

2021-01-27 09:39 UTC, ulysseferreira commented on src/helpers/authentication.js
> +    const code = String(Math.floor(Math.random() * (10000 - 1000 + 1) + 1000));
done

2021-01-27 10:04 UTC, cmolle commented on src/helpers/authentication.js
> +    const code = String(Math.floor(Math.random() * 9001 + 1000));
Je pense que c'est 9000 et pas 9001. Ici ils ne disent pas max - min + 1 contrairement au lien que tu m'avais montre hier: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Math/random
Comme random renvoie un nombre entre 0 et 1 exclus, si on met 9000 on aura un nombre entre 0 et 8999 -> donc entre 1000 et 9999. Ici on va avoir un nombre entre 0 et 9000 -> donc entre 1000 et 10000.

2021-01-27 10:07 UTC, ulysseferreira commented on src/helpers/authentication.js
> +    const code = String(Math.floor(Math.random() * 9001 + 1000));
done

2021-01-27 10:17 UTC, cmolle approved these changes

2021-01-27 12:56 UTC, merged