COM-1848: add isMandatory to card model and add prehandler
sophiemoustard/alenvi-api pull request #1282
Opened 2021-02-02 15:15 UTC by ulysseferreira

- [ ] Mon code est testé unitairement -np
- [x] Mon code est testé avec des tests d'intégration

- Périmetre interface : vendeur 

- Périmetre roles : ROF

- Cas d'usage :  je peux indiquer à l'aide d'une checkbox si la réponse à une carte de type questionnaire est obligatoire ou non

2021-02-02 16:24 UTC, cmolle commented on src/routes/cards.js
> +            isMandatory: Joi.boolean(),
Comme l'a indique felix sur ton autre pr tu peux faire la condition ici plutot que dans le prehandler

2021-02-02 16:24 UTC, cmolle commented on tests/integration/cards.test.js
> +    it('should return a 403 when provide a useless isMandatory field on a non-Questionnaire card', async () => {
idem que mon commentaire sur ton autre pr

2021-02-02 17:01 UTC, sophiemoustard requested changes

2021-02-02 17:01 UTC, sophiemoustard commented on src/routes/preHandlers/cards.js
> +  req.payload.isMandatory !== undefined) throw Boom.forbidden();
ici tu pourrais utiliser has de lodash `has(req, 'payload.isMandatory')` qui verifie que la clé est presente mais ne regarde pas sa valeur

2021-02-02 17:33 UTC, ulysseferreira commented on src/routes/cards.js
> +            isMandatory: Joi.boolean(),
outdated

2021-02-02 17:35 UTC, ulysseferreira commented on tests/integration/cards.test.js
> +    it('should return a 403 when provide a useless isMandatory field on a non-Questionnaire card', async () => {
done

2021-02-02 17:35 UTC, ulysseferreira commented on tests/integration/cards.test.js
> +    it('should return a 403 when provide a useless isMandatory field on a non-Questionnaire card', async () => {
done

2021-02-02 17:36 UTC, ulysseferreira commented on src/routes/preHandlers/cards.js
> +  req.payload.isMandatory !== undefined) throw Boom.forbidden();
done

2021-02-03 08:17 UTC, cmolle approved these changes

2021-02-03 08:24 UTC, sophiemoustard requested changes

2021-02-03 08:24 UTC, sophiemoustard commented on src/routes/preHandlers/cards.js
> +  has(req, 'payload.isMandatory')) throw Boom.forbidden();
il manque une indentation

2021-02-03 08:24 UTC, sophiemoustard commented on tests/integration/cards.test.js
> +        },
sur une ligne

2021-02-03 08:31 UTC, ulysseferreira commented on src/routes/preHandlers/cards.js
> +  has(req, 'payload.isMandatory')) throw Boom.forbidden();
done

2021-02-03 08:31 UTC, ulysseferreira commented on tests/integration/cards.test.js
> +        },
done

2021-02-03 08:32 UTC, felix-commits approved these changes

2021-02-03 08:36 UTC, sophiemoustard approved these changes

2021-02-03 11:28 UTC, merged