COM-1878 - Allow duplicate name for team of different structure
sophiemoustard/alenvi-api pull request #1296
Opened 2021-02-19 10:54 UTC by KennyCallegari

- [x] Mon code est testé unitairement
- ~~Tests intégrations: (barrer ce qui n'est pas utile)~~
  - ~~Ce n'est pas une ancienne route utilisée par le mobile~~
      - ~~[ ] J'ai bien fait les tests~~
  - ~~C'est une ancienne route utilisée par le mobile~~
    - ~~J'ai changé ce qu'acceptait ou ce que renvoyait la route (noms de champs, format, conditions)~~
      - ~~[ ] J'ai fait de nouveaux tests sans modifier les anciens pour s'assurer que les anciennes versions du mobile
      fonctionnent~~

- [x] Mes changements n'impactent pas une route utilisée par l'autre plateforme (mobile/webapp)
- ~~Mes changements impactent une route utilisée par l'autre plateforme (mobile/webapp):~~
  - ~~[ ] J'ai décrit dans le cas d'usage les choses a tester sur l'autre plateforme~~
  - ~~Je n'ai pas fait de breaking change :~~
    - ~~[ ] Je n'ai pas changé les droits de la route~~
    - ~~[ ] Je n'ai pas changé les droits dans le fichier rights.js~~
    - ~~[ ] Je n'ai pas fait de changement sur le prehandler qui implique le mobile~~
    - ~~[ ] Je n'ai pas changé le type d'un paramètre ou enlevé des valeurs possibles~~
    - ~~Justification des breaking changes s'il y en a:~~
  - ~~J'ai supprimé une route :~~
    - ~~[ ] Les anciennes versions mobiles + l'actuelle ne l'utilise pas~~
  - ~~J'ai renommé une route :~~
    - ~~[ ] La route n'est pas utilisée par le mobile (si la route est utilisée en mobile: ne pas la renommer et plutôt
    créer une nouvelle route utilisée par la WEBAPP et toutes les nouvelles versions mobiles)~~
  - ~~J'ai ajoute un champ possible dans la route :~~
    - ~~[ ] J'ai géré le cas ou on ne l'envoie pas~~
  - ~~J'ai rendu obligatoire un champs de la route :~~
    - ~~[ ] Il est toujours envoyé par le mobile (même par les anciennes versions)~~
  - ~~J'ai retiré un champ possible dans la route :~~
    - ~~[ ] Les anciennes versions mobiles + l'actuelle ne l'envoient pas~~
  - ~~J'ai supprimé un retour/un champs du retour de la route :~~
    - ~~[ ] Les anciennes versions mobiles + l'actuelle n'utilise pas ce retour~~

- ~~J'ai changé un modele :~~
  - ~~J'ai ajoute un champ possible :~~
    - ~~[ ] J'ai géré le cas ou on ne l'envoie pas~~
  - ~~J'ai rendu obligatoire un champs :~~
    - ~~[ ] Il est toujours envoyé par le mobile (même par les anciennes versions)~~
  - ~~J'ai retiré un champ possible :~~
    - ~~[ ] Les anciennes versions mobiles + l'actuelle ne l'envoient pas~~

- [x] Je n'ai pas changé de constante

- Périmetre interface : client

- Périmetre roles : admin

- Cas d'usage : 
Je peux créer une équipe (Config RH > Equipe) ayant le même nom qu'une autre équipe mais d'une autre structure. (Par exemple j'ai pu créer une équipe Lotus dans ma société Kenny Company). Je ne peux pas créer 2 équipes ayant le même nom au sein d'une même structure.
Refacto sinon-mongoose en boyscoot

2021-02-19 11:00 UTC, cmolle commented on src/helpers/sectors.js
>    if (existingSector) throw Boom.conflict(translate[language].sectorAlreadyExists);
Que penses-tu de deplacer cette partie dans un prehandler ? Il me semble qu'on fait plutot ces verifications dans des prehandler maintenant.

2021-02-19 11:08 UTC, cmolle reviewed
Tu peux ajouter un test d'integration pour verifier que tu peux ajouter un secteur qui est deja en base :)

2021-02-19 12:04 UTC, cmolle commented on tests/unit/helpers/sectors.test.js
calledOnceWithExactly ?

2021-02-19 13:49 UTC, KennyCallegari commented on tests/unit/helpers/sectors.test.js
done

2021-02-19 13:49 UTC, KennyCallegari commented on src/helpers/sectors.js
>    if (existingSector) throw Boom.conflict(translate[language].sectorAlreadyExists);
done

2021-02-19 15:29 UTC, ulysseferreira reviewed
je sais pas si c'est très important mais peut-être supprimer les potentiels espaces en fin de saisie quand on créé une équipe parce que je peux créer une équipe "Lotus" et une équipe "Lotus " et visuellement tu vois pas la diff entre les deux équipes

2021-02-19 15:42 UTC, cmolle commented on src/routes/preHandlers/sectors.js
> +exports.authorizeSectorCreation = async (req) => {
Est-ce que tu peux en profiter pour faire une refacto et utiliser ce prehandler egalement pour l'update et supprimer la verification du helper update ? Je me dis que c'est mieux que tout ce fasse au meme endroit

2021-02-19 17:29 UTC, KennyCallegari commented on src/routes/preHandlers/sectors.js
> +exports.authorizeSectorCreation = async (req) => {
done

2021-02-19 17:57 UTC, cmolle commented on tests/integration/sectors.test.js
> +    it('should create company even if sector name already exists in other company', async () => {
should update

2021-02-19 18:14 UTC, sophiemoustard requested changes

2021-02-19 18:14 UTC, sophiemoustard commented on src/routes/preHandlers/sectors.js
>    if (sector.company.toHexString() !== credentials.company._id.toHexString()) throw Boom.forbidden();
peux tu utiliser la methode utilse areObjectIdsEqual ?

2021-02-22 14:05 UTC, KennyCallegari commented on tests/integration/sectors.test.js
> +    it('should create company even if sector name already exists in other company', async () => {
done

2021-02-22 14:06 UTC, KennyCallegari commented on src/routes/preHandlers/sectors.js
>    if (sector.company.toHexString() !== credentials.company._id.toHexString()) throw Boom.forbidden();
done

2021-02-22 14:24 UTC, cmolle approved these changes

2021-02-22 15:07 UTC, ulysseferreira approved these changes

2021-02-22 18:14 UTC, sophiemoustard approved these changes

2021-02-22 18:14 UTC, merged