COM-1925 - Allow client_admin and coach to access attendanceSheets
sophiemoustard/alenvi-api pull request #1327
Opened 2021-03-17 16:46 UTC by KennyCallegari

- [x] Mon code est testé unitairement
- Tests intégrations: (barrer ce qui n'est pas utile)
  - Ce n'est pas une ancienne route utilisée par le mobile
      - [x] J'ai bien fait les tests
  - ~~C'est une ancienne route utilisée par le mobile~~
    - ~~J'ai changé ce qu'acceptait ou ce que renvoyait la route (noms de champs, format, conditions)~~
      - ~~[ ] J'ai fait de nouveaux tests sans modifier les anciens pour s'assurer que les anciennes versions du mobile
      fonctionnent~~

- [ ] J'ai testé que les anciennes versions maintenues de l'application mobile fonctionnent toujours (a minima):
  - [ ] Affichage des pages explorer/mes formations/About/CourseProfile
  - [ ] Inscription a une formation e-learning
  - [ ] Possibilité de faire une activité

- [x] Mes changements n'impactent pas une route utilisée par l'autre plateforme (mobile/webapp)
- ~~Mes changements impactent une route utilisée par l'autre plateforme (mobile/webapp):~~
  - ~~[ ] J'ai décrit dans le cas d'usage les choses a tester sur l'autre plateforme~~
  - ~~Je n'ai pas fait de breaking change :~~
    - ~~[ ] Je n'ai pas changé les droits de la route~~
    - ~~[ ] Je n'ai pas changé les droits dans le fichier rights.js~~
    - ~~[ ] Je n'ai pas fait de changement sur le prehandler qui implique le mobile~~
    - ~~[ ] Je n'ai pas changé le type d'un paramètre ou enlevé des valeurs possibles~~
    - ~~Justification des breaking changes s'il y en a:~~
  - ~~J'ai supprimé une route :~~
    - ~~[ ] Les anciennes versions mobiles + l'actuelle ne l'utilise pas~~
  - ~~J'ai renommé une route :~~
    - ~~[ ] La route n'est pas utilisée par le mobile (si la route est utilisée en mobile: ne pas la renommer et plutôt
    créer une nouvelle route utilisée par la WEBAPP et toutes les nouvelles versions mobiles)~~
  - ~~J'ai ajoute un champ possible dans la route :~~
    - ~~[ ] J'ai géré le cas ou on ne l'envoie pas~~
  - ~~J'ai rendu obligatoire un champs de la route :~~
    - ~~[ ] Il est toujours envoyé par le mobile (même par les anciennes versions)~~
  - ~~J'ai retiré un champ possible dans la route :~~
    - ~~[ ] Les anciennes versions mobiles + l'actuelle ne l'envoient pas~~
  - ~~J'ai supprimé un retour/un champs du retour de la route :~~
    - ~~[ ] Les anciennes versions mobiles + l'actuelle n'utilise pas ce retour~~

- ~~J'ai changé un modele :~~
  - ~~J'ai ajoute un champ possible :~~
    - ~~[ ] J'ai géré le cas ou on ne l'envoie pas~~
  - ~~J'ai rendu obligatoire un champs :~~
    - ~~[ ] Il est toujours envoyé par le mobile (même par les anciennes versions)~~
  - ~~J'ai retiré un champ possible :~~
    - ~~[ ] Les anciennes versions mobiles + l'actuelle ne l'envoient pas~~

- [x] Je n'ai pas changé de constante

- ~~J'ai ajouté une variable d'environnement :~~
  - ~~[ ] J'ai précisé sur le slite de MES et MEP les modifications faites~~

- Périmetre interface : client

- Périmetre roles : coach / client admin / vendor / rof

- Cas d'usage :
J'ai accès à l'onglet 'Suivi des stagiaires' dans la page profil d'une formation mixte intra dans l'interface client.
En tant que coach / client admin, je ne peux pas modifier le tableau de présence ni ajouter/supprimer une fiche de présence.

2021-03-17 17:42 UTC, KennyCallegari commented on tests/unit/helpers/authorization.test.js
> +          'attendancesheets:read',
Je ne comprends pas vraiment pourquoi il y a eu ce changement

2021-03-17 17:45 UTC, KennyCallegari commented on src/routes/preHandlers/attendances.js
> +    const { course } = courseSlots[0];
Je ne test que pour le premier courseSlot en partant du principe que tous les courseSlots ont la même company, qu'en pensez-vous ?

2021-03-17 17:45 UTC, KennyCallegari commented on tests/integration/attendances.test.js
> +    it('should return 403 if user is client_admin and course is intra and not from user company', async () => {
pas sûr que ce test soit utile (déjà compris dans le test du coach ?)

2021-03-18 15:48 UTC, cmolle commented on tests/unit/helpers/authorization.test.js
> +          'attendancesheets:read',
Je pense que c'est parce que avant l'utilisateur avait ce droit grace a vendor_admin et maintenant il l'a grace a client_admin, du coup il est plus haut dans le tableau de droit. (on fait une boucle sur les roles dans le service authorization)

2021-03-18 15:52 UTC, cmolle commented on tests/unit/helpers/authorization.test.js
> +          'attendancesheets:read',
D'ailleurs le test ici suppose que Set conserve toujours la premiere valeur. Ca a l'air d'etre le cas ici vu qu'on a pas trop de soucis, mais a voir si `expect.arrayContaining` ne serait pas plus adapte ici, car je ne crois pas qu'on utilise l'ordre du tableau.

2021-03-18 15:55 UTC, cmolle commented on src/routes/preHandlers/attendances.js
> +    const { course } = courseSlots[0];
Je me souviens qu'on s'etait pas mal pose la question a l'epoque avec les formateurs. Comme on avait decide de verifier tous les creneaux pour les formateurs je ferais pareil ici. Tu en penses quoi ?

2021-03-18 16:30 UTC, KennyCallegari commented on tests/unit/helpers/authorization.test.js
> +          'attendancesheets:read',
`arrayContaining` ne permet pas de savoir si on a ajouté un role au scope. Donc si on ajoute un role, le test ne cassera pas.
Aussi, je ne vois pas comment intégré le test `expect.arrayContaining` dans un test `.toEqual `😄

2021-03-18 16:41 UTC, KennyCallegari commented on src/routes/preHandlers/attendances.js
> +    const { course } = courseSlots[0];
je suis d'accord, done

2021-03-18 16:42 UTC, KennyCallegari commented on tests/integration/attendances.test.js
> +    it('should return 403 if user is client_admin and course is intra and not from user company', async () => {
done

2021-03-18 16:48 UTC, KennyCallegari commented on src/routes/preHandlers/attendances.js
> +      if (!userBelongToCompany) throw Boom.forbidden();
bien vu merci
done

2021-03-18 16:49 UTC, KennyCallegari commented on tests/integration/attendanceSheets.test.js
> +      { name: 'coach', expectedCode: 200 },
done

2021-03-18 16:49 UTC, KennyCallegari commented on tests/integration/attendances.test.js
> +      { name: 'client_admin', expectedCode: 200 },
done

2021-03-18 17:33 UTC, cmolle commented on tests/unit/helpers/authorization.test.js
> +          'attendancesheets:read',
Ha oui tu as raison... 
Tu peux regarder on le fait parfois dans des tests le arrayContaining dans des toEqual :)

2021-03-18 17:34 UTC, cmolle commented on tests/unit/helpers/authorization.test.js
> +          'attendancesheets:read',
Ha oui tu as raison...
Pour la partie arrayContaining, tu peux faire un ctrl maj f dnas le code de arrayContaining, ca nous arrive de le faire :)

2021-03-18 17:46 UTC, cmolle commented on src/routes/preHandlers/attendances.js
> +    const { course } = courseSlots[0];
Aujourd'hui je suis d'accord que ca revient au meme, mais fondamentalement ce n'est pas le fait de recuperer des creneaux de plusieurs entreprises que l'on veut bloquer, c'est le fait qu'un utilisateur recupere des creneaux d'une entreprise qui n'est pas la sienne. 
Si c'est beaucoup plus complique a faire et que le code est moins lisible, que penses-tu de deplacer le if dans le cas d'un utilisateur qui n'a pas de role vendeur ?

2021-03-19 07:36 UTC, sophiemoustard commented on src/routes/preHandlers/attendances.js
> +  if (courseSlots.some(cs => cs.course.company !== courseSlots[0].course.company)) throw Boom.badData();
as tu toujours une structure definie pour les formations des créneaux ? je me pose la question puisque tu fais la verification quelques lignes plus bas

2021-03-19 07:40 UTC, sophiemoustard commented on src/routes/preHandlers/attendances.js
> +    const { course } = courseSlots[0];
Pour cette fonctionnalité, je m'interroge : pourquoi envoie-t-on la listes de créneaux dans la requête et non l'_id d'une formation pour récupérer l'émargement sur ces créneaux ?

2021-03-19 10:29 UTC, KennyCallegari commented on tests/unit/helpers/authorization.test.js
> +          'attendancesheets:read',
top merci !

2021-03-19 12:02 UTC, ulysseferreira commented on tests/integration/attendances.test.js
> +    it('should return 403 if slots aren\'t from the same company', async () => {
return 422 du coup, non?

2021-03-19 13:17 UTC, KennyCallegari commented on src/routes/preHandlers/attendances.js
> +    const { course } = courseSlots[0];
Pour l'envoie de la liste des créneaux, c'est pratique parce qu'on utilise la fonction Attendances.list avec seulement un seul id pour rafraichir uniquement la colonne qui contient la checkbox qui vient d'être update (si on clique sur une checkbox, on rafraichi toutes les checkbox du créneau)
Donc les deux cas sont : 
- on envoie une liste de tous les id des créneaux
- on envoie une liste avec un seul créneau dedans

On pourrait peut-être faire deux routes différentes ou bien deux paramètres différents dans la route (courseId / courseSlotId) pour chacun de ces cas ?
Qu'en pensez vous ?

2021-03-19 13:22 UTC, KennyCallegari commented on src/routes/preHandlers/attendances.js
> +  if (courseSlots.some(cs => cs.course.company !== courseSlots[0].course.company)) throw Boom.badData();
Pas forcément, ça relève du badData du coup. J'ai ajouté un garde fou

2021-03-19 13:24 UTC, KennyCallegari commented on tests/integration/attendances.test.js
> +    it('should return 403 if slots aren\'t from the same company', async () => {
done

2021-03-19 13:38 UTC, KennyCallegari commented on src/routes/preHandlers/attendances.js
> +    const { course } = courseSlots[0];
https://github.com/sophiemoustard/alenvi-webapp/pull/960
https://github.com/sophiemoustard/alenvi-api/pull/1285/files

2021-03-19 13:44 UTC, sophiemoustard commented on src/routes/preHandlers/attendances.js
> +    const { course } = courseSlots[0];
je me dis que 1 route avec 2 possibilités pour le champ `query` c'est cool :) : soit un id de formation soit un id de créneau et le prehandler se charge de renvoyer la liste des id des creneaux concernés
l'option 2 routes n'est pas envisageable car l'action a mener est la même donc ca ferait doublon

2021-03-19 17:39 UTC, sophiemoustard commented on src/routes/preHandlers/attendances.js
> +  const courseSlots = await CourseSlot.find(courseSlotsQuery, { course: 1 })
dans ta requete tu pourrais filtrer les creneaux sur la structure aussi comme ca tu n'as pas plus de doute sur ton interrogation 
> Je ne test que pour le premier courseSlot en partant du principe que tous les courseSlots ont la même company, qu'en pensez-vous ?

2021-03-22 13:24 UTC, cmolle commented on src/routes/preHandlers/attendances.js
Est-ce que tu peux faire le changement ici aussi du coup, plus besoin de verifier pour tous les creneaux

2021-03-22 15:27 UTC, sophiemoustard commented on src/routes/preHandlers/attendances.js
> +  if (!courseSlots.length) throw Boom.notFound();
c'est dommage de renvoyer une erreur s'il n'y a pas de creneaux : pour toutes les nouvelles formations, quand on ira dans l'onglet de suivi on aura l'erreur...
ut pourrais simplement renvoyer une liste vide, qu'en penses tu ?

2021-03-22 15:29 UTC, sophiemoustard requested changes

2021-03-22 15:29 UTC, sophiemoustard commented on tests/integration/attendances.test.js
> +      expect(response.statusCode).toBe(200);
une petite ligne ?

2021-03-22 15:29 UTC, sophiemoustard commented on tests/integration/attendances.test.js
> +    it('should return 404 if wrong course', async () => {
`invalid course` plutot ?

2021-03-22 15:29 UTC, sophiemoustard commented on tests/integration/attendances.test.js
> +      });
une ligne ?

2021-03-22 15:29 UTC, sophiemoustard commented on tests/integration/attendances.test.js
> +      });
idem pour la suite

2021-03-22 15:45 UTC, KennyCallegari commented on src/routes/preHandlers/attendances.js
> +  if (!courseSlots.length) throw Boom.notFound();
bien vu ! je l'ai supprimé

2021-03-22 15:46 UTC, KennyCallegari commented on tests/integration/attendances.test.js
> +      expect(response.statusCode).toBe(200);
done

2021-03-22 15:46 UTC, KennyCallegari commented on tests/integration/attendances.test.js
> +    it('should return 404 if wrong course', async () => {
done

2021-03-22 15:46 UTC, KennyCallegari commented on tests/integration/attendances.test.js
> +      });
done

2021-03-22 15:56 UTC, cmolle approved these changes

2021-03-22 16:05 UTC, cmolle commented on src/routes/preHandlers/attendances.js
> +  if (!courseSlots.length) throw Boom.notFound();
Comme le suggerait Sophie, il faudrait que tu renvoie une liste vide ici, sinon on a une 500 car on essaye de lire course d'un courseSlot qui n'existe pas.

2021-03-22 17:01 UTC, sophiemoustard approved these changes

2021-03-23 11:10 UTC, cmolle approved these changes

2021-03-23 11:26 UTC, ulysseferreira approved these changes

2021-03-23 13:57 UTC, sophiemoustard approved these changes

2021-03-23 14:09 UTC, merged