Com 1956
sophiemoustard/alenvi-api pull request #1329
Opened 2021-03-18 10:26 UTC by cmolle

- [x] Mon code est testé unitairement
- Tests intégrations: (barrer ce qui n'est pas utile)
  - Ce n'est pas une ancienne route utilisée par le mobile
      - [x] J'ai bien fait les tests
  - C'est une ancienne route utilisée par le mobile -np
    - J'ai changé ce qu'acceptait ou ce que renvoyait la route (noms de champs, format, conditions)
      - [ ] J'ai fait de nouveaux tests sans modifier les anciens pour s'assurer que les anciennes versions du mobile
      fonctionnent

- [ ] J'ai testé que les anciennes versions maintenues de l'application mobile fonctionnent toujours (a minima): -np
  - [ ] Affichage des pages explorer/mes formations/About/CourseProfile
  - [ ] Inscription a une formation e-learning
  - [ ] Possibilité de faire une activité

- [x] Mes changements n'impactent pas une route utilisée par l'autre plateforme (mobile/webapp)
_- Mes changements impactent une route utilisée par l'autre plateforme (mobile/webapp):
  - [ ] J'ai décrit dans le cas d'usage les choses a tester sur l'autre plateforme
  - Je n'ai pas fait de breaking change :
    - [ ] Je n'ai pas changé les droits de la route
    - [ ] Je n'ai pas changé les droits dans le fichier rights.js
    - [ ] Je n'ai pas fait de changement sur le prehandler qui implique le mobile
    - [ ] Je n'ai pas changé le type d'un paramètre ou enlevé des valeurs possibles
    - Justification des breaking changes s'il y en a:
  - J'ai supprimé une route :
    - [ ] Les anciennes versions mobiles + l'actuelle ne l'utilise pas
  - J'ai renommé une route :
    - [ ] La route n'est pas utilisée par le mobile (si la route est utilisée en mobile: ne pas la renommer et plutôt
    créer une nouvelle route utilisée par la WEBAPP et toutes les nouvelles versions mobiles)
  - J'ai ajoute un champ possible dans la route :
    - [ ] J'ai géré le cas ou on ne l'envoie pas
  - J'ai rendu obligatoire un champs de la route :
    - [ ] Il est toujours envoyé par le mobile (même par les anciennes versions)
  - J'ai retiré un champ possible dans la route :
    - [ ] Les anciennes versions mobiles + l'actuelle ne l'envoient pas
  - J'ai supprimé un retour/un champs du retour de la route :
    - [ ] Les anciennes versions mobiles + l'actuelle n'utilise pas ce retour_

- J'ai changé un modele :
  - J'ai ajoute un champ possible :
    - [ ] J'ai géré le cas ou on ne l'envoie pas - non utilise en mobile
  _- J'ai rendu obligatoire un champs :
    - [ ] Il est toujours envoyé par le mobile (même par les anciennes versions)
  - J'ai retiré un champ possible :
    - [ ] Les anciennes versions mobiles + l'actuelle ne l'envoient pas_

- [x] Je n'ai pas changé de constante

- J'ai ajouté une variable d'environnement : -np
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

- Périmetre interface : vendeur

- Périmetre roles : ROF/admin

- Cas d'usage : Je peux ajouter des testeurs a un programme

2021-03-18 14:14 UTC, KennyCallegari commented on src/helpers/programs.js
> +  return Program.findOneAndUpdate({ _id: programId }, { $addToSet: { testers: addedTester._id } }, { new: true })
trop top $addToSet !

2021-03-18 15:25 UTC, cmolle commented on src/routes/programs.js
> +            contact: Joi.object().keys({ phone: phoneNumberValidation }),
Non ils ne le sont que si c'est un nouvel utilisateur :) Du coup je le verifie dans le prehandler

2021-03-18 15:37 UTC, KennyCallegari approved these changes

2021-03-18 16:35 UTC, sophiemoustard requested changes

2021-03-18 16:35 UTC, sophiemoustard commented on src/helpers/programs.js
> +    .populate('categories')
pourquoi as tu enlevé le path ?

2021-03-18 16:35 UTC, sophiemoustard commented on src/routes/preHandlers/programs.js
> +    }
tu pourrais directement inclure ton test sur le testeur dans le findone qu'en penses tu ? et remplacer par un countDocuments du coup

2021-03-18 16:35 UTC, sophiemoustard commented on src/routes/programs.js
> +      path: '/{_id}/tester',
je mettrai testers au pluriel... less routes sont plutot au pluriel

2021-03-18 17:21 UTC, cmolle commented on src/helpers/programs.js
> +    .populate('categories')
Il me semble que comme on en a pas besoin quand il n'y a pas d'autre params dans le populate, on ne le mettait pas. Tu en penses quoi ?

2021-03-19 10:44 UTC, ulysseferreira approved these changes

2021-03-22 08:25 UTC, sophiemoustard approved these changes

2021-03-22 08:59 UTC, merged