COM-1946: send billed and credit note event
sophiemoustard/alenvi-api pull request #1331
Opened 2021-03-19 10:13 UTC by ulysseferreira

- [x] Mon code est testé unitairement
- Tests intégrations: (barrer ce qui n'est pas utile)
  - Ce n'est pas une ancienne route utilisée par le mobile
      - [x] J'ai bien fait les tests
  - ~~C'est une ancienne route utilisée par le mobile~~
    - J'ai changé ce qu'acceptait ou ce que renvoyait la route (noms de champs, format, conditions)
      - [ ] J'ai fait de nouveaux tests sans modifier les anciens pour s'assurer que les anciennes versions du mobile
      fonctionnent

- [x] J'ai testé que les anciennes versions maintenues de l'application mobile fonctionnent toujours (a minima):
  - [x] Affichage des pages explorer/mes formations/About/CourseProfile
  - [x] Inscription a une formation e-learning
  - [x] Possibilité de faire une activité

- [x] Mes changements n'impactent pas une route utilisée par l'autre plateforme (mobile/webapp)
- ~~Mes changements impactent une route utilisée par l'autre plateforme (mobile/webapp):~~
  - [ ] J'ai décrit dans le cas d'usage les choses a tester sur l'autre plateforme
  - Je n'ai pas fait de breaking change :
    - [ ] Je n'ai pas changé les droits de la route
    - [ ] Je n'ai pas changé les droits dans le fichier rights.js
    - [ ] Je n'ai pas fait de changement sur le prehandler qui implique le mobile
    - [ ] Je n'ai pas changé le type d'un paramètre ou enlevé des valeurs possibles
    - Justification des breaking changes s'il y en a:
  - J'ai supprimé une route :
    - [ ] Les anciennes versions mobiles + l'actuelle ne l'utilise pas
  - J'ai renommé une route :
    - [ ] La route n'est pas utilisée par le mobile (si la route est utilisée en mobile: ne pas la renommer et plutôt
    créer une nouvelle route utilisée par la WEBAPP et toutes les nouvelles versions mobiles)
  - J'ai ajoute un champ possible dans la route :
    - [ ] J'ai géré le cas ou on ne l'envoie pas
  - J'ai rendu obligatoire un champs de la route :
    - [ ] Il est toujours envoyé par le mobile (même par les anciennes versions)
  - J'ai retiré un champ possible dans la route :
    - [ ] Les anciennes versions mobiles + l'actuelle ne l'envoient pas
  - J'ai supprimé un retour/un champs du retour de la route :
    - [ ] Les anciennes versions mobiles + l'actuelle n'utilise pas ce retour

- ~~J'ai changé un modele :~~
  - J'ai ajoute un champ possible :
    - [ ] J'ai géré le cas ou on ne l'envoie pas
  - J'ai rendu obligatoire un champs :
    - [ ] Il est toujours envoyé par le mobile (même par les anciennes versions)
  - J'ai retiré un champ possible :
    - [ ] Les anciennes versions mobiles + l'actuelle ne l'envoient pas

- [x] Je n'ai pas changé de constante

- ~~J'ai ajouté une variable d'environnement :~~
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

- Périmetre interface : client

- Périmetre roles : admin/ROF

- Cas d'usage : refacto avoirs

2021-03-19 15:12 UTC, KennyCallegari commented on tests/integration/events.test.js
> +              &endDate=${endDate}`,
indentation en trop

2021-03-19 16:44 UTC, ulysseferreira commented on src/helpers/events.js
> +  }
en effet

2021-03-19 16:45 UTC, ulysseferreira commented on tests/integration/events.test.js
> +              &endDate=${endDate}`,
indeed, il sort d'où lui 🤔

2021-03-19 17:21 UTC, sophiemoustard commented on src/helpers/events.js
>    return Event.find(query).lean();
il manque une ligne vide avant le return

2021-03-19 17:25 UTC, sophiemoustard commented on tests/unit/helpers/events.test.js
> +    EventModel.expects('find')
peux tu changer ces tests sur `listForCreditNotes` avec la nouvelle version de SinonMongoose ?

2021-03-19 17:25 UTC, sophiemoustard commented on src/routes/preHandlers/events.js
> +  let creditNote = null;
tu peux le définir juste avant `  if (creditNoteId) {` car tu ne l'utilises pas avant

2021-03-19 17:25 UTC, sophiemoustard commented on src/routes/preHandlers/events.js
> +    creditNote = await CreditNote.findOne({ _id: req.query.creditNoteId });
tu peux passer un ligne entre le bloc sur le beneficiaire et le bloc sur l'avoir

2021-03-19 17:26 UTC, KennyCallegari commented on tests/unit/helpers/events.test.js
> +    EventModel.expects('find')
Tu pourrais le faire via SinonMongoose ? 😄

2021-03-19 17:26 UTC, KennyCallegari commented on src/helpers/events.js
> +  }
petit saut de ligne

2021-03-19 17:26 UTC, KennyCallegari commented on tests/unit/helpers/events.test.js
> +    const result = await EventHelper.listForCreditNotes(payload, credentials, creditNote);
petit saut de ligne ici aussi

2021-03-19 17:26 UTC, KennyCallegari commented on tests/unit/helpers/events.test.js
> +    }];
tu peux le définir directement dans le return, il me semble qu'on préfère faire comme ça quand ce n'est pas un id (même chose pour credentials)

2021-03-19 17:28 UTC, sophiemoustard requested changes

2021-03-19 17:28 UTC, sophiemoustard commented on src/helpers/events.js
> +    };
sur une ligne

2021-03-19 17:28 UTC, sophiemoustard commented on src/helpers/events.js
> +  if (creditNote) {
pour garder la logique des bloc et en meme temps aérer ton code, tu peux passer une ligne et idem au dessus

2021-03-19 18:42 UTC, ulysseferreira commented on src/helpers/events.js
>    return Event.find(query).lean();
done

2021-03-19 18:48 UTC, ulysseferreira commented on tests/unit/helpers/events.test.js
> +    EventModel.expects('find')
done

2021-03-19 18:50 UTC, ulysseferreira commented on src/routes/preHandlers/events.js
> +  let creditNote = null;
done

2021-03-19 18:51 UTC, ulysseferreira commented on src/routes/preHandlers/events.js
> +    creditNote = await CreditNote.findOne({ _id: req.query.creditNoteId });
done

2021-03-19 18:51 UTC, ulysseferreira commented on tests/unit/helpers/events.test.js
> +    EventModel.expects('find')
oupsi done

2021-03-19 18:52 UTC, ulysseferreira commented on src/helpers/events.js
> +  }
done

2021-03-19 18:53 UTC, ulysseferreira commented on tests/unit/helpers/events.test.js
> +    const result = await EventHelper.listForCreditNotes(payload, credentials, creditNote);
done

2021-03-19 18:55 UTC, ulysseferreira commented on tests/unit/helpers/events.test.js
> +    }];
done

2021-03-19 18:55 UTC, ulysseferreira commented on src/helpers/events.js
> +    };
done

2021-03-19 18:56 UTC, ulysseferreira commented on src/helpers/events.js
> +  if (creditNote) {
done

2021-03-22 07:54 UTC, sophiemoustard commented on src/routes/preHandlers/events.js
> +  const { creditNoteId, startDate, endDate } = req.query;
ca aussi, a mettre juste avant le `if (creditNoteId) {`

2021-03-22 07:54 UTC, sophiemoustard commented on tests/unit/helpers/events.test.js
>      }];
sur une ligne

2021-03-22 07:55 UTC, sophiemoustard commented on tests/unit/helpers/events.test.js
> +    ]);
sur une ligne

2021-03-22 07:55 UTC, sophiemoustard commented on tests/unit/helpers/events.test.js
> +    ]);
idem

2021-03-22 07:56 UTC, sophiemoustard commented on tests/unit/helpers/events.test.js
>      }];
il y a d'autres endroits, je te laisse le changer partout. pour cette variable et pour les autres

2021-03-22 09:38 UTC, KennyCallegari commented on tests/unit/helpers/events.test.js
> +    }];
Top, merci pour ta réponse détaillée !
Pour le `.toBe`, je pense que tu peux le passer en `.toEqual` .
En général, on utilise `toBe` sur les `statusCode` et toEqual sur les `result`

2021-03-22 12:02 UTC, ulysseferreira commented on tests/unit/helpers/events.test.js
> +    }];
done

2021-03-22 12:03 UTC, ulysseferreira commented on src/routes/preHandlers/events.js
> +  const { creditNoteId, startDate, endDate } = req.query;
done

2021-03-22 12:07 UTC, ulysseferreira commented on tests/unit/helpers/events.test.js
>      }];
done

2021-03-22 12:20 UTC, ulysseferreira commented on tests/unit/helpers/events.test.js
> +    ]);
done

2021-03-23 08:12 UTC, cmolle commented on src/routes/preHandlers/events.js
> +    if (creditNote.events.some(e => e.startDate < startDate && e.endDate > endDate)) throw Boom.badData();
A quoi sert cette condition ?

2021-03-23 08:21 UTC, sophiemoustard approved these changes

2021-03-23 09:43 UTC, KennyCallegari approved these changes

2021-03-23 09:57 UTC, ulysseferreira commented on src/routes/preHandlers/events.js
> +    if (creditNote.events.some(e => e.startDate < startDate && e.endDate > endDate)) throw Boom.badData();
on vérifie que les évènements de l’avoir sont compris dans l’intervalle de dates query.startDate et query.endDate, c'était spécifié dans la strat technique pour s'assurer que les événements cochés qu'on récupère sont bien dans l'intervalle. Tu penses que c'est superflu comme vérif ?

2021-03-23 10:50 UTC, cmolle commented on src/routes/preHandlers/events.js
> +    if (creditNote.events.some(e => e.startDate < startDate && e.endDate > endDate)) throw Boom.badData();
Je suis desolee je pensais que c'etait un prehandler pour l'edition, je n'avais pas vu que c'etait celui du get :)

2021-03-23 10:51 UTC, cmolle approved these changes

2021-03-23 11:04 UTC, merged