Com 1955
sophiemoustard/alenvi-api pull request #1334
Opened 2021-03-23 12:55 UTC by cmolle

- [x] Mon code est testé unitairement
- Tests intégrations: (barrer ce qui n'est pas utile)
  - Ce n'est pas une ancienne route utilisée par le mobile
      - [x] J'ai bien fait les tests
  - C'est une ancienne route utilisée par le mobile -np
    - J'ai changé ce qu'acceptait ou ce que renvoyait la route (noms de champs, format, conditions)
      - [ ] J'ai fait de nouveaux tests sans modifier les anciens pour s'assurer que les anciennes versions du mobile
      fonctionnent

- [ ] J'ai testé que les anciennes versions maintenues de l'application mobile fonctionnent toujours (a minima): -np
  - [ ] Affichage des pages explorer/mes formations/About/CourseProfile
  - [ ] Inscription a une formation e-learning
  - [ ] Possibilité de faire une activité

- [x] Mes changements n'impactent pas une route utilisée par l'autre plateforme (mobile/webapp)
- Mes changements impactent une route utilisée par l'autre plateforme (mobile/webapp): -np
  - [ ] J'ai décrit dans le cas d'usage les choses a tester sur l'autre plateforme
  - Je n'ai pas fait de breaking change :
    - [ ] Je n'ai pas changé les droits de la route
    - [ ] Je n'ai pas changé les droits dans le fichier rights.js
    - [ ] Je n'ai pas fait de changement sur le prehandler qui implique le mobile
    - [ ] Je n'ai pas changé le type d'un paramètre ou enlevé des valeurs possibles
    - Justification des breaking changes s'il y en a:
  - J'ai supprimé une route :
    - [ ] Les anciennes versions mobiles + l'actuelle ne l'utilise pas
  - J'ai renommé une route :
    - [ ] La route n'est pas utilisée par le mobile (si la route est utilisée en mobile: ne pas la renommer et plutôt
    créer une nouvelle route utilisée par la WEBAPP et toutes les nouvelles versions mobiles)
  - J'ai ajoute un champ possible dans la route :
    - [ ] J'ai géré le cas ou on ne l'envoie pas
  - J'ai rendu obligatoire un champs de la route :
    - [ ] Il est toujours envoyé par le mobile (même par les anciennes versions)
  - J'ai retiré un champ possible dans la route :
    - [ ] Les anciennes versions mobiles + l'actuelle ne l'envoient pas
  - J'ai supprimé un retour/un champs du retour de la route :
    - [ ] Les anciennes versions mobiles + l'actuelle n'utilise pas ce retour

- J'ai changé un modele : -np
  - J'ai ajoute un champ possible :
    - [ ] J'ai géré le cas ou on ne l'envoie pas
  - J'ai rendu obligatoire un champs :
    - [ ] Il est toujours envoyé par le mobile (même par les anciennes versions)
  - J'ai retiré un champ possible :
    - [ ] Les anciennes versions mobiles + l'actuelle ne l'envoient pas

- [x] Je n'ai pas changé de constante

- J'ai ajouté une variable d'environnement : -np
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

- Périmetre interface : vendeur

- Périmetre roles : rof/admin

- Cas d'usage : Possibilite de voir les reponses aux questionnaires d'une formation elearning

2021-03-23 14:01 UTC, ulysseferreira commented on tests/unit/helpers/courses.test.js
> +  it('should return [] if no stepss', async () => {
un s en trop à steps

2021-03-23 14:03 UTC, ulysseferreira commented on tests/unit/helpers/courses.test.js
> +            {
je l'aurais mis sur la ligne du dessus avec le crochet (pareil pour la parenthèse fermante)

2021-03-23 14:04 UTC, ulysseferreira commented on tests/unit/helpers/courses.test.js
> +          {
idem

2021-03-23 14:06 UTC, ulysseferreira commented on tests/unit/helpers/courses.test.js
> +            {
idem

2021-03-23 14:07 UTC, ulysseferreira commented on tests/unit/helpers/courses.test.js
> +            {
idem

2021-03-23 14:07 UTC, ulysseferreira commented on tests/unit/helpers/courses.test.js
> +            {
je l'aurais mis sur la ligne du dessus avec le crochet (pareil pour la parenthèse fermante)

2021-03-23 14:08 UTC, ulysseferreira commented on tests/unit/helpers/courses.test.js
> +            {
idem

2021-03-23 14:08 UTC, ulysseferreira commented on tests/unit/helpers/courses.test.js
> +            {
idem

2021-03-23 14:29 UTC, sophiemoustard requested changes

2021-03-23 14:29 UTC, sophiemoustard commented on tests/unit/helpers/courses.test.js
> +            _id: ObjectID(),
il manque le new devant

2021-03-23 14:29 UTC, sophiemoustard commented on tests/unit/helpers/courses.test.js
> +          },
sur une ligne

2021-03-23 14:29 UTC, sophiemoustard commented on tests/unit/helpers/courses.test.js
> +          },
idem

2021-03-23 15:10 UTC, KennyCallegari approved these changes

2021-03-24 07:59 UTC, sophiemoustard commented on src/helpers/courses.js
> +      const { answerList } = answer;
pourquoi as tu créé cette variable ?

2021-03-24 07:59 UTC, sophiemoustard commented on tests/unit/helpers/courses.test.js
> +  it('should return [] if no steps', async () => {
step snsa s puisque tu en as 0

2021-03-24 08:00 UTC, sophiemoustard commented on src/helpers/courses.js
> +      if (answerList.length === 1 && !answerList[0].trim()) continue;
pourquoi tu ne `trim` que le premier ?

2021-03-24 08:21 UTC, sophiemoustard commented on src/helpers/courses.js
> +      followUp[answer.card._id].answers.push(...answerList);
pourquoi tu ne `trim` que le premier et pas le tableau entier ? il n'y en aura toujours qu'un

2021-03-24 12:20 UTC, cmolle commented on src/helpers/courses.js
> +      const { answerList } = answer;
Pour simplifier le code vu que j'utilisais trois fois`answer.answerList`

2021-03-24 12:24 UTC, cmolle commented on src/helpers/courses.js
> +      followUp[answer.card._id].answers.push(...answerList);
Je ne suis pas sure de comprendre ta question. 
Au moment ou je trim il n'y en a qu'un car je le verifie en premiere condition, du coup je trim le tableau en entier. 
De maniere plus globale il peut y avoir plusieurs elements dans answerList dans le cas de qcm mais c'est un cas qui ne nous interesse pas car ce sont des id.

2021-03-24 12:31 UTC, sophiemoustard approved these changes

2021-03-24 14:45 UTC, ulysseferreira approved these changes

2021-03-24 14:58 UTC, merged