[Draft] Com 1926
sophiemoustard/alenvi-api pull request #1341
Opened 2021-03-25 20:24 UTC by KennyCallegari

draft

2021-03-25 20:27 UTC, KennyCallegari commented on src/routes/preHandlers/attendances.js
> +  if (!courseSlots.length) throw Boom.notFound();
Règle un bug présent sur dev -> si on va sur l'onglet suivi des stagiaires sur une formation sans créneaux = 500;

(Ajouter un test ?)

2021-03-25 20:27 UTC, KennyCallegari commented on tests/integration/attendances.test.js
> +    it('should return 400 if query has course and courseSlot but return a 404 and I have no idea why', async () => {
Pourquoi ?

2021-03-26 11:30 UTC, cmolle commented on src/routes/preHandlers/attendanceSheets.js
> +  return (course.type === INTER_B2B && !loggedUserHasVendorRole) ? loggedUserCompany : null;
Pour le cas intra/sans role vendeur il faut probablement faire la meme verif que pour les emargements non ? (i.e. que le loggedUser a la meme entreprise que la formation)

2021-03-26 11:30 UTC, cmolle commented on src/routes/preHandlers/attendances.js
>  exports.authorizeAttendancesGet = async (req) => {
Que penses-tu de decouper ce prehandler en plusieurs methodes ?

2021-03-26 11:30 UTC, cmolle commented on tests/integration/attendanceSheets.test.js
> +    it('should get only authComapny\'s attendance sheets for interB2B course if user does not have vendor role',
company

2021-03-26 11:30 UTC, cmolle commented on tests/integration/attendances.test.js
> +    it('should get course attendances not filtered by company for inter course', async () => {
Il me semble que dans les tests on essaye de mettre tous les cas qui renvoient une 200 au debut, puis tous les cas qui renvoient une erreur

2021-03-26 11:30 UTC, cmolle commented on tests/unit/helpers/attendanceSheets.test.js
> +    ]);
Il manque le populate

2021-03-26 11:30 UTC, cmolle commented on tests/unit/helpers/attendances.test.js
> +    ]);
idem

2021-03-26 11:30 UTC, cmolle commented on tests/unit/helpers/attendances.test.js
> +    ]);
idem

2021-03-26 13:20 UTC, ulysseferreira commented on tests/unit/helpers/attendanceSheets.test.js
> +    SinonMongoose.calledWithExactly(find, [
le find à la ligne (un paramètre par ligne), y en a plusieurs à corriger sur cette page

2021-03-26 16:52 UTC, KennyCallegari commented on src/routes/preHandlers/attendanceSheets.js
> +  return (course.type === INTER_B2B && !loggedUserHasVendorRole) ? loggedUserCompany : null;
done

2021-03-26 16:57 UTC, KennyCallegari commented on src/routes/preHandlers/attendances.js
>  exports.authorizeAttendancesGet = async (req) => {
done

2021-03-26 16:57 UTC, KennyCallegari commented on tests/integration/attendanceSheets.test.js
> +    it('should get only authComapny\'s attendance sheets for interB2B course if user does not have vendor role',
done

2021-03-26 16:57 UTC, KennyCallegari commented on tests/integration/attendances.test.js
> +    it('should get course attendances not filtered by company for inter course', async () => {
done

2021-03-26 17:01 UTC, KennyCallegari commented on tests/unit/helpers/attendanceSheets.test.js
> +    ]);
done (bien vu !)

2021-03-26 17:01 UTC, KennyCallegari commented on tests/unit/helpers/attendances.test.js
> +    ]);
done

2021-03-26 17:04 UTC, KennyCallegari commented on tests/unit/helpers/attendances.test.js
> +    ]);
done

2021-03-29 07:13 UTC, sophiemoustard commented on src/helpers/attendanceSheets.js
> +exports.list = async (course, company) => {
companyId peut etre ?

2021-03-29 07:13 UTC, sophiemoustard commented on src/helpers/attendances.js
> +exports.list = async (query, company) => {
idem

2021-03-29 07:28 UTC, sophiemoustard requested changes

2021-03-29 07:28 UTC, sophiemoustard commented on src/routes/preHandlers/attendanceSheets.js
> +  if (!UtilsHelper.areObjectIdsEquals(loggedUserCompany, course.company) && !loggedUserHasVendorRole) {
si la formation est INTER_B2B il n'y a pas de structure pour la formation

2021-03-29 07:28 UTC, sophiemoustard commented on src/routes/preHandlers/attendanceSheets.js
> +  if (!UtilsHelper.areObjectIdsEquals(loggedUserCompany, course.company) && !loggedUserHasVendorRole) {
dans ton prehandler tu pourrais faire 2 cas distincts, voire 2 methodes distinctes selon le type de la formation
- si INTRA
  -- si pas de role vendeur et structure différentes -> erreur
  -- sinon ok
- si INTER_B2B
  --  si pas de role vendeur, on ernvoie la structure
  -- sinon on renvoie null

2021-03-29 07:28 UTC, sophiemoustard commented on src/routes/preHandlers/attendanceSheets.js
> +  if (!UtilsHelper.areObjectIdsEquals(loggedUserCompany, course.company) && !loggedUserHasVendorRole) {
pour ce genre de developpement ou il y a pas mal de cas a tester, je te conseille de faire un tableau sur ton carnet pour bien lister tous les cas :)

2021-03-29 07:28 UTC, sophiemoustard commented on src/routes/preHandlers/attendances.js
> +      UtilsHelper.areObjectIdsEquals(loggedUserCompany, t.company));
je mettrais plutot le `.some` a la ligne pour la lisibilité qu'en penses tu ?

2021-03-29 07:50 UTC, KennyCallegari commented on tests/unit/helpers/attendanceSheets.test.js
> +    SinonMongoose.calledWithExactly(find, [
done

2021-03-29 07:53 UTC, KennyCallegari commented on src/helpers/attendanceSheets.js
> +exports.list = async (course, company) => {
done

2021-03-29 07:53 UTC, KennyCallegari commented on src/helpers/attendances.js
> +exports.list = async (query, company) => {
done

2021-03-29 07:54 UTC, KennyCallegari commented on src/routes/preHandlers/attendances.js
> +      UtilsHelper.areObjectIdsEquals(loggedUserCompany, t.company));
done

2021-03-29 09:45 UTC, ulysseferreira commented on tests/unit/helpers/attendances.test.js
>      SinonMongoose.calledWithExactly(find, [
find à la ligne

2021-03-29 09:45 UTC, ulysseferreira commented on tests/unit/helpers/attendances.test.js
>      SinonMongoose.calledWithExactly(find, [
idem

2021-03-29 09:45 UTC, ulysseferreira commented on tests/unit/helpers/attendances.test.js
>      SinonMongoose.calledWithExactly(find, [
idem

2021-03-29 09:45 UTC, ulysseferreira commented on tests/integration/attendances.test.js
> +    it('should return 400 if query has course and courseSlot but return a 404 and I have no idea why', async () => {
@cmolle @sophiemoustard vous avez une idée de pourquoi ? 404 c'est quand la ressource est pas accessible aka l'id fourni n'est pas bon et 400 quand le serveur arrive même pas à interprété la route, genre il y a une faute de frappe où un truc du genre ? mais là c'est une route qui est jamais possible du coup ça devrait plutôt être interprété en 400 ?

2021-03-29 09:48 UTC, cmolle commented on src/routes/preHandlers/attendances.js
>    }
Est-ce qu'il y a besoin de ce test ? Vu qu'on verifie qu'il y a des creneaux, si on passe le `if (!courseSlots.length)` et qu'on ne passe pas celui-la c'est qu'on a un soucis dans notre bdd.

2021-03-29 10:02 UTC, KennyCallegari commented on src/routes/preHandlers/attendanceSheets.js
> +  if (!UtilsHelper.areObjectIdsEquals(loggedUserCompany, course.company) && !loggedUserHasVendorRole) {
done

2021-03-29 10:04 UTC, cmolle commented on tests/integration/attendances.test.js
> +        url: `/attendances/course=${coursesList[0]._id}&courseSlot=${slotsList[0]._id}`,
L'url a appeler est `/attendances?course=${coursesList[0]._id}&courseSlot=${slotsList[0]._id}`, il faut remplacer le '/' par '?'. 

Pour rappel, il me semble que : 
- Le / est suivi des parametres de la route (ex: id de la couse que l'on recupere), 
- le ? est suivi des query (ex: ici les id de la course ou creneau liés aux emargements que l'on veut recuperer)

2021-03-29 10:06 UTC, KennyCallegari commented on src/routes/preHandlers/attendanceSheets.js
> +  if (!UtilsHelper.areObjectIdsEquals(loggedUserCompany, course.company) && !loggedUserHasVendorRole) {
done

2021-03-29 10:07 UTC, KennyCallegari commented on tests/integration/attendances.test.js
> +        url: `/attendances/course=${coursesList[0]._id}&courseSlot=${slotsList[0]._id}`,
bien vu ><

2021-03-29 10:12 UTC, KennyCallegari commented on tests/unit/helpers/attendances.test.js
>      SinonMongoose.calledWithExactly(find, [
done

2021-03-29 10:12 UTC, KennyCallegari commented on tests/unit/helpers/attendances.test.js
>      SinonMongoose.calledWithExactly(find, [
done

2021-03-29 10:12 UTC, KennyCallegari commented on tests/unit/helpers/attendances.test.js
>      SinonMongoose.calledWithExactly(find, [
done

2021-03-29 10:12 UTC, KennyCallegari commented on tests/integration/attendances.test.js
> +    it('should return 400 if query has course and courseSlot but return a 404 and I have no idea why', async () => {
chloé a trouvé la typo !

2021-03-29 10:14 UTC, KennyCallegari commented on src/routes/preHandlers/attendances.js
>    }
Je penses aussi que c'est redondant avec le test au dessus

2021-03-29 10:29 UTC, ulysseferreira commented on src/routes/preHandlers/attendanceSheets.js
> +  if (course.type === INTER_B2B) return loggedUserCompany;
sur la route et le controller au lieu de lui assigner company, peut-être lui assigner companyId pour être cohérent

2021-03-29 11:08 UTC, KennyCallegari commented on src/routes/preHandlers/attendanceSheets.js
> +  if (course.type === INTER_B2B) return loggedUserCompany;
done

2021-03-29 12:18 UTC, ulysseferreira approved these changes

2021-03-29 13:35 UTC, sophiemoustard commented on tests/unit/helpers/attendances.test.js
> +  it('should return all courseSlots attendances', async () => {
je ne comprends pas la difference avec le test du dessus

2021-03-29 14:21 UTC, KennyCallegari commented on tests/unit/helpers/attendances.test.js
> +  it('should return all courseSlots attendances', async () => {
Je voulais tester les deux cas d'utilisation de cette route : 
- soit on demande la liste d'émargement pour un seul créneau (premier test)
- soit on demande la liste d'émargement pour tous les créneaux d'une formation (deuxième test)

Je voulais bien distinguer les deux cas pour être sûr que dans le futur, si on modifie le helper, il respecte toujours son rôle pour les deux cas d'utilisation de cette route.

2021-03-29 14:54 UTC, cmolle approved these changes

2021-03-29 15:03 UTC, sophiemoustard commented on tests/unit/helpers/attendances.test.js
> +  it('should return all courseSlots attendances', async () => {
en fait dans ton service ne fait pas la distinction entre les 2 - dans le logique du code
donc ce doublon n'est pas forcement utile car ta methode est agnostique du nombre d'id que tu lui passes dans ton tableau

2021-03-29 15:56 UTC, sophiemoustard approved these changes

2021-03-29 15:56 UTC, merged