Com 1995
sophiemoustard/alenvi-api pull request #1372
Opened 2021-04-15 09:12 UTC by ulysseferreira

### TESTS
- [x] Mon code est testé unitairement
- Tests intégrations :
  - Ce n'est pas une ancienne route utilisée par les apps mobiles
      - [x] J'ai bien fait les tests
  - ~~C'est une ancienne route utilisée par une des apps mobiles~~
    - J'ai changé ce qu'acceptait ou ce que renvoyait la route (noms de champs, format, conditions)
      - [ ] J'ai fait de nouveaux tests sans modifier les anciens pour s'assurer que les anciennes versions des
      apps mobiles fonctionnent

### FONCTIONNALITÉS APPS MOBILES
- Si mes changements impactent l'application formation :
  - [x] J'ai testé que les anciennes versions maintenues fonctionnent toujours (a minima):
    - [x] Affichage des pages explorer/mes formations/About/CourseProfile
    - [x] Inscription a une formation e-learning
    - [x] Possibilité de faire une activité

-~~ Si mes changements impactent l'application erp :~~
  - [ ] J'ai testé que les anciennes versions maintenues fonctionnent toujours

### MODIFICATIONS SUR LES ROUTES IMPACTANT UNE AUTRE PLATEFORME
- [x] J'ai décrit dans le cas d'usage les choses à tester sur l'autre plateforme
- Je n'ai pas fait de breaking change :
  - [x] Je n'ai pas changé les droits de la route
  - [x] Je n'ai pas changé les droits dans le fichier rights.js
  - [x] Je n'ai pas fait de changement sur le prehandler qui implique le mobile
  - [x] Je n'ai pas changé le type d'un paramètre ou enlevé des valeurs possibles
  - ~~Justification des breaking changes s'il y en a:~~
- ~~J'ai supprimé une route :~~
  - [ ] Les anciennes versions mobiles + les actuelles ne l'utilisent pas
- ~~J'ai renommé une route :~~
  - [ ] La route n'est pas utilisée par les apps mobiles 
    (si la route est utilisée en mobile: ne pas la renommer et plutôt créer une nouvelle route utilisée par la WEBAPP
    et toutes les nouvelles versions mobiles)
- ~~J'ai ajouté un champ possible dans la route :~~
  - [ ] J'ai géré le cas ou on ne l'envoie pas
- ~~J'ai rendu obligatoire un champs de la route :~~
  - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
- ~~J'ai retiré un champ possible dans la route :~~
  - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas
- ~~J'ai supprimé un retour/un champs du retour de la route :~~
  - [ ] Les anciennes versions mobiles + les actuelles n'utilisent pas ce retour

### MODIFICATIONS SUR LES MODÈLES UTILISÉS PAR LES APPS MOBILE
- ~~J'ai changé un modèle :~~
  - J'ai ajoutê un champ possible :
    - [ ] J'ai géré le cas où l'application ne l'envoie pas
  - J'ai rendu obligatoire un champs :
    - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
  - J'ai retiré un champ possible :
    - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas

### CONSTANTES ET VARIABLE D'ENV
-~~ J'ai changé une constante :~~
  - [ ] Elle n'est pas utilisée sur les apps mobiles (Sinon on doit forcer la maj des apps)

- ~~J'ai ajouté une variable d'environnement :~~
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

### POUR TESTER LA PR
- Périmetre interface : mobile

- Périmetre roles : tous 

- Cas d'usage : sur l'application mobile, sur les formations blended non commencées, j'ai un bandeau avec le questionnaire Recueil des besoins

2021-04-15 11:44 UTC, KennyCallegari commented on src/helpers/questionnaires.js
> +  }
Je pense qu'il vaut mieux ne pas faire l'appel en front si ces conditions sont respectées et donc renvoyer une forbidden dans le preHandler si on appelle quand même la route

2021-04-15 11:44 UTC, KennyCallegari commented on src/helpers/questionnaires.js
> +    .lean();
Il me semble qu'on formate comme ça plutôt : 
```
  const questionnaire = await Questionnaire.findOne({ type: EXPECTATIONS, status: PUBLISHED }, { type: 1, title: 1 })
    .lean();
```

2021-04-15 11:44 UTC, KennyCallegari commented on tests/integration/questionnaires.test.js
> +      fakeDate = sinon.stub(Date, 'now');
Il me semble qu'on utilise fakeDate avec `sinon.fakeTimer` ici ce serait plutôt un `nowStub`, qu'en penses-tu ?

2021-04-15 11:44 UTC, KennyCallegari commented on tests/integration/questionnaires.test.js
> +      expect(response.result.data.questionnaires).toEqual([{ _id, title, type }]);
Il me semble qu'on a arrêté ce genre de test puisqu'en soit les tests unitaires sont là pour ça. ça te parle ?

2021-04-15 11:44 UTC, KennyCallegari commented on tests/integration/questionnaires.test.js
> +        url: '/questionnaires/user?course=skusku',
👌

2021-04-15 11:44 UTC, KennyCallegari commented on tests/integration/questionnaires.test.js
> +    it('should return 404 if invalid course', async () => {
course not found*

2021-04-15 11:44 UTC, KennyCallegari commented on tests/integration/seed/questionnairesSeed.js
> +const coursesList = [{
Que penses-tu d'ajouter un format 'blended' à cette formation pour mieux représenter une donnée réaliste ?

2021-04-15 12:20 UTC, ulysseferreira commented on src/routes/questionnaires.js
> +        pre: [{ method: authorizeCourseQuestionnairesGet, assign: 'course' }],
done

2021-04-15 12:29 UTC, ulysseferreira commented on src/helpers/questionnaires.js
> +  }
hum je sais pas on en avait parlé avec Sophie pour la partie strictly_e-learning et l'argument pour le mettre en back c'était qu'actuellement on veut pas de questionnaires sur les formations e-learning mais potentiellement ça sera le cas à l'avenir et ça sera plus simple si la gestion se fait en back comme ça on n'aura que le back à changer et on n'aura pas à faire de MAJ forcée pour l'utilisateur. Pour les deux autres je suis d'accord que ça pourrait être fait en front mais du coup je sais pas trop si c'est bien de scinder la logque en deux 🤔

2021-04-15 12:33 UTC, ulysseferreira commented on src/helpers/questionnaires.js
> +    .lean();
hum je sais pas trop j'ai l'impression que c'est pas trop défini (faudrait peut-être homogénéiser) mais que lorsqu'il y a que le find puis le lean, on les mets chacun sur une ligne et que c'est quand on a des populates entre les deux qu'on laisse le find sur la même ligne que son parent

2021-04-15 12:34 UTC, ulysseferreira commented on tests/integration/questionnaires.test.js
> +      expect(response.result.data.questionnaires).toEqual([{ _id, title, type }]);
j'avais pas suivi qu'on avait arrêté mais en soit oui c'est logique, ça sert pas vraiment, je le retire

2021-04-15 12:42 UTC, ulysseferreira commented on tests/integration/questionnaires.test.js
> +        url: '/questionnaires/user?course=skusku',
😂

2021-04-15 12:42 UTC, ulysseferreira commented on tests/integration/questionnaires.test.js
> +    it('should return 404 if invalid course', async () => {
done

2021-04-15 12:53 UTC, KennyCallegari reviewed
Je me tape des 401 quand j'essaye d'accéder à un formation, tu sais pourquoi ?

2021-04-15 13:07 UTC, ulysseferreira commented on tests/integration/seed/questionnairesSeed.js
> +const coursesList = [{
done

2021-04-15 13:08 UTC, ulysseferreira commented on tests/integration/questionnaires.test.js
> +      fakeDate = sinon.stub(Date, 'now');
done

2021-04-15 15:55 UTC, KennyCallegari commented on src/helpers/questionnaires.js
> +    .lean();
Effectivement, il faudrait une petite homogénéisation de tout ça.
@sophiemoustard @cmolle Qu'en pensez vous ?

2021-04-15 16:20 UTC, sophiemoustard requested changes

2021-04-15 16:25 UTC, KennyCallegari commented on src/helpers/questionnaires.js
> +  }
En soit si tu changes le back, il y aura forcément du maj forcée non ? Sinon ceux qui ont la version de l'API qui renvoi [] pour une formation eLearning ne verront pas le questionnaire.

Pour le deuxième cas aussi ça peut être géré par preHandler / appel dans le front, non ?

2021-04-15 16:29 UTC, sophiemoustard commented on src/helpers/questionnaires.js
> +    .lean();
je penche pour la proposition de Kenny
si model + find tiennent sur une meme ligne, on peut faire comme ca

2021-04-15 16:31 UTC, KennyCallegari commented on src/helpers/questionnaires.js
> +  }
Pour la partie maj forcée, je suis d'accord. Mais ça m'embête d'avoir des appels à cette route à chaque fois qu'un utilisateur arrive sur courseProfile. Sachant qu'on pourrait limiter ce nombre d'appels en front, au moins pour : `!course.slots.length || DatesHelper.isAfter(Date.now(), course.slots[0].startDate)`

Par contre on pourrait toujours gérer avec front + preHandler pour le deuxième cas non ?

2021-04-15 16:33 UTC, KennyCallegari commented on src/helpers/questionnaires.js
> +  }
Et à la limite je préfèrerai avoir front + preHandler et forcer la maj, plutôt que de laisser ça comme ça.

Qu'en pensez-vous ? @cmolle @sophiemoustard

2021-04-15 16:36 UTC, ulysseferreira commented on src/helpers/questionnaires.js
> +    DatesHelper.isAfter(Date.now(), course.slots[0].startDate)) {
done

2021-04-15 16:52 UTC, ulysseferreira commented on src/helpers/questionnaires.js
> +  }
ouais mais quand on aura pleins de questionnaires avec pleins d'autres conditions d'affichage, on devra remettre tout ça dans le helper du coup je suis pas trop convaincu par l'option front

2021-04-15 17:08 UTC, sophiemoustard commented on src/helpers/questionnaires.js
> +  }
Avec les futurs questionnaire qui arrivent (Fin de formation / Evaluation / Auto-positionnement), ces conditions vont beaucoup évoluer. donc a date je ne pense pas que ce soit une bonne idée de gérer cette logique dans le front au risque de demander un MAJ toutes les 2 semaines + se prendre la tête avec des potentielles MEP intermédiaires. C'est une complexité pour nous et une mauvaise expérience pour l'utilisateur.

Et de manière générale, je me dis que c'est plus simple de gerer la logique en back qu'en mobile pour limiter les breaking change, les mep intermediaires, les maj forcée... Chloé avait soumis cette idée pour la gesiton des creneaux en reflechissant a la strat technique de ce ticket et je suis d'accord avec ce constat

2021-04-16 07:38 UTC, KennyCallegari commented on src/helpers/questionnaires.js
> +  }
ça marche 👌

2021-04-16 08:54 UTC, KennyCallegari approved these changes

2021-04-16 08:56 UTC, KennyCallegari commented on src/helpers/questionnaires.js
> +  if (course.format === STRICTLY_E_LEARNING || !course.slots.length || isCourseStarted) return [];
pas besoin du saut de ligne et il me semble que la condition `!course.slots.length` est déjà comprise dans `get(course, 'slots.length')`

2021-04-16 09:07 UTC, cmolle commented on src/helpers/questionnaires.js
> +  if (course.format === STRICTLY_E_LEARNING || !course.slots.length || isCourseStarted) return [];
Si il n'y a pas de créneau on pourrait afficher les questionnaires non ? Si il n'y en a pas, c'est normalement qu'ils ne sont pas encore passés car pas encore plannifiés

2021-04-16 09:07 UTC, cmolle commented on tests/integration/questionnaires.test.js
> +  describe('Other roles', () => {
Il faudrait tester avec quelqu'un sans role aussi

2021-04-16 09:07 UTC, cmolle commented on tests/integration/questionnaires.test.js
> +      nowStub = sinon.stub(Date, 'now');
Est-ce que tu as eu le temps de regarder les bonnes pratiques a ce sujet ?

2021-04-16 09:15 UTC, sophiemoustard commented on tests/integration/questionnaires.test.js
> +  describe('Other roles', () => {
tu pourrais tester uniquement sans role d'ailleurs non ?

2021-04-16 09:38 UTC, ulysseferreira commented on src/helpers/questionnaires.js
> +  if (course.format === STRICTLY_E_LEARNING || !course.slots.length || isCourseStarted) return [];
done

2021-04-16 09:38 UTC, ulysseferreira commented on src/helpers/questionnaires.js
> +  if (course.format === STRICTLY_E_LEARNING || !course.slots.length || isCourseStarted) return [];
done

2021-04-16 09:46 UTC, ulysseferreira commented on tests/integration/questionnaires.test.js
> +  describe('Other roles', () => {
done

2021-04-16 09:48 UTC, ulysseferreira commented on tests/integration/questionnaires.test.js
> +      nowStub = sinon.stub(Date, 'now');
y a des gens qui parlaient d'utiliser userfaketimer sur stack overflow mais d'après certains ça peut faire péter les tests et du coup d'autres conseillaient d'utiliser sinon.stub(Date, 'now')

2021-04-16 10:24 UTC, cmolle commented on tests/integration/questionnaires.test.js
> +  describe('Other roles', () => {
Up sur le commentaire de Sophie

2021-04-16 10:25 UTC, cmolle commented on tests/integration/questionnaires.test.js
> +      nowStub = sinon.stub(Date, 'now');
Ok. @KennyCallegari Est-ce que c'est avec toi qu'on avait eu un soucis avec le stub de date et mongo ? Je ne me souviens pas bien du bug/ de ce qu'on s'etait dit sur le sujet.

2021-04-16 10:45 UTC, cmolle commented on tests/integration/questionnaires.test.js
> +  describe('TRAINING_ORGANISATION_MANAGER', () => {
Des ici tu peux tester sans role je pense

2021-04-16 10:50 UTC, ulysseferreira commented on tests/integration/questionnaires.test.js
> +  describe('TRAINING_ORGANISATION_MANAGER', () => {
done

2021-04-16 12:08 UTC, KennyCallegari commented on tests/integration/questionnaires.test.js
> +      nowStub = sinon.stub(Date, 'now');
Je me souviens de ce useFakeTimer qui n'était pas conseillé mais je ne sais plus si on avait eu un bug ou pas à cause de ça :/

2021-04-16 12:32 UTC, cmolle commented on tests/integration/questionnaires.test.js
> +  describe('TRAINING_ORGANISATION_MANAGER', () => {
Il faut changer le nom du describe du coup

2021-04-16 12:33 UTC, cmolle commented on tests/integration/questionnaires.test.js
> +      nowStub = sinon.stub(Date, 'now');
Ok laissons comme ca alors.

2021-04-16 12:40 UTC, ulysseferreira commented on tests/integration/questionnaires.test.js
> +  describe('TRAINING_ORGANISATION_MANAGER', () => {
damn je suis naze...

2021-04-16 12:51 UTC, sophiemoustard approved these changes

2021-04-16 13:03 UTC, cmolle approved these changes

2021-04-16 13:28 UTC, merged