Com 2078 - MEP Intermédiaire
sophiemoustard/alenvi-api pull request #1409
Opened 2021-05-12 17:09 UTC by KennyCallegari

### TESTS
- [x] Mon code est testé unitairement

- Tests intégrations :
  - Ce n'est pas une ancienne route utilisée par les apps mobiles
      - [x] J'ai bien fait les tests
  - ~~C'est une ancienne route utilisée par une des apps mobiles~~
    - J'ai changé ce qu'acceptait ou ce que renvoyait la route (noms de champs, format, conditions)
      - [ ] J'ai fait de nouveaux tests sans modifier les anciens pour s'assurer que les anciennes versions des
      apps mobiles fonctionnent

### FONCTIONNALITÉS APPS MOBILES
- Si mes changements impactent l'application formation :
  - [x] J'ai testé que les anciennes versions maintenues fonctionnent toujours (a minima):
    - [x] Affichage des pages explorer/mes formations/About/CourseProfile
    - [x] Inscription a une formation e-learning
    - [x] Possibilité de faire une activité

- ~~Si mes changements impactent l'application erp :~~
  - [ ] J'ai testé que les anciennes versions maintenues fonctionnent toujours

### ~~MODIFICATIONS SUR LES ROUTES IMPACTANT UNE AUTRE PLATEFORME~~
- ~~[ ] J'ai décrit dans le cas d'usage les choses à tester sur l'autre plateforme~~
- ~~Je n'ai pas fait de breaking change :~~
  - ~~[ ] Je n'ai pas changé les droits de la route~~
  - ~~[ ] Je n'ai pas changé les droits dans le fichier rights.js~~
  - ~~[ ] Je n'ai pas fait de changement sur le prehandler qui implique le mobile~~
  - ~~[ ] Je n'ai pas changé le type d'un paramètre ou enlevé des valeurs possibles~~
  - ~~Justification des breaking changes s'il y en a:~~
- ~~J'ai supprimé une route :~~
  - [ ] Les anciennes versions mobiles + les actuelles ne l'utilisent pas
- ~~J'ai renommé une route :~~
  - [ ] La route n'est pas utilisée par les apps mobiles 
    (si la route est utilisée en mobile: ne pas la renommer et plutôt créer une nouvelle route utilisée par la WEBAPP
    et toutes les nouvelles versions mobiles)
- ~~J'ai ajouté un champ possible dans la route :~~
  - [ ] J'ai géré le cas ou on ne l'envoie pas
- ~~J'ai rendu obligatoire un champs de la route :~~
  - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
- ~~J'ai retiré un champ possible dans la route :~~
  - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas
- ~~J'ai supprimé un retour/un champs du retour de la route :~~
  - [ ] Les anciennes versions mobiles + les actuelles n'utilisent pas ce retour

### ~~MODIFICATIONS SUR LES MODÈLES~~
- ~~J'ai ajouté un modèle spécifique à une structure:~~
  - [ ] J'ai ajouté le champ company ainsi que les preHooks associés
- ~~J'ai changé un modèle utilisé par l'app mobile:~~
  - J'ai ajouté un champ possible :
    - [ ] J'ai géré le cas où l'application ne l'envoie pas
  - J'ai rendu obligatoire un champs :
    - [ ] Il est toujours envoyé par les apps mobiles (même par les anciennes versions)
  - J'ai retiré un champ possible :
    - [ ] Les anciennes versions mobiles + les actuelles ne l'envoient pas

### CONSTANTES ET VARIABLE D'ENV
- ~~J'ai changé une constante :~~
  - [ ] Elle n'est pas utilisée sur les apps mobiles (sinon on doit forcer la maj des apps)

- ~~J'ai ajouté une variable d'environnement :~~
  - [ ] J'ai précisé sur le slite de MES et MEP les modifications faites

### POUR TESTER LA PR
- Périmetre interface : mobile

- Périmetre roles : tous

- Cas d'usage : 
A tester sur iOS et Android :
  - Je me connecte sur mobile, j'accepte les notifications, je m'inscris sur la webapp à une formation mixte -> je reçois une notification -> je clique sur cette notification, je suis envoyé sur la page a propos de la formation à laquelle j'ai été inscris
  - Je me déconnecte et je m'inscris à un formation blended -> pas de notification
  - Je me re-connecte et je mets l'app en arrière plan -> je reçois une notification
  - Je retire les notifications de mon mobile -> pas de notification
  - Je me connecte avec un autre compte -> pas de notification si j'inscris mon ancien compte mais j'ai bien une notification sur le nouveau compte
  - Je me connecte sur un autre mobile (n'hésitez pas à voler le portable de vos proches) -> j'ai une notification sur tous mes appareils qui ont acceptés les notifications et sur lesquels je suis connecté.

2021-05-12 17:25 UTC, KennyCallegari commented on src/routes/users.js
>    },
Je ne voyais pas comment passer par la route PUT /users/_id donc j'ai préféré faire une fonction à part.
D'ailleurs je trouve cette solution plus élégante, que pensez-vous de créer une route POST /{_id}/formation-expo-token/ pour ajouter les expoToken plutôt que de passer par la route PUT ?

2021-05-17 07:30 UTC, sophiemoustard requested changes

2021-05-17 07:30 UTC, sophiemoustard commented on src/helpers/users.js
> +exports.removeFormationExpoToken = async (userId, formationExpoToken) => {
tu pourrais faire directement

`exports.removeFormationExpoToken = async (userId, formationExpoToken) => User.updateOne({ _id: userId }, { $pull: { formationExpoTokenList: formationExpoToken } });`

2021-05-17 07:30 UTC, sophiemoustard commented on src/routes/users.js
> +      path: '/{_id}/formation-expo-token/{formationExpoToken}',
est ce qu'on ne pourrait pas trouver un format de route qui fonctionne aussi pour le token erp ?

2021-05-17 07:55 UTC, ulysseferreira commented on tests/unit/helpers/users.test.js
> +  it('should update user and delete media', async () => {
je suis pas très sûr de ce nom de test

2021-05-17 07:55 UTC, ulysseferreira commented on src/routes/users.js
> +            _id: Joi.objectId().required(),
on peut supprimer le token d'un autre utilisateur ou seulement de soi ?

2021-05-17 07:55 UTC, ulysseferreira commented on src/routes/users.js
>    },
ça me choque pas, je sais pas si on a déjà des cas de figure où le champ existe en BDD mais est vide et où on le remplis pour voir si on le fait avec put ou post

2021-05-17 09:01 UTC, KennyCallegari commented on src/helpers/users.js
> +exports.removeFormationExpoToken = async (userId, formationExpoToken) => {
done

2021-05-17 09:02 UTC, KennyCallegari commented on src/routes/users.js
> +      path: '/{_id}/formation-expo-token/{formationExpoToken}',
on peut oui 👍

2021-05-17 09:23 UTC, KennyCallegari commented on tests/unit/helpers/users.test.js
> +  it('should update user and delete media', async () => {
haha, done

2021-05-17 09:25 UTC, KennyCallegari commented on src/routes/users.js
> +            _id: Joi.objectId().required(),
Je voulais laisser la possibilité aux admin de modifier le token, notamment pour les scripts. Je trouve ça logique que les roles avec users:edit puissent modifier tous les champs de user.
Qu'en penses-tu ?

2021-05-17 09:34 UTC, ulysseferreira commented on src/routes/users.js
> +            _id: Joi.objectId().required(),
Ah oui j'avais pas pensé à cette option, parce que sinon on aurait pu enlever ce paramètre et directement prendre req.auth._id. T'es sûr que c'est bloquant pour les scripts ?

2021-05-17 11:49 UTC, sophiemoustard commented on src/helpers/users.js
> +  { _id: userId }, { $pull: { formationExpoTokenList: expoToken } }
chaque argument doit etre a la ligne

2021-05-17 11:56 UTC, sophiemoustard requested changes

2021-05-17 11:56 UTC, sophiemoustard commented on src/routes/preHandlers/users.js
> -const checkExpoToken = async (req) => {
pourquoi enleves tu ce verification ?

2021-05-17 11:56 UTC, sophiemoustard commented on src/routes/users.js
> +            _id: Joi.objectId().required(),
je rejoins l'interrogation d'Ulysse... et je ne pense pas que ce soit une bonne idée de laisser cette possibilité la. et d'ailleurs, un admin n'a pas le droit de modifier un mot de passe par exemple
de mon point de vu ce n'est pas bloquant pour les scripts car je ne pense pas qu'un jour on veuille modifier la valeur du champ..
pour moi il n'y a pas de droit sur cette route et il faut verifier dans un prehandler que c'est bien l'utilisateur connecté.
Limite je me pose la question de faire une route `/users/expo-token/token` (enlever l'id et utiliser celui des `credentials`) mais je ne sais pas si c'est clair du coupque cette route ne concerne qu'un utilisateur

2021-05-17 11:59 UTC, sophiemoustard commented on src/routes/users.js
>    },
si on peut ! sachant que d'ailleurs, ce ne sont pas les memes droits sur la route

2021-05-17 13:18 UTC, KennyCallegari commented on src/routes/users.js
> +            _id: Joi.objectId().required(),
Je trouve aussi que la route /users/expo-token/token n'est pas trop claire, je préfère avec l'_id, quite à ajouter un preHandler

2021-05-17 13:20 UTC, KennyCallegari commented on src/helpers/users.js
> +  { _id: userId }, { $pull: { formationExpoTokenList: expoToken } }
done

2021-05-17 13:22 UTC, KennyCallegari commented on src/routes/preHandlers/users.js
> -const checkExpoToken = async (req) => {
ce preHandler envoyais une 403 si un autre utilisateur avait le même expoToken.
Or on souhaite laisser la possibilité à plusieurs utilisateurs d'utiliser le même téléphone donc il faut supprimer cette vérification

2021-05-17 14:21 UTC, sophiemoustard commented on src/routes/preHandlers/users.js
> -const checkExpoToken = async (req) => {
dans ce cas, que se passe-t-il si : 
- utilisateur A se connecte sur un telephone puis se deconnecte
- utilisateur B se connecte sur ce meme telephone
- on ajoute utilisateur A a une formation 
?

2021-05-17 14:24 UTC, KennyCallegari commented on src/routes/preHandlers/users.js
> -const checkExpoToken = async (req) => {
L'utilisateur A ne reçoit pas de notification puisqu'il n'est pas connecté

2021-05-17 15:24 UTC, KennyCallegari commented on src/routes/users.js
> +            _id: Joi.objectId().required(),
J'ai donc ajouté une route POST pour ajouter un token

2021-05-17 15:41 UTC, sophiemoustard commented on src/routes/preHandlers/users.js
> -const checkExpoToken = async (req) => {
et l'utilisateur B ?

2021-05-17 16:17 UTC, sophiemoustard commented on src/routes/preHandlers/users.js
> -const checkExpoToken = async (req) => {
ah oui, en fait tu le retires au moment de la deconnexion donc c'est bon

2021-05-18 06:23 UTC, sophiemoustard requested changes

2021-05-18 06:23 UTC, sophiemoustard commented on src/helpers/users.js
> +    { _id: userId, company: companyId },
pourquoi fais tu un filtre sur le champ `company` ?

2021-05-18 06:23 UTC, sophiemoustard commented on src/routes/preHandlers/users.js
> +    'origin',
tu peux le laisser sur un ligne

2021-05-18 08:18 UTC, KennyCallegari commented on src/helpers/users.js
> +    { _id: userId, company: companyId },
effectivement ! done

2021-05-18 08:21 UTC, KennyCallegari commented on src/routes/preHandlers/users.js
> +    'origin',
Il me semble que ce n'est pas notre convention d'écrire une array comme ça :/
Qu'en penses-tu ?

2021-05-18 08:29 UTC, KennyCallegari commented on src/routes/preHandlers/users.js
> -const checkExpoToken = async (req) => {
done !

2021-05-18 08:43 UTC, ulysseferreira commented on src/routes/users.js
> +            _id: Joi.objectId().required(),
sur une ligne

2021-05-18 08:43 UTC, ulysseferreira commented on src/routes/users.js
> +            formationExpoToken: expoTokenValidation.required(),
same

2021-05-18 08:43 UTC, ulysseferreira commented on tests/integration/users.test.js
> +describe('POST /users/:id #tag', () => {
tag à retirer

2021-05-18 08:45 UTC, ulysseferreira commented on src/routes/users.js
> +            expoToken: Joi.string().required(),
sur une ligne aussi

2021-05-18 08:51 UTC, KennyCallegari commented on tests/integration/users.test.js
> +describe('POST /users/:id #tag', () => {
done

2021-05-18 08:53 UTC, KennyCallegari commented on src/routes/users.js
> +            expoToken: Joi.string().required(),
Quand il y a 2 params, je n'ai pas l'impression qu'on les laisse sur une ligne, qu'en penses-tu ?

2021-05-18 08:54 UTC, KennyCallegari commented on src/routes/users.js
> +            _id: Joi.objectId().required(),
done

2021-05-18 08:54 UTC, KennyCallegari commented on src/routes/users.js
> +            formationExpoToken: expoTokenValidation.required(),
done

2021-05-18 08:59 UTC, ulysseferreira commented on src/routes/users.js
> +            expoToken: Joi.string().required(),
on le fait  dans card, company, course, step, program mais en effet c'est pas systématique, du coup je sais pas quelle est la règle

2021-05-18 09:43 UTC, sophiemoustard commented on src/routes/preHandlers/users.js
> +    'origin',
ah oui tu as raison !

2021-05-18 09:44 UTC, sophiemoustard commented on src/helpers/users.js
> +  const userId = credentials._id;
tu pourrasi simplifier et ne pas creer de variable
idem en dessous

2021-05-18 11:02 UTC, KennyCallegari commented on src/routes/preHandlers/users.js
> +    'origin',
je l'ai remis bien 👌

2021-05-18 11:03 UTC, KennyCallegari commented on src/helpers/users.js
> +  const userId = credentials._id;
done !

2021-05-18 11:07 UTC, KennyCallegari commented on src/routes/users.js
> +            expoToken: Joi.string().required(),
La règle est à fixer du coup. Instinctivement je dirai sur plusieurs ligne tout le temps, je trouve ça plus clair

2021-05-18 11:22 UTC, ulysseferreira commented on src/routes/users.js
> +            expoToken: Joi.string().required(),
ok

2021-05-18 11:23 UTC, ulysseferreira approved these changes

2021-05-18 13:12 UTC, sophiemoustard approved these changes

2021-05-18 13:14 UTC, merged