COM-1406 add mandatory subProgram in CourseCreationModal and review a…
sophiemoustard/alenvi-api pull request #980
Opened 2020-08-18 09:15 UTC by CorentinMartinot

…ccess to program

- [x] Mon code est testé unitairement
- [x] Mon code est testé avec des tests d'intégration

- Périmetre interface : vendeur

- Périmetre roles : admin

- Cas d'usage : liaison de la formation au sous-programme + esLint 'import/extension'

2020-08-18 09:51 UTC, KennyCallegari commented on tests/integration/seed/courseSlotsSeed.js
> +    subProgram: subProgramList[0]._id,
subProgram**s**List ?

2020-08-18 09:51 UTC, KennyCallegari commented on tests/integration/seed/coursesSeed.js
> +    name: 'sous-program',
sous programme ou sub program ^^

2020-08-18 10:15 UTC, CorentinMartinot commented on tests/integration/seed/courseSlotsSeed.js
> +    subProgram: subProgramList[0]._id,
done

2020-08-18 10:15 UTC, CorentinMartinot commented on tests/integration/seed/coursesSeed.js
> +    name: 'sous-program',
doen

2020-08-19 09:32 UTC, KennyCallegari requested changes

2020-08-19 09:32 UTC, KennyCallegari commented on src/helpers/courses.js
>    const possiblyMisc = course.misc ? ` - ${course.misc}` : '';
possibleMisc ?

2020-08-19 09:32 UTC, KennyCallegari commented on tests/integration/courses.test.js
> +            _id: expect.any(ObjectID),
Pourquoi pas programsList[0]._id ?

2020-08-19 09:32 UTC, KennyCallegari commented on tests/integration/seed/courseSlotsSeed.js
> +    subProgram: subProgramList[0]._id,
Tu ne rajoutes pas de **s** du coup ?

2020-08-19 09:32 UTC, KennyCallegari commented on tests/unit/helpers/courses.test.js
> +      subProgram: { program : { name: 'programme de formation' } },
subProgram: { program: <- espace en trop

2020-08-19 09:32 UTC, KennyCallegari commented on tests/unit/helpers/courses.test.js
> +      subProgram: { program : { learningGoals: 'Apprendre', name: 'nom du programme' } },
same

2020-08-19 09:41 UTC, CorentinMartinot commented on tests/integration/courses.test.js
> +            _id: expect.any(ObjectID),
done

2020-08-19 09:41 UTC, CorentinMartinot commented on src/helpers/courses.js
>    const possiblyMisc = course.misc ? ` - ${course.misc}` : '';
done

2020-08-19 09:41 UTC, CorentinMartinot commented on tests/unit/helpers/courses.test.js
> +      subProgram: { program : { name: 'programme de formation' } },
done

2020-08-19 09:41 UTC, CorentinMartinot commented on tests/unit/helpers/courses.test.js
> +      subProgram: { program : { learningGoals: 'Apprendre', name: 'nom du programme' } },
done

2020-08-19 09:43 UTC, sophiemoustard commented on src/helpers/courses.js
> +  .populate({ path: 'subProgram',  select: 'program steps', populate: { path: 'program', select: 'name image' } })
il y a un espace en trop avant le select

2020-08-19 10:08 UTC, sophiemoustard approved these changes

2020-08-19 10:37 UTC, KennyCallegari approved these changes

2020-08-19 10:37 UTC, merged