COM-1418 - fix eslint
sophiemoustard/alenvi-api pull request #982
Opened 2020-08-19 10:13 UTC by sophiemoustard

- [x] Mon code est testé unitairement
- [x] Mon code est testé avec des tests d'intégration

- Cas d'usage : 
maJ de eslint

2020-08-19 15:17 UTC, KennyCallegari commented on src/helpers/draftBills.js
> +    result.thirdPartyPayer = Object.keys(thirdPartyPayerPrices).reduce(
Pourquoi passer par reduce plutôt que par map ? Les deux font la même chose non ?

2020-08-19 15:27 UTC, KennyCallegari commented on src/models/Customer.js
>      delete doc.referent;
omit ?

2020-08-19 15:30 UTC, KennyCallegari commented on src/models/Customer.js
>      delete doc.referent;
Sinon désactive no-param-reassign tout court, il est pas très important : https://eslint.org/docs/rules/no-param-reassign
C'est juste pour éviter la 'confusion' et les typages foireux

2020-08-19 15:35 UTC, KennyCallegari commented on src/models/utils.js
>  const ESTABLISHMENT_NAME_VALIDATION = /^[a-zA-Z0-9éèêëâàäöôûüîïç°2!#$%&'()*+,\-./:;<=>?@ ]{1,32}$/;
la solution du /u ne marche pas ?
https://eslint.org/docs/rules/no-misleading-character-class

2020-08-19 16:47 UTC, sophiemoustard commented on src/models/Customer.js
>      delete doc.referent;
hum j'aime bien cette regle, justement pour eviter la confusion et avoir un code clair. 
le omit ne fonctionne pas car il ne modifie pas l'objet mais en cree un autre

2020-08-19 16:49 UTC, sophiemoustard commented on .eslintrc.js
> +    'consistent-return': 0,
Done

2020-08-19 16:50 UTC, sophiemoustard commented on .eslintrc.js
> +    'implicit-arrow-linebreak': 0,
a voir ensemble

2020-08-20 06:51 UTC, sophiemoustard commented on .eslintrc.js
> +    'no-restricted-syntax': 0,
Je te propose qu'on se garde ca pour du boyscout - Enlever cette règle entraine 121 erreurs et les corriger demande de toucher a beaucoup de fonctionnel qu'on aura pas le temps de bien tester avant la mep. On rissque d'introduire beaucoup de regressions dans la precipitation et on n'est pas en avance sur la fin de sprint

2020-08-20 06:51 UTC, sophiemoustard commented on .eslintrc.js
> +    'no-plusplus': 0,
idem

2020-08-20 06:56 UTC, sophiemoustard commented on src/helpers/draftBills.js
> +    result.thirdPartyPayer = Object.keys(thirdPartyPayerPrices).reduce(
non car le map te retourne un array et la je veux un objet

2020-08-20 07:19 UTC, KennyCallegari commented on .eslintrc.js
> +    'no-restricted-syntax': 0,
ça marche !

2020-08-20 07:32 UTC, KennyCallegari requested changes

2020-08-20 07:32 UTC, KennyCallegari commented on src/helpers/utils.js
>    for (let i = 0; i < format.length; ++i) {
i++

2020-08-20 07:34 UTC, sophiemoustard commented on src/helpers/utils.js
>    for (let i = 0; i < format.length; ++i) {
yes

2020-08-20 07:35 UTC, KennyCallegari approved these changes

2020-08-20 13:46 UTC, merged