COM-1452 display nbr of events on bill if service is fixed
sophiemoustard/alenvi-api pull request #998
Opened 2020-08-26 14:56 UTC by cmolle

- [x] Mon code est testé unitairement -np
- [ ] Mon code est testé avec des tests d'intégration -np

- Périmetre interface : client

- Périmetre roles : aidant et admin

- Cas d'usage : sur la facture pour les forfaits nuit je vois le nombre d'evenement et non pas le nombre d'heure (cf capture d'ecran sur le ticket)

2020-08-26 15:54 UTC, sophiemoustard requested changes

2020-08-26 15:54 UTC, sophiemoustard commented on tests/unit/helpers/bills.test.js
> +    const result = {
tu n'as pas besoin de cette constante en fait, tu peux la mettre directement dans le toEqual

2020-08-26 15:57 UTC, CorentinMartinot commented on src/helpers/bills.js
> +      formattedSub.hours = sub.events.length;
vaudrait pas mieux mettre volume ? (comme dans le pdf) on pourrait ne pas comprendre le hours === 1 des tests par exemple (qui font 40 h)

2020-08-26 16:17 UTC, sophiemoustard approved these changes

2020-08-27 07:33 UTC, KennyCallegari approved these changes

2020-08-27 08:04 UTC, merged